### ISSUE TITLE
<autogenerated-issue>

### ISSUE THREAD

**Issue by pihentagy** [DeterminateSystems/nix-installer#1015]
## Error
```
Error: 
   0: Planner error
   1: Error executing action
   2: Action `create_group` errored
   3: Group `nixbld` existed but had a different gid (997) than planned (30000)
```

## Metadata
|key|value|
|--|--|
|**version**|0.19.0|
|**os**|linux|
|**arch**|x86_64|

**Comment by cole-h** [comment]
If you previously used the upstream installer, you may need to follow their uninstallation instructions: https://nix.dev/manual/nix/2.18/installation/uninstall.html#uninstalling-nix
