### ISSUE TITLE
Failed to execute command `"mount" "-d"`: No such file or directory

### ISSUE THREAD

**Issue by fancyplants** [DeterminateSystems/nix-installer#1021]
## Error
```
Error: 
   0: Planner error
   1: Error executing action
   2: Action `configure_nix` errored
   3: Action `place_nix_configuration` errored
   4: Action `create_directory` errored
   5: Failed to execute command `"mount" "-d"`
   6: No such file or directory (os error 2)
```

## Metadata
|key|value|
|--|--|
|**version**|0.19.0|
|**os**|macos|
|**arch**|aarch64|

## Other Info
Used to have `nix-darwin` and `nix` (installed with DeterminateSystems' installer) installed on this device, but I uninstalled because on most boots (but not all), I would get a message asking me to add a password to login to the Nix store. Even when saving to keychain, I would get this almost all the time, and none of the running daemons I specified in nix-darwin (like yabai, skhd, etc.) would actually be running on boot.

Let me know if I can provide any other info.

**Comment by cole-h** [comment]
Hm, that's strange. It looks like it thinks the `mount` binary doesn't exist..? If you run `which mount`, does that return anything? If you try again, do you get the same error?

Could you try again and pass `-vv` to output trace logs and post them here (or gist them and post the link)?

**Comment by fancyplants** [comment]
Aha! It was indeed an issue where `mount` was an unavailable command in my shell. For some reason or other, the installer worked perfectly after running it in iTerm instead of the base MacOS Terminal. I'll have to investigate this more, but this was the difference:

Terminal `which mount`: `mount not found`
iTerm `which mount`: `/sbin/mount`

It appears to be that iTerm just adds more to the `$PATH` var.

**Comment by Ch4s3r** [comment]
Could we maybe add the `/sbin/` internally, so when using the standard terminal, you don't have to change the `PATH` and it has a smoother experience for all newcomers?
Had that issue several times and was never sure why it happened.
Switched then to the normal nix installer.
But now that i now this, there are no hiccups anymore uninstalling and installing again.
