### ISSUE TITLE
New warning "warning: unknown experimental feature 'repl-flake'" after upgrading nix to 2.23.3

### ISSUE THREAD

**Issue by kastl-ars** [DeterminateSystems/nix-installer#1048]
I just upgraded nix using `sudo -i nix upgrade-nix` as stated in the README.

Now I have a new warning printed multiple times on each command, e.g. `nix-channel --update`

```
$ nix-channel --update
warning: unknown experimental feature 'repl-flake'
warning: unknown experimental feature 'repl-flake'
unpacking 2 channels...
warning: unknown experimental feature 'repl-flake'
```

It might be a good idea to add instructions to the README on how to handle things like that. I guess I need to adapt a config file somewhere?
(No mention of it in `~/.config/nix/nix.conf`)

Kind Regards,
Johannes

**Comment by cole-h** [comment]
This is configured in `/etc/nix/nix.conf`. You should see a line like `experimental-features = nix-command flakes repl-flake` -- just remove `repl-flake` from there and you should be good to go!

**Comment by kastl-ars** [comment]
Thanks, that worked. I checked all of my $HOME for configuration, but did not think of /etc/...
