### ISSUE TITLE
Packaging nix-installer for openSUSE: How to set NIX_INSTALLER_TARBALL_PATH properly (and elegantly)?

### ISSUE THREAD

**Issue by kastl-ars** [DeterminateSystems/nix-installer#1049]
Hi,

to make use of nix and home-manager easier on openSUSE I tried to package the nix-installer.

However I need to set the `NIX_INSTALLER_TARBALL_PATH` variable to point to a tarball.

Is there a way to get the "appropriate" version during build? I understand that each nix-installer version has a corresponding nix version that "fits". I would of course like to use that, possibly without having to hardcode a nix version.

Is there some nice trick that does not involve having nix installed already?

Kind Regards
Johannes

**Comment by cole-h** [comment]
You should be able to download the tarballs from `releases.nixos.org` (e.g. https://releases.nixos.org/?prefix=nix/nix-2.23.3) and use that as the `NIX_INSTALLER_TARBALL_PATH`.

If you go that route, please make sure to follow the Nix version we install, as it will be difficult for us to support other versions, since we don't test every possible Nix version.

**Comment by kastl-ars** [comment]
> If you go that route, please make sure to follow the Nix version we install, as it will be difficult for us to support other versions, since we don't test every possible Nix version.

Thanks for your reply. My question was more on **how** to find out "the Nix version we install" when packaging. Is there a file inside the repository that contains the version string? Where is this documented (maybe I can use that to derive the version)?

Kind Regards,
Johannes

**Comment by cole-h** [comment]
Ah, I misunderstood.

Right now, it's pinned in the flake.nix:

https://github.com/DeterminateSystems/nix-installer/blob/51a1467b45eda46c861534e48d7fe91f77e65e1d/flake.nix#L18

**Comment by kastl-ars** [comment]
OK, perfect, then I can somehow extract that version.

Thanks!
