### ISSUE TITLE
Fedora Silverblue: toolbx doesn't inherit nix-profile in PATH

### ISSUE THREAD

**Issue by axelsimon** [DeterminateSystems/nix-installer#1060]
Hi,
Not sure who is "responsible" for this, but on Fedora Silverblue, with nix installed using `nix-installer`, when entering a [toolbx](https://containertoolbx.org/) with `toolbox enter` the toolbx doesn't inherit the PATH and so none of the packages installed with nix are available. Toolbx is the default option for creating mutable environments in Silverblue (given the OS is otherwise immutable).

I'm using home-manager and so this means toolbx doesn't get starship, direnv etc.

I'd love to find a way to fix this :)

**Comment by cole-h** [comment]
I'm not familiar with `toolbx`, but it looks like `toolbox enter` gives you a shell inside a container (just going off the docs at https://github.com/containers/toolbox/blob/cb6eee85ef88a0dc8694707d29737f61fa0ac330/doc/toolbox-enter.1.md: "toolbox-enter - Enter a Toolbx container for interactive use").

You'll probably want to engage with them and ask how to pass your external environment variables into the container. If you/they have any suggestions on how we can improve this, we're all ears! But for now, I'm going to close this, as I don't think there is anything we can do at this moment.
