### ISSUE TITLE
File '/dev/full' has an unsupported type in Docker

### ISSUE THREAD

**Issue by mausch** [DeterminateSystems/nix-installer#1066]
Given this dockerfile:

```
FROM ubuntu:24.04

RUN apt update -y && apt install curl -y
RUN curl -sSf -L https://github.com/DeterminateSystems/nix-installer/releases/download/v0.20.2/nix-installer-x86_64-linux -o nix-installer
RUN chmod +x nix-installer
RUN ./nix-installer install linux \
  --extra-conf "sandbox = false" \
  --init none \
  --no-confirm
ENV PATH="${PATH}:/nix/var/nix/profiles/default/bin"

# WORKDIR /workdir

COPY flake.nix .

RUN nix run
```

and a trivial flake.nix:

```
{
  inputs = {
    nixpkgs.url = "github:nixos/nixpkgs?ref=nixos-unstable";
  };

  outputs = { self, nixpkgs }: {

    packages.x86_64-linux.hello = nixpkgs.legacyPackages.x86_64-linux.hello;

    packages.x86_64-linux.default = self.packages.x86_64-linux.hello;

  };
}
```

Building the docker image crashes at the `nix run` step with:

```
#11 [7/7] RUN nix run
#11 0.174 error:
#11 0.174        … while fetching the input 'path:/'
#11 0.174 
#11 0.174        error: file '/dev/full' has an unsupported type
#11 ERROR: process "/bin/sh -c nix run" did not complete successfully: exit code: 1
------
```

Setting a WORKDIR fixes this. Problem is the error message is pretty obscure. Should this be reported upstream?

**Comment by cole-h** [comment]
I think the issue is that flakes copy their containing directory to the Nix store. Since you're copying your `flake.nix` (as an aside: you should also copy the `flake.lock`) to the root of the docker image, you're seeing this error. If you copy it to a directory anywhere underneath `/`, then it'll only copy that directory and not try to copy any `/dev` or `/proc` nodes unnecessarily.

I don't think there's anything we or upstream can do about this -- it's just how flakes work.

**Comment by mausch** [comment]
> as an aside: you should also copy the flake.lock

Yep I do that. This is just a minimal repro.

>  it's just how flakes work.

Thanks, yep I get that. This is not about the issue itself but about the obscure error message.
Surely something can be done about that?

**Comment by cole-h** [comment]
Ah, if it's about the error message, then yes, this issue would be more appropriate upstream. Unfortunately, that's an error message from Nix itself, so we can't do anything in the installer to fix it :(
