### ISSUE TITLE
The volume "Nix Store" on disk3s8 couldn't be unmounted because it is in use by process 0 (kernel)

### ISSUE THREAD

**Issue by aron-silverton** [DeterminateSystems/nix-installer#1085]
## Error
```
Error: 
   0: Error reverting
   0: Action `create_or_merge_nix_config` errored
      Remove file `/etc/nix/nix.conf`

      Action `create_apfs_volume` errored
      Failed to execute command with status 1 `"/usr/sbin/diskutil" "apfs" "deleteVolume" "Nix Store"`, stdout: Started APFS operation
      Deleting APFS Volume from its APFS Container
      Unmounting disk3s8
      The volume "Nix Store" on disk3s8 couldn't be unmounted because it is in use by process 0 (kernel)

      stderr: Error: -69888: Couldn't unmount disk



```

## Metadata
|key|value|
|--|--|
|**version**|0.20.2|
|**os**|macos|
|**arch**|aarch64|

**Comment by cole-h** [comment]
Does rebooting and rerunning the `deleteVolume` command from the error message resolve this for you?

**Comment by aron-silverton** [comment]
IIRC, I unmounted with diskutil and then deleted it. FWIW, I re-ran the un-installer and got a lot more error messages, but they mostly seemed to be from things that were already done. My general takeaway, is that that nix-darwin un-installer didn't do a very good job cleaning up after itself before I ran your un-installer. All seems fine now - I was able to remove everything and reinstall. 

This issue can be closed.

**Comment by cole-h** [comment]
Thanks for reporting back! I'll go ahead and close as you suggested, but if you have any concrete examples on what the nix-darwin uninstaller failed to clean up properly, let us know! We could attempt to detect it ourselves and improve error messages and whatnot.

**Comment by aron-silverton** [comment]
Off the top-of-my head, anything that was renamed "*.before-nix-darwin" was not restored. This included `/etc/{bashrc, zprofile, zshenv, zshrc}` and /etc/nix/nix.conf. After running your uninstaller I still had `/Library/LaunchDaemons/org.nixos.nix-daemon.plist.` I also had a lot of cruft from home-manager, but that's a different issue. I'll probably repeat this at some point in the future and can file another issue then.
