### ISSUE TITLE
(Re)Installation failure on MacOS Sonoma 14.6.1

### ISSUE THREAD

**Issue by jbgreer** [DeterminateSystems/nix-installer#1098]
Greetings.   I am encountering an error when attempting to install Nix on my M1 Mac Mini running Sonoma 14.6.1 and would appreciate feedback on the error and advice on how to successfully complete the install.   I would be happy to retry and provide additional information. 

My initial installation finished with a message indicating the installation was successful, but the 'nix' command was not in my path even after starting a new shell (including logout).  I currently use stow to symlink various config files includes zsh and use XDG settings to park my config files under ~/.config.  Thinking that might be an issue, I
- Uninstalled Nix using Determinate Systems installer.
- Rebooted the machine just in case there were lingering processes ,etc.
- Created a new admin user account on the machine.
- Attempted to install Nix using the same method on the new user account, which does not use stow / XDG.
- Failed during the installation process.
- Uninstalled as part of the unwinding of the installation process.
- Decided to try again on my original user account and pay closer attention, assuming that my issue was not related to use of stow/XDG.

Before restarting on my original user account, I confirmed:
-  no entries in fstab
-  no entries in launchcrtl with nix, 
-  no /nix directory, no /etc/nix* files.

I am getting the error below during the installation process.  I do wish there was a little more detail on the command - sudo?  user?  output?

## Error
```
Error: 
   0: Install failure
   1: Error executing action
   2: Action `configure_init_service` errored
   3: Failed to execute command with status 5 `"launchctl" "bootstrap" "system" "/Library/LaunchDaemons/org.nixos.nix-daemon.plist"`, stdout: 
      stderr: Bootstrap failed: 5: Input/output error


```

The file '/Library/LaunchDaemons/org.mixos.nix-daemon.plist' exists.
The file /nix/var/nix/profiles/default/bin/nix-daemon exists.
The file /var/log/nix-daemon.log is empty.

I note that the action references "configure_init_service", which I assume is:
    https://github.com/DeterminateSystems/nix-installer/blob/main/src/action/common/configure_init_service.rs

In It I see references to:
    const TMPFILES_SRC: &str = "/nix/var/nix/profiles/default/lib/tmpfiles.d/nix-daemon.conf";
    const TMPFILES_DEST: &str = "/etc/tmpfiles.d/nix-daemon.conf";
neither of which exist.

The installer initiated an uninstallation due to the failed step.   Anticipating planned actions, I checked for the existence of changes that should have been made by the installer and see evidence of almost all.  I would guess that the uninstallation process unwinds changes in the opposite order of installation.

* Unconfigure Nix daemon related settings with launchctl
     launchctl list | grep nix reveals no matching entry, correlating with the above error.
* Delete file `/Library/LaunchDaemons/systems.determinate.nix-installer.nix-hook.plist`
    As above, this file exists.
* Remove the Nix configuration from zsh's non-login shells
   File /etc/zsh/zsh exists and contains references to /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh, which exists.
* Unconfigure the shell profiles
    Not certain what this step entails.
* Remove the Nix configuration in `/etc/nix/nix.conf`
    File /etc/nix/nix.conf exists.
* Unset the default Nix profile
* Remove time machine exclusions
    Checking Settings->General->Time Machine, I do not see any additional exclusions.
* Remove Nix users and group
    In Settings->Users & Groups->Groups I see a "Nix build group for nix-daemon".
  `dscl . list /groups | grep nix` lists 'nixbld'
  `dscl . list /users | grep nix` lists the 32 _nixbld[0-9]* accounts.
* Remove the directory tree in `/nix`
    Directory '/nix' exists.
* Remove the APFS volume `Nix Store` on `disk3`
    I see a Nix-Store comment and entry in /etc/fstab
   Disk Utility lists a 'Nix Store' APFS file system.

## Metadata
|key|value|
|--|--|
|**version**|0.20.2|
|**os**|macos|
|**arch**|aarch64|

**Comment by jbgreer** [comment]
Follow up: I appear to have successfully installed Nix, but have noticed that the previous uninstallation process did not appear to complete automatically.  In particular, the /Library/LaunchDaemons/org.nixos.nix-daemon.plist file was not successfully removed during uninstallation, and this interfered with my reinstall attempt.

I note that the installer includes -v and -vv verbosity options; might I recommend that users having difficulty during installation reattempt with one of those options? 

Steps in my process:
- Finished the uninstallation process from my previous attempt at installation.
- Noted that the /nix directory was not removed; attempted to `sudo rmdir nix` but noted that directory was read-only.
- Rebooted machine
- Checked for /nix directory and confirmed it no longer existed.

- Downloaded the nix-installer.sh script from the zero-to-nix 'quick start' webpage and made executable.
- Attempted an installation, collecting full trace information, redirecting stderr to stout, to file foo.out
    ./nix-installer.sh -vv install 2>&1 | tee foo.out
- Noted error message about /Library/LaunchDaemons/org.nixos-nix-daemon.plist 
- Removed file via `sudo rm -f /Library/LaunchDaemons/org.nixos-nix-daemon.plist`
- Retried installation.  Received success message.
- Performed `. /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh`
- Performed `nix --help`. Success!

**Comment by jbgreer** [comment]
Unfortunately, my success was short-lived.
Having restarted the machine to ensure things were in good order, I find that
- the `nix` command is not in my path
- ~/.nix-profile, which is symlinked to /Users/<username>/.local/state/nix/profiles/profile, is invalid.  That is, there is a ~/.nix-profile link, but the file is it linked to is missing, as there is no file 'profile' in that directory.

Curious.

**Comment by jbgreer** [comment]
[ got a chance to play around more a few hours later ]
I successfully uninstalled & reinstalled and see the same behavior:  the installation shell has the correct path, by which I mean one prepended with:
    PATH=/Users/<username>/.nix-profile/bin:/nix/var/nix/profiles/default/bin
but other shells do not.  All other environmental variables appear the same, including XDG_DATA_DIRS, which is not set by my zsh files but which references nix specific files:
  XDG_DATA_DIRS=/usr/local/share:/usr/share:/Users/<username>/.nix-profile/share:/nix/var/nix/profiles/default/share

It appears that /etc/zsh/zshrc is not being executed?  That file is added by nix and calls
    . /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh

The second to last line of that script is :
    export PATH="$NIX_LINK/bin:/nix/var/nix/profiles/default/bin:$PATH"
which corresponds to the addition to the working installation shell.

**Comment by jbgreer** [comment]
Resolved the path issue: I was resetting my path in my $ZDOTDIR/.zshrc and in the process removing the Nix entries.

**Comment by jbgreer** [comment]
Nix install is working correctly.  That said, it does appear that the Determinate Systems Nix installer does not completely remove all files, and in not doing so may cause issues if one re-installs.

**Comment by cole-h** [comment]
@jbgreer Do you happen to know which files we don't remove? We definitely should be removing everything we place (unless an error occurs that prevents that from happening, that is), that's one of the main reasons we have the receipt system in the first place.

**Comment by jbgreer** [comment]
@cole-h 
At least /Library/LaunchDaemons/org.nixos.nix-daemon.plist appear to not be removed during uninstallation.
