### ISSUE TITLE
<autogenerated-issue> Installation failed on Mac OSX Sequoia 15.0 Beta (24A5327a)

### ISSUE THREAD

**Issue by alishahlakhani** [DeterminateSystems/nix-installer#1114]
## Error
```
Error: 
   0: Planner error
   1: Error executing action
   2: Action `create_users_and_group` errored
   3: Action `create_user` errored
   4: User `_nixbld5` existed but had a different uid (305) than planned (455)
```

## Metadata
|key|value|
|--|--|
|**version**|0.20.2|
|**os**|macos|
|**arch**|aarch64|

**Comment by cole-h** [comment]
Related to https://github.com/DeterminateSystems/nix-installer/issues/1001.

It sounds like you updated to macOS 15 with Nix installed. Upstream has created a migration script that you may be interested in trying out until we have our own solution to help repair these systems: https://github.com/NixOS/nix/blob/076b6f7bb163a95e6a6537aad21d9661b0c6c8fa/scripts/sequoia-nixbld-user-migration.sh

**Comment by cole-h** [comment]
(Closing this in favor of the issue linked in my previous comment.)
