### ISSUE TITLE
Unexpected argument and outdated version

### ISSUE THREAD

**Issue by dougg0k** [DeterminateSystems/nix-installer#1116]
Complains about the last arg and giving outdated version 0.20.2 rather than latest.

```
nu ✗ curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix | sh -s -- install --determinate
info: downloading installer https://install.determinate.systems/nix/tag/v0.20.2/nix-installer-x86_64-linux
error: unexpected argument '--determinate' found

  tip: to pass '--determinate' as a value, use '-- --determinate'

Usage: nix-installer install [OPTIONS] [PLAN]
       nix-installer install <COMMAND>

For more information, try '--help'.
```

**Comment by cole-h** [comment]
When fetching from the unversioned URL, we do ratio-based rollouts to ensure that everything is in tip-top shape before making it 100% available. Over the next couple of days, the new 0.22.0 release will become the default version (as long as we don't notice anything strange).

In the meantime, you can specify an exact version in the url, like `https://install.determinate.systems/nix/tag/v0.22.0` (or any other tagged version).
