### ISSUE TITLE
Could not find service "org.nixos.darwin-store" in domain for system

### ISSUE THREAD

**Issue by kaihendry** [DeterminateSystems/nix-installer#1124]
I am trying https://www.reddit.com/r/NixOS/comments/1efsg5c/upgrade_to_macos_146_nuked_macnix/lfn6jip/ since the Nix one's  /run/current-system seems to get removed between upgrades on my work MDM machine.

## Error
```
Error: 
   0: Install failure
   1: Error executing action
   2: Action `create_nix_volume` errored
   3: Action `kickstart_launchctl_service` errored
   4: Failed to execute command with status 113 `"launchctl" "kickstart" "-k" "system/org.nixos.darwin-store"`, stdout: 
      stderr: Could not find service "org.nixos.darwin-store" in domain for system


```

## Metadata
|key|value|
|--|--|
|**version**|0.22.0|
|**os**|macos|
|**arch**|aarch64|

**Comment by cole-h** [comment]
Could you take a look at my comment in this similar issue and see if it helps you get further? https://github.com/DeterminateSystems/nix-installer/issues/960#issuecomment-2104730686

**Comment by cole-h** [comment]
I'm going to close this as a duplicate of the linked issue, pending further information. Feel free to reopen if you can give some more information!
