### ISSUE TITLE
`nix-installer install --extra-conf` cannot set `extra-trusted-substituters` and `extra-trusted-public-keys`

### ISSUE THREAD

**Issue by l2dy** [DeterminateSystems/nix-installer#1133]
The user-specified extra configuration should have precedence over or be merged with `nix-installer` defaults, but the following overrides user config.

https://github.com/DeterminateSystems/nix-installer/blob/36ed46823d0e0dc40b11141ee921789664e44a1c/src/action/common/place_nix_configuration.rs#L124-L135

**Comment by cole-h** [comment]
This should be fixed in https://github.com/DeterminateSystems/nix-installer/pull/1145. If you're willing / able, would you mind giving that a shot?

```
curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix/pr/1145 | sh -s -- install --extra-conf 'extra-trusted-substituters = foo'
```

**Comment by l2dy** [comment]
Thanks! Sorry I'm not able to test this PR for the time being.
