### ISSUE TITLE
Waiting for /nix to exist doesn't succeed within 5s

### ISSUE THREAD

**Issue by sherman1-rbi** [DeterminateSystems/nix-installer#1140]
## Error
```
Error: 
   0: Install failure
   1: Error executing action
   2: Action `create_nix_volume` errored
   3: Failed to execute command with status 1 `"/usr/sbin/diskutil" "info" "/nix"`, stdout: 
      stderr: Could not find disk: /nix


```

## Metadata
|key|value|
|--|--|
|**version**|0.24.0|
|**os**|macos|
|**arch**|aarch64|

## Backtrace

<details>

```
Backtrace:
   0: __mh_execute_header
   1: __mh_execute_header
   2: __mh_execute_header
   3: __mh_execute_header
   4: __mh_execute_header
   5: __mh_execute_header
   6: __mh_execute_header
   7: __mh_execute_header
   8: __mh_execute_header
   9: __mh_execute_header
  10: __mh_execute_header
  11: __mh_execute_header
  12: __mh_execute_header

```
</details>

**Comment by cole-h** [comment]
Hm, we retry there for ~5s to see if the disk shows up... We might want to increase it to 15 seconds. If you try to install again, does it work the second time?

**Comment by sherman1-rbi** [comment]
I tried a few times, but encounter this issue every time (this specific case with backtrace enabled was my 3rd attempt)

**Comment by cole-h** [comment]
I've opened #1141 to hopefully resolve this issue. Please try it and report back:

```
curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix/pr/1141 | sh -s -- install
```

**Comment by sherman1-rbi** [comment]
> That's disappointing to hear, sorry for the inconvenience. Let me whip up a quick patch for you to try that might help with this.

No apologies required whatsoever. I really appreciate the work you all have put into improving the onboarding experience. 

> I've opened https://github.com/DeterminateSystems/nix-installer/pull/1141 to hopefully resolve this issue. Please try it and report back:

This worked :) - thank you so much for the incredible turnaround time here.

**Comment by cole-h** [comment]
Thanks for trying it out! That'll be available in the next release (which hopefully isn't much longer than a week away -- if it is, I'll cut a patch release with it instead.).
