### ISSUE TITLE
<autogenerated-issue>

### ISSUE THREAD

**Issue by jornslegers** [DeterminateSystems/nix-installer#1144]
## Error
```
Error: 
   0: Planner error
   1: Error executing action
   2: Action `create_group` errored
   3: Group `nixbld` existed but had a different gid (30000) than planned (350)
```

## Metadata
|key|value|
|--|--|
|**version**|0.24.0|
|**os**|macos|
|**arch**|x86_64|

**Comment by cole-h** [comment]
This sounds like you have a previous Nix installation already. If it was through our installer, you'll want to uninstall via `/nix/nix-installer uninstall` before you can rerun the installer. If it was through the upstream install scripts, you'll need to follow their uninstall instructions: https://nix.dev/manual/nix/stable/installation/uninstall.html#macos

If that doesn't work, feel free to reopen this issue!
