### ISSUE TITLE
User `_nixbld2` existed but had a different uid (302) than planned (352)

### ISSUE THREAD

**Issue by mubarak23** [DeterminateSystems/nix-installer#1154]
## Error
```
Error: 
   0: Planner error
   1: Error executing action
   2: Action `create_users_and_group` errored
   3: Action `create_user` errored
   4: User `_nixbld2` existed but had a different uid (302) than planned (352)
```

## Metadata
|key|value|
|--|--|
|**version**|0.24.0|
|**os**|macos|
|**arch**|aarch64|

**Comment by cole-h** [comment]
Did you previously install Nix via our installer or via the upstream scripts?

**Comment by mubarak23** [comment]
> Did you previously install Nix via our installer or via the upstream scripts?

i did on my macbook 2019, 

then migrated
 the to m2 chip macbook pro 2023

**Comment by cole-h** [comment]
Sorry, that doesn't quite answer my question. How did you install Nix the first time before you got the error that `_nixbld2` already exists with UID `302` -- was it by `curl -L https://nixos.org/nix/install` or by `curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix | sh -s -- install`?

**Comment by cole-h** [comment]
If you want to reinstall, you'll probably want to uninstall first. `/nix/nix-installer uninstall` should get you going on that.

**Comment by cole-h** [comment]
I don't think there's anything more to do here, so I'm going to close this issue. If that's not the case, please reopen with more information!
