### ISSUE TITLE
How do I upgrade `nix-installer` itself?

### ISSUE THREAD

**Issue by bryanhonof** [DeterminateSystems/nix-installer#1164]
Once I've got a working installation of Nix, how do I make sure `nix-installer` under `/nix/nix-installer` stays up-to-date?

**Comment by cole-h** [comment]
Out of curiosity, why do you want to upgrade `nix-installer`?

In general, we don't have any provisions for upgrading it (because we don't see it as necessary), aside from uninstalling with `/nix/nix-installer uninstall` and reinstalling with the new version. After installation, `/nix/nix-installer` shouldn't be needed for anything (aside from repairing shell profiles, if necessary, and uninstalling).

**Comment by bryanhonof** [comment]
> Out of curiosity, why do you want to upgrade nix-installer?

I thought that with the release of [v0.26.0](https://github.com/DeterminateSystems/nix-installer/releases/tag/v0.26.0), I'd need to update `nix-installer` to prepare myself for the macOS Sequoia update. So that I could do the repair offline when the update hits.

I guess I could also just pre-download the script & tool, but I thought it'd be cool if I was able to update `nix-installer` and be prepared.

**Comment by cole-h** [comment]
In the release notes for https://github.com/DeterminateSystems/nix-installer/releases/tag/v0.26.0, I've documented a way to be prepared without needing to reinstall. If you run the snippet on that page, the repair tool will migrate your users to the Sequoia-compatible UID range, and Nix will continue working after you take the macOS Sequoia upgrade!

If there's anything I can do to make it clearer that you don't need to wait and don't need to uninstall-reinstall / upgrade your current `nix-installer`, please let me know!

**Comment by bryanhonof** [comment]
Oh, I did get that, but it requires me to first curl that command. I was thinking it'd be possible to do this offline, right after the macOS update.

Might just be a misconception on my end. 😅

**Comment by cole-h** [comment]
I guess my confusion stems from why you want to wait to do it after the update. You could do it right now (with the invocation in the release notes), and save yourself some effort -- after you run the repair, Nix will continue to work on 14.6.1, and it will still work immediately after the 15.0 update completes.

As for doing it offline, the release also includes the binaries for all our supported platforms, so you could download those and distribute them to the machines you want to run them on offline.

**Comment by bryanhonof** [comment]
Yeah, that makes sense. I just thought there was some command to update the already installed installer. But it makes sense that there's not. Thanks for explaining! 😁
