### ISSUE TITLE
All derivation evaluating nix commands hang

### ISSUE THREAD

**Issue by yamashitax** [DeterminateSystems/nix-installer#1166]
After using nix-installer and nix for a couple of days suddenly all nix commands hang indefinitely. Things like nix --version and such work without issue, however, commands like `nix shell nixpkgs#htop` will hang indefinitely.

Running macOS 14.6.1 (23G93) M3 Pro

Reinstalling my Mac and nix fixes the issue for a couple of days before reappearing.

Have not had this issue when installing nix manually and nix-darwin.

```
$ nix shell nixpkgs#htop -vvvvv                                                                                                  
evaluating file '<nix/derivation-internal.nix>'
evaluating derivation 'flake:nixpkgs#htop'...
using cache entry 'file:{"name":"flake-registry.json","store":"/nix/store","url":"https://channels.nixos.org/flake-registry.json"}' -> '{"etag":"W/\"000191f1e8b067fb44be0f6e2f655c952721a897d4e8c9b38207be8864cc3b51\"","storePath":"5bs7lbd1fk22w7bzdd8d6fvysnyzgw35-flake-registry.json","url":"https://channels.nixos.org/flake-registry.json"}'
```

```
$ rm -rf ~/.cache/nix
$ nix shell nixpkgs#php -vvvvv
evaluating file '<nix/derivation-internal.nix>'
evaluating derivation 'flake:nixpkgs#php'...
did not find cache entry for 'file:{"name":"flake-registry.json","store":"/nix/store","url":"https://channels.nixos.org/flake-registry.json"}'
downloading 'https://channels.nixos.org/flake-registry.json'...
download thread waiting for 10000 ms
starting download of https://channels.nixos.org/flake-registry.json
curl: Couldn't find host channels.nixos.org in the /nix/var/determinate/netrc file; using defaults
download thread waiting for 100 ms
download thread waiting for 100 ms
download thread waiting for 100 ms
download thread waiting for 100 ms
download thread waiting for 100 ms
download thread waiting for 100 ms
curl:   Trying 151.101.86.217:443...
download thread waiting for 100 ms
curl: Connected to channels.nixos.org (151.101.86.217) port 443
curl: ALPN: curl offers h2,http/1.1
curl: TLSv1.3 (OUT), TLS handshake, Client hello (1):
curl:  CAfile: /etc/ssl/certs/ca-certificates.crt
curl:  CApath: none
download thread waiting for 100 ms
curl: TLSv1.3 (IN), TLS handshake, Server hello (2):
curl: TLSv1.2 (IN), TLS handshake, Certificate (11):
curl: TLSv1.2 (IN), TLS handshake, Server key exchange (12):
curl: TLSv1.2 (IN), TLS handshake, Server finished (14):
curl: TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
curl: TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
curl: TLSv1.2 (OUT), TLS handshake, Finished (20):
download thread waiting for 100 ms
curl: TLSv1.2 (IN), TLS handshake, Finished (20):
curl: SSL connection using TLSv1.2 / ECDHE-RSA-CHACHA20-POLY1305
curl: ALPN: server accepted h2
curl: Server certificate:
curl:  subject: CN=channels.nixos.org
curl:  start date: Dec  9 19:50:10 2023 GMT
curl:  expire date: Jan  9 19:50:09 2025 GMT
curl:  subjectAltName: host "channels.nixos.org" matched cert's "channels.nixos.org"
curl:  issuer: C=BE; O=GlobalSign nv-sa; CN=GlobalSign Atlas R3 DV TLS CA 2023 Q4
curl:  SSL certificate verify ok.
curl: using HTTP/2
curl: [HTTP/2] [1] OPENED stream for https://channels.nixos.org/flake-registry.json
curl: [HTTP/2] [1] [:method: GET]
curl: [HTTP/2] [1] [:scheme: https]
curl: [HTTP/2] [1] [:authority: channels.nixos.org]
curl: [HTTP/2] [1] [:path: /flake-registry.json]
curl: [HTTP/2] [1] [user-agent: curl/8.4.0 Nix/2.23.3]
curl: [HTTP/2] [1] [accept: */*]
curl: [HTTP/2] [1] [accept-encoding: zstd, br, gzip, deflate, bzip2, xz]
download thread waiting for 100 ms
download thread waiting for 100 ms
download thread waiting for 100 ms
got header for 'https://channels.nixos.org/flake-registry.json': HTTP/2 200
got header for 'https://channels.nixos.org/flake-registry.json': cache-control: max-age=300
got header for 'https://channels.nixos.org/flake-registry.json': content-security-policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
got header for 'https://channels.nixos.org/flake-registry.json': content-type: text/plain; charset=utf-8
got header for 'https://channels.nixos.org/flake-registry.json': etag: W/"000191f1e8b067fb44be0f6e2f655c952721a897d4e8c9b38207be8864cc3b51"
got header for 'https://channels.nixos.org/flake-registry.json': strict-transport-security: max-age=31536000
got header for 'https://channels.nixos.org/flake-registry.json': x-content-type-options: nosniff
got header for 'https://channels.nixos.org/flake-registry.json': x-frame-options: deny
got header for 'https://channels.nixos.org/flake-registry.json': x-xss-protection: 1; mode=block
got header for 'https://channels.nixos.org/flake-registry.json': x-github-request-id: D08F:35CB7F:38D5DF:3BDC80:66DFB001
got header for 'https://channels.nixos.org/flake-registry.json': content-encoding: gzip
got header for 'https://channels.nixos.org/flake-registry.json': via: 1.1 varnish, 1.1 varnish
got header for 'https://channels.nixos.org/flake-registry.json': x-timer: S1725935618.700681,VS0,VE254
got header for 'https://channels.nixos.org/flake-registry.json': cross-origin-resource-policy: cross-origin
got header for 'https://channels.nixos.org/flake-registry.json': x-fastly-request-id: 894cfc471ee6f9d1ed14c3332c414446d289a066
got header for 'https://channels.nixos.org/flake-registry.json': expires: Tue, 10 Sep 2024 02:38:37 GMT
got header for 'https://channels.nixos.org/flake-registry.json': source-age: 0
got header for 'https://channels.nixos.org/flake-registry.json': access-control-allow-origin: *
got header for 'https://channels.nixos.org/flake-registry.json': accept-ranges: bytes
got header for 'https://channels.nixos.org/flake-registry.json': age: 0
got header for 'https://channels.nixos.org/flake-registry.json': date: Mon, 16 Sep 2024 06:54:53 GMT
got header for 'https://channels.nixos.org/flake-registry.json': x-served-by: cache-bma1679-BMA, cache-bma1665-BMA
got header for 'https://channels.nixos.org/flake-registry.json': x-cache: MISS, HIT
got header for 'https://channels.nixos.org/flake-registry.json': x-cache-hits: 0, 0
got header for 'https://channels.nixos.org/flake-registry.json': vary: Authorization,Accept-Encoding,Origin
got header for 'https://channels.nixos.org/flake-registry.json': content-length: 668
got header for 'https://channels.nixos.org/flake-registry.json': 
curl: Connection #0 to host channels.nixos.org left intact
finished download of 'https://channels.nixos.org/flake-registry.json'; curl status = 0, HTTP status = 200, body = 668 bytes
download thread waiting for 10000 ms
download thread waiting for 10000 ms
download thread waiting for 10000 ms
 […]
```

**Comment by cole-h** [comment]
Sorry for the delay -- is this still happening? What version(s) of Nix are you noticing this happen on?

**Comment by yamashitax** [comment]
@cole-h 

hiya! Since upgrading to the newest macOS this does not happen anymore.

**Comment by cole-h** [comment]
I'm glad to hear that! For now, I'm going to close this, but if you run into it again, feel free to reopen!

**Comment by grahamc** [comment]
Hey if you’re in determinate nix 3.6.5, can you upgrade to 3.6.6? We saw a regression there that should be fixed now. 

On Wed, Jun 18, 2025, at 2:41 AM, Yacine Hmito wrote:
> *yacinehmito* left a comment (DeterminateSystems/nix-installer#1166) <https://github.com/DeterminateSystems/nix-installer/issues/1166#issuecomment-2982859490>
> I am having the exact same issue. This is quite blocking.
> 
> Running macOS 15.5 with an M1 Pro.
> 
> Output of `nix shell nixpkgs#htop -vvvvv`:
> 
> `evaluating file '<nix/derivation-internal.nix>'
> evaluating derivation 'flake:nixpkgs#htop'...
> reading registry '/Users/yacinehmito/.config/nix/registry.json'
> reading registry '/etc/nix/registry.json'
> using cache entry 'file:{"name":"flake-registry.json","store":"/nix/store","url":"https://channels.nixos.org/flake-registry.json"}' -> '{"etag":"W/\"f284424ae1a4369a3f591f28915f7e43176ccc52bdf7117ff49868055d6c522b\"","storePath":"pc6y12ccrlvmgfbp0rs34cbj8mbsyyvk-flake-registry.json","url":"https://channels.nixos.org/flake-registry.json"}'
`
> And then it just hangs indefinitely.
> 
> Output of `nix shell nixpkgs#htop -vvvvv` after running `rm -rf ~/.cache/nix`:
> 
> `evaluating file '<nix/derivation-internal.nix>'
> evaluating derivation 'flake:nixpkgs#htop'...
> reading registry '/Users/yacinehmito/.config/nix/registry.json'
> reading registry '/etc/nix/registry.json'
> did not find cache entry for 'file:{"name":"flake-registry.json","store":"/nix/store","url":"https://channels.nixos.org/flake-registry.json"}'
> downloading 'https://channels.nixos.org/flake-registry.json'...
> download thread waiting for 10000 ms
> starting download of https://channels.nixos.org/flake-registry.json
> curl: Couldn't find host channels.nixos.org in the /nix/var/determinate/netrc file; using defaults
> download thread waiting for 100 ms
> download thread waiting for 100 ms
> download thread waiting for 100 ms
> download thread waiting for 100 ms
> download thread waiting for 100 ms
> curl: Host channels.nixos.org:443 was resolved.
> curl: IPv6: 2a04:4e42:1d::729
> curl: IPv4: 151.101.122.217
> curl:   Trying [2a04:4e42:1d::729]:443...
> cloexec set for fd 9
> download thread waiting for 100 ms
> curl: ALPN: curl offers h2,http/1.1
> curl: TLSv1.3 (OUT), TLS handshake, Client hello (1):
> curl:  CAfile: /etc/nix/macos-keychain.crt
> curl:  CApath: none
> download thread waiting for 100 ms
> curl: TLSv1.3 (IN), TLS handshake, Server hello (2):
> curl: TLSv1.2 (IN), TLS handshake, Certificate (11):
> curl: TLSv1.2 (IN), TLS handshake, Server key exchange (12):
> curl: TLSv1.2 (IN), TLS handshake, Server finished (14):
> curl: TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
> curl: TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
> curl: TLSv1.2 (OUT), TLS handshake, Finished (20):
> download thread waiting for 100 ms
> curl: TLSv1.2 (IN), TLS handshake, Finished (20):
> curl: SSL connection using TLSv1.2 / ECDHE-RSA-CHACHA20-POLY1305 / x25519 / RSASSA-PSS
> curl: ALPN: server accepted h2
> curl: Server certificate:
> curl:  subject: CN=channels.nixos.org
> curl:  start date: Oct 11 19:55:57 2024 GMT
> curl:  expire date: Nov 12 19:55:56 2025 GMT
> curl:  subjectAltName: host "channels.nixos.org" matched cert's "channels.nixos.org"
> curl:  issuer: C=BE; O=GlobalSign nv-sa; CN=GlobalSign Atlas R3 DV TLS CA 2024 Q4
> curl:  SSL certificate verify ok.
> curl:   Certificate level 0: Public key type RSA (2048/112 Bits/secBits), signed using sha256WithRSAEncryption
> curl:   Certificate level 1: Public key type RSA (2048/112 Bits/secBits), signed using sha256WithRSAEncryption
> curl:   Certificate level 2: Public key type RSA (2048/112 Bits/secBits), signed using sha256WithRSAEncryption
> curl: Connected to channels.nixos.org (2a04:4e42:1d::729) port 443
> curl: using HTTP/2
> curl: [HTTP/2] [1] OPENED stream for https://channels.nixos.org/flake-registry.json
> curl: [HTTP/2] [1] [:method: GET]
> curl: [HTTP/2] [1] [:scheme: https]
> curl: [HTTP/2] [1] [:authority: channels.nixos.org]
> curl: [HTTP/2] [1] [:path: /flake-registry.json]
> curl: [HTTP/2] [1] [user-agent: curl/8.12.1 Nix/2.29.0 DeterminateNix/3.6.5]
> curl: [HTTP/2] [1] [accept: */*]
> curl: [HTTP/2] [1] [accept-encoding: zstd, br, gzip, deflate, bzip2, xz]
> curl: Request completely sent off
> download thread waiting for 100 ms
> download thread waiting for 100 ms
> download thread waiting for 100 ms
> got header for 'https://channels.nixos.org/flake-registry.json': HTTP/2 200
> got header for 'https://channels.nixos.org/flake-registry.json': cache-control: max-age=300
> got header for 'https://channels.nixos.org/flake-registry.json': content-security-policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
> got header for 'https://channels.nixos.org/flake-registry.json': content-type: text/plain; charset=utf-8
> got header for 'https://channels.nixos.org/flake-registry.json': etag: W/"f284424ae1a4369a3f591f28915f7e43176ccc52bdf7117ff49868055d6c522b"
> got header for 'https://channels.nixos.org/flake-registry.json': strict-transport-security: max-age=31536000
> got header for 'https://channels.nixos.org/flake-registry.json': x-content-type-options: nosniff
> got header for 'https://channels.nixos.org/flake-registry.json': x-frame-options: deny
> got header for 'https://channels.nixos.org/flake-registry.json': x-xss-protection: 1; mode=block
> got header for 'https://channels.nixos.org/flake-registry.json': x-github-request-id: 5DF8:35C235:64B476:6E4E15:6834420C
> got header for 'https://channels.nixos.org/flake-registry.json': content-encoding: gzip
> got header for 'https://channels.nixos.org/flake-registry.json': via: 1.1 varnish, 1.1 varnish
> got header for 'https://channels.nixos.org/flake-registry.json': x-timer: S1748309315.744264,VS0,VE156
> got header for 'https://channels.nixos.org/flake-registry.json': cross-origin-resource-policy: cross-origin
> got header for 'https://channels.nixos.org/flake-registry.json': x-fastly-request-id: 89a0b55b07a4e01b7b2c99065219753441cfc2d3
> got header for 'https://channels.nixos.org/flake-registry.json': expires: Tue, 27 May 2025 01:33:34 GMT
> got header for 'https://channels.nixos.org/flake-registry.json': source-age: 0
> got header for 'https://channels.nixos.org/flake-registry.json': access-control-allow-origin: *
> got header for 'https://channels.nixos.org/flake-registry.json': accept-ranges: bytes
> got header for 'https://channels.nixos.org/flake-registry.json': age: 0
> got header for 'https://channels.nixos.org/flake-registry.json': date: Wed, 18 Jun 2025 06:27:45 GMT
> got header for 'https://channels.nixos.org/flake-registry.json': x-served-by: cache-par-lfpg1960031-PAR, cache-par-lfpb1150046-PAR
> got header for 'https://channels.nixos.org/flake-registry.json': x-cache: HIT, HIT
> got header for 'https://channels.nixos.org/flake-registry.json': x-cache-hits: 0, 0
> got header for 'https://channels.nixos.org/flake-registry.json': vary: Authorization,Accept-Encoding,Origin
> got header for 'https://channels.nixos.org/flake-registry.json': content-length: 696
> got header for 'https://channels.nixos.org/flake-registry.json':
> curl: Connection #0 to host channels.nixos.org left intact
> finished download of 'https://channels.nixos.org/flake-registry.json'; curl status = 0, HTTP status = 200, body = 696 bytes, duration = 0.18 s
> download thread waiting for 10000 ms
> download thread waiting for 10000 ms
> download thread waiting for 10000 ms
> download thread waiting for 10000 ms
> download thread waiting for 10000 ms
> download thread waiting for 10000 ms
> download thread waiting for 10000 ms
> download thread waiting for 10000 ms
> download thread waiting for 10000 ms
> download thread waiting for 10000 ms
`

**Comment by yacinehmito** [comment]
Works with 3.6.6, but I uninstalled Nix and reinstalled. I am not sure it was 100% necessary, but I did and it worked.
