### ISSUE TITLE
Boot-out failed: 5: Input/output error on systems.determinate.nix-installer.nix-hook

### ISSUE THREAD

**Issue by AlexMouton** [DeterminateSystems/nix-installer#1167]
## Error

Me again.
I seem to be able to corrupt my nix installs pretty regularly now, after networking seems to die.
This one seems unrecoverable.  Install fails like this, and revert also fails.  repair succeeds quietly with no information.

Thanks
A

```
Error: 
   0: Install failure
   1: Error executing action
   2: Action `create_nix_hook_service` errored
   3: Failed to execute command with status 5 `"launchctl" "bootout" "system" "/Library/LaunchDaemons/systems.determinate.nix-installer.nix-hook.plist"`, stdout: 
      stderr: Boot-out failed: 5: Input/output error


```

## Metadata
|key|value|
|--|--|
|**version**|0.26.0|
|**os**|macos|
|**arch**|aarch64|

**Comment by cole-h** [comment]
When you say "revert also fails", what exactly do you mean by that? Is there any output you can share?

Next time you run the installer, could you pass `-vvv` to get trace logging and if it fails, upload the logs to a gist or something that I can peek at?

Also, if it does fail, before you revert, could you run `launchctl print system/systems.determinate.nix-installer.nix-hook` and `sudo launchctl bootout system /Library/LaunchDaemons/systems.determinate.nix-installer.nix-hook.plist` and show their output?

**Comment by AlexMouton** [comment]
Hi Cole.
Sorry for the interruption. I think my issue was that something was spamming out watchman processes and i hit my proc limit.   I updated brew and watchman and I think I'm back to normal.
