### ISSUE TITLE
nixbld group not found

### ISSUE THREAD

**Issue by joshbainbridge** [DeterminateSystems/nix-installer#1171]
After following the instructions at:
```
https://determinate.systems/posts/nix-support-for-macos-sequoia/
```

and running:
```
curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix/tag/v0.26.0 | sh -s -- repair sequoia --move-existing-users
```

I'm getting:

## Error
```
Error: 
   0: Failed to execute command with status 56 `"/usr/bin/dscl" "-plist" "." "-read" "/Groups/nixbld"`, stdout: 
      stderr: <dscl_cmd> DS Error: -14136 (eDSRecordNotFound)


```

## Metadata
|key|value|
|--|--|
|**version**|0.26.0|
|**os**|macos|
|**arch**|aarch64|

**Comment by cole-h** [comment]
Did you previous install Nix with our installer? If so, what version? Would you mind posting your receipt (`/nix/receipt.json`) here?

If you have not installed Nix yet, you can safely do so with any version of our installer v0.23.0 and later, as that uses the Sequoia compatible UID range by default.

**Comment by joshbainbridge** [comment]
I did use a previous version of nix-installer for the prior install. However, I've found that the root cause of this was an update to macOS that caused access to the Nix partition to no longer be possible.

Manually deleting the partition and then re-running the latest nix-installer resolved the issue for me. Thanks for the suggestions!
