### ISSUE TITLE
Group `nixbld` existed but had a different gid (30000) than planned (350)

### ISSUE THREAD

**Issue by markvdp** [DeterminateSystems/nix-installer#1177]
## Error
```
Error: 
   0: Planner error
   1: Error executing action
   2: Action `create_group` errored
   3: Group `nixbld` existed but had a different gid (30000) than planned (350)
```

## Metadata
|key|value|
|--|--|
|**version**|0.26.0|
|**os**|macos|
|**arch**|aarch64|

**Comment by cole-h** [comment]
Are you just trying to get Nix working with macOS Sequoia? If so, you don't need to (re)install. We put up a blog post with guidance on this: https://determinate.systems/posts/nix-support-for-macos-sequoia/ (similar information can be found in the https://github.com/DeterminateSystems/nix-installer/releases/tag/v0.26.0 release notes).

**Comment by markvdp** [comment]
Lost my password for the "nix store". Eventually I did removed the nix store APFS disk with disk utility and a manual uninstall of everything else.  https://nix.dev/manual/nix/2.18/installation/uninstall


And a re-install without encryption this time (option macos)
`
curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix | sh -s -- install macos
`

Fix a deadlink
`
sudo ln -s /nix/var/nix/profiles/default/etc/ssl/certs/ca-bundle.crt /etc/ssl/certs/ca-certificates.crt
`

This ticket can be closed

**Comment by cole-h** [comment]
Glad you got it sorted! Thanks for saying how you did so, as well!
