### ISSUE TITLE
The keychain has an existing password for a non-existing "Nix Store" volume on disk `disk3`

### ISSUE THREAD

**Issue by dminca** [DeterminateSystems/nix-installer#1183]
## Error
```
Error: 
   0: Planner error
   1: Error executing action
   2: Action `encrypt_apfs_volume` errored
   3: The keychain has an existing password for a non-existing "Nix Store" volume on disk `disk3`, consider removing the password with `sudo security delete-generic-password  -a "Nix Store" -s "Nix Store" -l "disk3 encryption password" -D "Encrypted volume password"`. Note that it's possible to have several passwords stored, so you may need to run this command several times until receiving the message `The specified item could not be found in the keychain.`
```

## Metadata
|key|value|
|--|--|
|**version**|0.26.0|
|**os**|macos|
|**arch**|aarch64|

**Comment by cole-h** [comment]
If you do the suggestions in the error message, does that allow you to get further in the install process?

You may also want to follow upstream's uninstallation procedure before trying again: https://nix.dev/manual/nix/latest/installation/uninstall.html#macos

**Comment by dminca** [comment]
hi @cole-h , sorry for the late reply.

The suggested command actually fixed the issue, thank you!
