### ISSUE TITLE
User `_nixbld1` existed but had a different gid (30000) than planned (350)

### ISSUE THREAD

**Issue by diederikm** [DeterminateSystems/nix-installer#1194]
Upgraded apple to Sequoia, made a mess of not knowing how i did the first nix install, used detsystems repair script and then run the installer, got errors with suggestions how to fix it, ended here.

## Error
```
Error: 
   0: Planner error
   1: Error executing action
   2: Action `create_users_and_group` errored
   3: Action `create_user` errored
   4: User `_nixbld1` existed but had a different gid (30000) than planned (350)
```

## Metadata
|key|value|
|--|--|
|**version**|0.26.2|
|**os**|macos|
|**arch**|aarch64|

**Comment by diederikm** [comment]
Got it all working reading other peoples solutions in the issue list, thanks guys!

https://nix.dev/manual/nix/2.24/installation/uninstall.html#macos

**Comment by cole-h** [comment]
For what it's worth, you should have been OK after you ran the repair script -- installing Nix again was unnecessary. But glad you got it working!
