### ISSUE TITLE
<autogenerated-issue>

### ISSUE THREAD

**Issue by polonoid** [DeterminateSystems/nix-installer#1206]
## Error
```
Error: 
   0: Install failure
   1: Error executing action
   2: Action `create_nix_hook_service` errored
   3: Failed to execute command with status 5 `"launchctl" "bootout" "system" "/Library/LaunchDaemons/systems.determinate.nix-installer.nix-hook.plist"`, stdout: 
      stderr: Boot-out failed: 5: Input/output error


```

## Metadata
|key|value|
|--|--|
|**version**|0.26.3|
|**os**|macos|
|**arch**|aarch64|

**Comment by cole-h** [comment]
This looks similar to https://github.com/DeterminateSystems/nix-installer/issues/1187 -- would you please try my suggestions in https://github.com/DeterminateSystems/nix-installer/issues/1187#issuecomment-2368473915 and report back in that issue? Thanks!
