### ISSUE TITLE
SELinux support

### ISSUE THREAD

**Issue by Hoverbear** [DeterminateSystems/nix-installer#124]
We should detect SELinux in our `linux-multi` planner and add steps similar to those found in https://github.com/nix-community/nix-installers/tree/master/selinux.

**Comment by COLAMAroro** [comment]
A Fedora user (@dnkmmr69420) managed to make Nix works with SELinux, both on Fedora and Fedora Silverblue, without a complete deactivation of SELinux

https://github.com/dnkmmr69420/nix-with-selinux

**Comment by Hoverbear** [comment]
Oh my goodness that's so cool!
