### ISSUE TITLE
UID 301 already exists

### ISSUE THREAD

**Issue by nocksock** [DeterminateSystems/nix-installer#1243]
## Error
```
Error: 
   0: Install failure
   1: Error executing action
   2: Action `create_users_and_group` errored
   3: Action `create_user` errored
   4: Failed to execute command with status 55 `"/usr/bin/dscl" "." "-create" "/Users/_nixbld1" "UniqueID" "301"`, stdout: 
      stderr: <main> attribute status: eDSRecordAlreadyExists
      <dscl_cmd> DS Error: -14135 (eDSRecordAlreadyExists)


```

## Metadata
|key|value|
|--|--|
|**version**|0.14.0|
|**os**|macos|
|**arch**|aarch64|

**Comment by cole-h** [comment]
0.14.0 is quite old (over a year at this point!) and does not have the defaults required to support an install on macOS Sequoia (which I assume you're running, as this error is due to Sequoia most of the time -- if not, please correct me!). If you try a newer installer version (any version after 0.23.0 should work, but why not go for the latest using the invocation in the README :), that should get you going.

**Comment by nocksock** [comment]
Huh. I was using `curl -L https://raw.githubusercontent.com/NixOS/experimental-nix-installer/main/nix-installer.sh | sh -s install` - which I took from [devenv's getting started](https://devenv.sh/getting-started/) page. I'll try the install instructions from the nix page.

**Comment by nocksock** [comment]
I'm getting this error - which seems to be missing the actual UID in the output:

```txt
It seems the build user _nixbld1 already exists, but with the UID
with the UID ''. This script can't really handle that right
now, so I'm going to give up.

If you already created the users and you know they start from
 and go up from there, you can edit this script and change
NIX_FIRST_BUILD_UID near the top of the file to  and try
again.

We'd love to help if you need it.

You can open an issue at
https://github.com/NixOS/nix/issues/new?labels=installer&template=installer.md

Or get in touch with the community: https://nixos.org/community
```

Given the initial error, I'm assuming it's 301?

**Comment by cole-h** [comment]
You may need to follow the upstream uninstall instructions first: https://nix.dev/manual/nix/latest/installation/uninstall.html#macos

**Comment by nocksock** [comment]
> You may need to follow the upstream uninstall instructions first: https://nix.dev/manual/nix/latest/installation/uninstall.html#macos

Uninstalling fully as described on that URL and then running it again worked without issues! 
Thanks for the help!
