### ISSUE TITLE
Installing over existing script-based install fails due to different nixbld GIDs

### ISSUE THREAD

**Issue by isaacvando** [DeterminateSystems/nix-installer#1247]
Below is the autogenerated message from the installer. I have had Nix installed in the past using the standard installer. When I ran the installer first it ran into an error because I already had a Nix Store volume. I removed it using the instructions from the installer (had to run two other commands before removing it).

## Error
```
Error: 
   0: Planner error
   1: Error executing action
   2: Action `create_group` errored
   3: Group `nixbld` existed but had a different gid (30000) than planned (350)
```

## Metadata
|key|value|
|--|--|
|**version**|0.27.0|
|**os**|macos|
|**arch**|aarch64|

**Comment by cole-h** [comment]
You may want to follow the uninstallation instructions for the upstream scripts before trying again: https://nix.dev/manual/nix/latest/installation/uninstall.html#macos

**Comment by isaacvando** [comment]
I was able to install successfully after following those instructions. Thank you!
