### ISSUE TITLE
Can't uninstall/reinstall after accidentally running v26 sequoia repair on v27

### ISSUE THREAD

**Issue by ajlive** [DeterminateSystems/nix-installer#1248]
## Error
```
Error: 
   0: [31mUnable to parse plan, this plan was created by `nix-installer` version `0.27.0`, this is `nix-installer` version `0.27.0`
      To uninstall, either run  `/nix/nix-installer uninstall` or `curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix/tag/v0.27.0 | sh -s -- uninstall`[39m
   1: missing field `use_ec2_instance_store` at line 1282 column 3
```

## Metadata
|key|value|
|--|--|
|**version**|0.27.0|
|**os**|macos|
|**arch**|aarch64|

This all happened because I was trying to run the v27 installer in a `justfile`, and every time the task would crap out after successful installation with the error `sh: Nix: command not found`, preventing further steps from executing. I tried various ways to suppress the error to no avail. This also happens when the installer is run in a subshell in a script.

Unfortunately, I found the post https://determinate.systems/posts/nix-support-for-macos-sequoia/, but I didn't notice that it was about v26 and not v27. I ran:

```
$ curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix/tag/v0.26.0 | sh -s -- repair sequoia --move-existing-users
info: downloading installer https://install.determinate.systems/nix/tag/v0.26.0/nix-installer-aarch64-darwin
 INFO nix-installer v0.26.0
`nix-installer` needs to run as `root`, attempting to escalate now via `sudo`...
 INFO nix-installer v0.26.0
Will move the _nixbld users to the Sequoia-compatible 350+ UID range and WILL update the receipt

Proceed? ([Y]es/[n]o): Y
 INFO Backed up pre-repair receipt to /nix/receipt.pre-repair.1729886472512.json
 INFO Wrote updated receipt
 INFO Finished repairing successfully!
```

This didn't change anything when it came to installing, but then trying to reinstall caused the above error:

```
$ curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix/tag/v0.27.0 | sh -s -- uninstall
info: downloading installer https://install.determinate.systems/nix/tag/v0.27.0/nix-installer-aarch64-darwin
 INFO nix-installer v0.27.0
`nix-installer` needs to run as `root`, attempting to escalate now via `sudo`...
 INFO nix-installer v0.27.0
Error:
   0: Unable to parse plan, this plan was created by `nix-installer` version `0.27.0`, this is `nix-installer` version `0.27.0`
      To uninstall, either run  `/nix/nix-installer uninstall` or `curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix/tag/v0.27.0 | sh -s -- uninstall`
   1: missing field `use_ec2_instance_store` at line 1282 column 3

Location:
   src/cli/subcommand/uninstall.rs:126

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
```

This also happens with `/nix/nix-installer uninstall`. Unfortunately, changing the installer version in the path to 26 gives a different error:

```
$ curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix/tag/v0.26.0 | sh -s -- uninstall
info: downloading installer https://install.determinate.systems/nix/tag/v0.26.0/nix-installer-aarch64-darwin
 INFO nix-installer v0.26.0
`nix-installer` needs to run as `root`, attempting to escalate now via `sudo`...
 INFO nix-installer v0.26.0
`nix-installer` version `0.26.0` is not compatible with this plan's version `0.27.0`

Found existing plan in `/nix/receipt.json` which was created by a version incompatible `nix-installer`.


                    To uninstall, either run `/nix/nix-installer uninstall` or `curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix/tag/v$0.27.0 | sh -s -- uninstall`
```

Which makes sense, since I only ever used v26 to run the repair command, never the install or uninstall commands. There are two receipts in `/nix/`, both for v27:

```
$ ls -1 /nix/
nix-installer*
receipt.json
receipt.pre-repair.1729886472512.json
store/
var/

i> ~/nix
$ head /nix/receipt.json
{
  "version": "0.27.0",
  "actions": [
    {
      "action": {
        "action_name": "create_apfs_volume",
        "disk": "disk3",
        "name": "Nix Store",
        "case_sensitive": false,
        "encrypt": true,

i> ~/nix
$ head /nix/receipt.pre-repair.1729886472512.json
{
  "version": "0.27.0",
  "actions": [
    {
      "action": {
        "action_name": "create_apfs_volume",
        "disk": "disk3",
        "name": "Nix Store",
        "case_sensitive": false,
        "encrypt": true,
```

While I hope to eventually get the installer not to cause my just task to crap out, my first order of business now is to clean up my mess. Any help to get uninstall working would be greatly appreciated!

**Comment by ajlive** [comment]
Ah, great. I was able to solve my own problem with a little bit of guesswork and an adventurous spirit. I moved `receipt.json` out of `/nix/` and renamed `/nix/receipt.pre-repair.1729886472512.json` to `/nix/receipt.json`, then ran `/nix/nix-installer uninstall` and nix uninstalled successfully! Now back to trying to figure out the justfile.

**Comment by cole-h** [comment]
Sorry this happened to you! I'll take a look into how that was possible...

In the meantime, you should be able to uninstall by pointing the appropriate uninstaller version to the `pre-repair` receipt. However, if everything is working just fine for the moment, you may be able to get away with moving the `pre-repair` receipt to `/nix/receipt.json` (so that uninstall will work in the future), and leaving it be.


If that `justfile` error is exactly what you see, then the problem may be: the binary is called `nix` (lowercase `n`), not `Nix` (capital `N`).

**Comment by cole-h** [comment]
(For any future users who end up here: the uninstaller accepts a file argument, so you could just run `/nix/nix-installer uninstall /nix/receipt.pre-repair.1729886472512.json` and it should work just fine)

**Comment by ajlive** [comment]
Thanks for that blazing fast reply! I'll make a separate issue for the justfile if I can't figure it out.

**Comment by ajlive** [comment]
Just popping back to say for posterity that it was not `nix-installer` causing the issue in the `justfile`, but some bizarre interaction between `just` and `gum` (https://github.com/charmbracelet/gum), which I'm using to confirm steps inside my just task, causing the task to fail the second time I execute `gum confirm`, but not the first. That just so happened to be right after installing nix...
