### ISSUE TITLE
Cannot install in an Ubuntu container

### ISSUE THREAD

**Issue by osalbahr** [DeterminateSystems/nix-installer#1251]
Is it possible to install `nix` in an `ubuntu` container?

Steps to reproduce:

1. `podman run -it ubuntu`
2. Add a user with `sudo` group
3. Run `curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix | sh -s -- install` in the user

## Error

```
Error: 
   0: Planner error
   1: Error executing action
   2: Action `create_upstream_init_service` errored
   3: Action `configure_init_service` errored
   4: Could not detect systemd; you may be able to get up and running without systemd with `nix-installer install linux --init none`.
      See https://github.com/DeterminateSystems/nix-installer#without-systemd-linux-only for documentation on usage and drawbacks.
```

## Metadata
|key|value|
|--|--|
|**version**|0.27.0|
|**os**|linux|
|**arch**|aarch64|

**Comment by cole-h** [comment]
If you do the suggestions in the error message, does that allow you to get further in the install process?

Otherwise, you may want to look at the container section in the README: https://github.com/DeterminateSystems/nix-installer?tab=readme-ov-file#in-a-container

**Comment by osalbahr** [comment]
@cole-h thx, I completely missed the suggestion!

Is there a reason the suggestion isn't applied by default?
