### ISSUE TITLE
Nix install fails on macos

### ISSUE THREAD

**Issue by jbojcic1** [DeterminateSystems/nix-installer#1259]
## Error
```
Error: 
   0: Install failure
   1: Error executing action
   2: Action `create_users_and_group` errored
   3: Action `create_user` errored
   4: Failed to execute command with status 55 `"/usr/bin/dscl" "." "-create" "/Users/_nixbld1" "UniqueID" "301"`, stdout: 
      stderr: <main> attribute status: eDSRecordAlreadyExists
      <dscl_cmd> DS Error: -14135 (eDSRecordAlreadyExists)


```

## Metadata
|key|value|
|--|--|
|**version**|0.14.0|
|**os**|macos|
|**arch**|aarch64|

**Comment by jbojcic1** [comment]
I did not have it installed. I tried installing using this command `curl -L https://raw.githubusercontent.com/NixOS/experimental-nix-installer/main/nix-installer.sh | sh -s install` (found it in devenv docs [here](https://devenv.sh/getting-started/).

When I did installation using `sh <(curl -L https://nixos.org/nix/install)` it worked fine.

**Comment by cole-h** [comment]
Ah, I see -- I misread the error, sorry about that. The issue is that you're likely on macOS Sequoia, and the experimental Nix installer (found at https://github.com/NixOS/experimental-nix-installer, which is a fork of this one) hasn't been updated to handle that yet.
