### ISSUE TITLE
Install issue

### ISSUE THREAD

**Issue by yleclercq-pass** [DeterminateSystems/nix-installer#1275]
## Description 
I install Nix via DeterminateSystems it work wells for a while. I had a problem so i tried to uninstall nix with : 
`/nix/nix-installer uninstall`

i tried to reinstall again and i had an error. So i rebooted my Mac and try to reinstall  : 
`curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix | sh -s -- install  --ssl-cert-file '/Library/Application Support'/*/*/data/*cacert.pem`

Again an error. So i tried to uninstall it manually following this documentation : 
https://nix.dev/manual/nix/2.18/installation/uninstall

I rebooted and again i tried to reinstall with the same command `curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix | sh -s -- install  --ssl-cert-file '/Library/Application Support'/*/*/data/*cacert.pem`

And finally i've got this error and i'm blocked : 

## Error
```
ERROR Error saving receipt: RecordingReceipt("/nix/receipt.tmp", Os { code: 30, kind: ReadOnlyFilesystem, message: "Read-only file system" })
Error: 
   0: Install failure
   1: Error executing action
   2: Action `create_nix_volume` errored
   3: Action `create_volume_service` errored
   4: Open path `/Library/LaunchDaemons/org.nixos.darwin-store.plist`
   5: No such file or directory (os error 2)
```

May i ask you some help for this please

## Metadata
|key|value|
|--|--|
|**version**|0.27.1|
|**os**|macos|
|**arch**|aarch64|

**Comment by cole-h** [comment]
That's weird... The only time this error should happen is when we're trying to open that, but we also tell Rust to create it if it doesn't exist... Does the `/Library/LaunchDaemons` directory exist? If not, can you create it? If it does, what are its contents? `ls -la /Library/LaunchDaemons`

**Comment by yleclercq-pass** [comment]
@cole-h Thank you for your response, this directory doesn't exist i can create it manually. Should i create manually and lunch install command ?

**Comment by cole-h** [comment]
For now, yes please! You will need to create it with root, but I'm not sure what other permissions it would need, if any. We should make the error here better (or create this directory if it doesn't exist but that bears more investigation to see if we can actually do that).

**Comment by yleclercq-pass** [comment]
Thank you for your help ! It worked ! I just created the directiory `/Library/LaunchDaemons` and the command for install worked fine.  You saved my day ! 
<img width="560" alt="Capture d’écran 2024-11-12 à 09 46 49" src="https://github.com/user-attachments/assets/929fec83-392c-4a14-9db1-bcff9711c6cd">
