### ISSUE TITLE
Boot-out failed: 5: Input/output error

### ISSUE THREAD

**Issue by rafaelfelix** [DeterminateSystems/nix-installer#1283]
## Error
```
Error: 
   0: Install failure
   1: Error executing action
   2: Action `create_nix_hook_service` errored
   3: Failed to execute command with status 5 `"launchctl" "bootout" "system" "/Library/LaunchDaemons/systems.determinate.nix-installer.nix-hook.plist"`, stdout: 
      stderr: Boot-out failed: 5: Input/output error


```

## Metadata
|key|value|
|--|--|
|**version**|0.27.1|
|**os**|macos|
|**arch**|aarch64|

**Comment by cole-h** [comment]
This should be fixed by https://github.com/DeterminateSystems/nix-installer/pull/1257, which has been released as a part of https://github.com/DeterminateSystems/nix-installer/releases/tag/v0.28.0.
