### ISSUE TITLE
Install failure on x86_64-apple-darwin GitHub Actions runner

### ISSUE THREAD

**Issue by lovesegfault** [DeterminateSystems/nix-installer#1300]
## Error
https://github.com/lovesegfault/vim-config/actions/runs/11883521510/job/33110402722?pr=157#logs
```
Error: 
   0: Install failure
   1: Error executing action
   2: Action `create_users_and_group` errored
   3: Action `create_user` errored
   4: Failed to execute command with status 140 `"/usr/bin/dscl" "." "-create" "/Users/_nixbld1" "UniqueID" "351"`, stdout: create: DS error: eNotYetImplemented

      stderr: <dscl_cmd> DS Error: -14988 (eNotYetImplemented)


```

## Metadata
|key|value|
|--|--|
|**version**|0.28.0|
|**os**|macos|
|**arch**|x86_64|

**Comment by cole-h** [comment]
Looks like ansible ran into the same bug: https://github.com/ansible/ansible/issues/73505

and they believe it's also a macOS bug. 

...if you try restarting the run, does that work? If so, maybe retrying a few times is the best we can do...

**Comment by lovesegfault** [comment]
> ...if you try restarting the run, does that work?

yup, a retry succeeded, and other jobs did not see the same issue.
