### ISSUE TITLE
Fedora Silverblue: `nix profile` installs, but don't work

### ISSUE THREAD

**Issue by Noriller** [DeterminateSystems/nix-installer#1328]
Fresh install of silverblue (fedora silverblue 41), installed following [instructions](https://github.com/DeterminateSystems/nix-installer?tab=readme-ov-file#install-nix), `nix profile install nixpkgs#hello` completes and listing will show the package, but it just isn't available to be used (`which hello` -> not found).

Context: some packages I want to install some packages "globally" for use with sudo among other things.

**Comment by cole-h** [comment]
Hm, it's weird that you can run nix commands (like `nix profile install`) just fine, but not have the package show up on your `PATH`... Just as a sanity check, if you manually run `. /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh`, does `which hello` work?

**Comment by Noriller** [comment]
Screw up from me... it wasn't actually hello but something that exposed a bin with some other name.

Thank you
