### ISSUE TITLE
Test "HPC contexts" or "LDAP contexts"

### ISSUE THREAD

**Issue by RaitoBezarius** [DeterminateSystems/nix-installer#139]
On machines with a lot of users due to LDAP running in a big org, it would be interesting to see if the nix installer behaves well, e.g. select the proper UIDs for the build users, etc.

Also, HPC contexts are more special case of LDAP contexts, so better keep them in mind I think.

I have seen a PR for adding sandboxed QEMU tests, I think it would be great to extend those with similar scenarios.

**Comment by Hoverbear** [comment]
I agree! Do you have any guidance on what these would look like (eg should we just run `createuser` 5000 times and then run the test?), or example images to test with?

**Comment by Hoverbear** [comment]
If you come up with anything please reopen the issue and let me know!
