### ISSUE TITLE
Confirm installation is successful

### ISSUE THREAD

**Issue by rapenne-s** [DeterminateSystems/nix-installer#143]
I just used `nix-installer` and the end of the output looks like

```
INFO Step: Create directory /nix
INFO Step: Provision Nix
INFO Step: Configure Nix
```

Now, I'm curious to know if it aborted or finished correctly, a simple message such as `INFO Nix is installed` or something like this would be nice.

**Comment by Hoverbear** [comment]
Oh, thanks for catching this! A refactor accidently moved the success message into some area where it is effectively unreachable.
