### ISSUE TITLE
Cleverness to merge `extra-conf` etc

### ISSUE THREAD

**Issue by Hoverbear** [DeterminateSystems/nix-installer#174]
We should safely handle when a user adds options which we also set.

**Comment by Hoverbear** [comment]
I almost wonder if it's worth trying to teach Nix to be configured with another format as well...

**Comment by cole-h** [comment]
I was able to hack up a library that roughly parses the Nix config as Nix itself does: https://github.com/DeterminateSystems/nix-config-parser (Nix's implementation here: https://github.com/NixOS/nix/blob/0079d2943702a7a7fbdd88c0f9a5ad677c334aa8/src/libutil/config.cc#L80-L138)

For the moment, it's little more than a re-implementation of the parser code from Nix that puts the settings into a `HashMap<String, String>`. Maybe we could make that more useful (maybe make `NixConfig` a proper struct with helper methods for various things), if that would help.
