### ISSUE TITLE
Support WSL2 (without Systemd)

### ISSUE THREAD

**Issue by beeb** [DeterminateSystems/nix-installer#211]
When trying to run the [install script](https://install.determinate.systems/nix) on WSL2 (Ubuntu 22.04) I get the following error:

```
Error:
   0: Planner error
   1: Error executing action
   2: No supported init system found

Location:
   /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/convert/mod.rs:726
```

**Comment by Hoverbear** [comment]
Hi! Yes! You need systemd enabled https://devblogs.microsoft.com/commandline/systemd-support-is-now-available-in-wsl/, though soon we will support without systemd in #188

**Comment by Hoverbear** [comment]
Agh ya it can be a bit finnicky! We should support your use case soon, so maybe check back next time you reinstall your WSL distro!
