### ISSUE TITLE
MacOS: Newly created zshenv doesn't have correct permissions

### ISSUE THREAD

**Issue by Netruk44** [DeterminateSystems/nix-installer#254]
I'm running through the [zero to nix guide](https://zero-to-nix.com/start/install) and had an issue during install step. After installation, no newly created Terminal windows knew what the `nix` command was (`zsh: command not found: nix`)

I tracked the issue down to the fact that the custom nix installer created a new zsh config file at `/etc/zshenv` (or `/private/etc/zshenv`) that zsh is supposed to read. But the file was created with just r/w permissions for the root user:

```bash
-rw-------  1 root  wheel  172 Feb 16 11:28 /private/etc/zshenv
```

If I `sudo chmod go+r /etc/zshenv` it fixes the issue, and I can run `nix` in a new Terminal window.

**Comment by Hoverbear** [comment]
Thanks for this report! 

It does look like we're not setting it right, here's the zsh files:

https://github.com/DeterminateSystems/nix-installer/blob/c150d603eac35fea0f68ca0de8672786a6b90a31/src/action/common/configure_shell_profile.rs#L69-L76

compared to the fish ones

https://github.com/DeterminateSystems/nix-installer/blob/c150d603eac35fea0f68ca0de8672786a6b90a31/src/action/common/configure_shell_profile.rs#L110-L119

I'm working on a fix.

**Comment by DimitryAndric** [comment]
It's similar for the file `/etc/bash.bashrc`:

```
% ls -ltr /etc/ | tail -6
-rw-r-xr-x   1 root  wheel       4 Feb 19 19:34:14 2023 synthetic.conf*
-rw-r--r--   1 root  wheel     135 Feb 19 19:34:16 2023 fstab
-rw-------   1 root  wheel     172 Feb 19 19:34:36 2023 zshenv
-rw-------   1 root  wheel     172 Feb 19 19:34:36 2023 bash.bashrc
-r--r--r--   1 root  wheel     437 Feb 19 19:34:36 2023 bashrc
drwxr-xr-x   3 root  wheel      96 Feb 19 19:34:36 2023 nix/
```

This is just after nix-install completed. You can see that it created zshenv, bash.bashrc, and updated the 'main' bashrc. The former two are mode 600, however.
