### ISSUE TITLE
Installation does not add paths to fish config

### ISSUE THREAD

**Issue by hussainweb** [DeterminateSystems/nix-installer#265]
I previously reported this at https://github.com/DeterminateSystems/zero-to-nix/issues/236 but I think this is the more appropriate place. I also think this might be related to #254 and I can't say if this has been fixed by #257. But I'm posting this anyway because I think the issue is different.

I think that the reason the path setting doesn't work is that fish expects to read config at `~/.config/fish`. These are the directories referred to in the code.

https://github.com/DeterminateSystems/nix-installer/blob/689cf84bbffeb00fbb426bc7f67559cf0a8e0f75/src/action/common/configure_shell_profile.rs#L18-L23

In my case, only the homebrew path exists and it does create the file there. But as I reported in my previous issue, it doesn't work. I had to manually add this to my `config.fish` file to get it to work.

```
test -e /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.fish ; and source /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.fish
```

I can't find any reference to where the fish-shell finds the config but the [documentation](https://fishshell.com/docs/current/tutorial.html#startup-where-s-bashrc) only mentions `~/.config/fish` paths. I am guessing a line can be added to the array above but since this is a user path, I am not sure how to refer to the user in Rust. In any case, I am guessing this binary runs as root and I don't know how it can find out the user it is supposed to refer to. I'm happy to create a PR if you can help me see how to refer to the user in the path strings. I'm guessing just `"~/.config/fish.."` won't work because the binary is probably running as root.

**Comment by hussainweb** [comment]
Update: I found out how [fish loads the configuration files](https://fishshell.com/docs/current/language.html#configuration). It also reads config from `$__fish_sysconf_dir/conf.d` and I can see that points to `/opt/homebrew/etc/fish/conf.d` on my machine. So, the path seems to be correct. However, I cannot access that directory with my user.

```bash
homebrew/etc/fish on  master
❯ cd conf.d/
cd: Permission denied: 'conf.d/'
```

This is what the directory looks like:
```
homebrew/etc/fish on  master
❯ l
drw-r--r--   - root admin 23 Feb 09:26 -I conf.d/
.rw-r--r-- 425 hw   admin  9 Jan 01:44 -I config.fish
```

Now, I am not sure if this directory always existed or if `nix-installer` created it. But if it's not readable by my user, I'm pretty sure fish can't access it. Considering the date, I am going to assume that the `nix-installer` created it as seen by this code.
https://github.com/DeterminateSystems/nix-installer/blob/689cf84bbffeb00fbb426bc7f67559cf0a8e0f75/src/action/common/configure_shell_profile.rs#L115-L119C14

So, apart from the fix in #257, I am thinking that the permission must be updated in line 117 above as well. If this sounds correct, I am happy to create a PR for this.

**Comment by Hoverbear** [comment]
Thanks for the report! @cole-h and I were actually poking at similar! I believe #267 may resolve this!  I appreciate you offering to make a PR, please feel welcome to if you find anything more!

**Comment by Hoverbear** [comment]
I set that PR to upload to S3 so once the "Release PR" job passes (it should take a few minutes) you can test it with:

```bash
/nix/nix-installer uninstall
```

Then

```
curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix/pr/267 | sh -s -- install
```

**Comment by hussainweb** [comment]
@Hoverbear, thanks for the instructions. I just tried them out (twice) and it works properly now. I also see that PR is merged and so this can be closed.

**Comment by Hoverbear** [comment]
Thanks for testing! A release is going out soon. :)
