### ISSUE TITLE
Include failed step(s) in errors and diagnostics

### ISSUE THREAD

**Issue by cole-h** [DeterminateSystems/nix-installer#268]
> I wonder, could we easily include which step failed as well...? Knowing it was a permissions error would be more useful if it also said "CreateFile".

_Originally posted by @cole-h in https://github.com/DeterminateSystems/nix-installer/pull/264#discussion_r1116102317_

**Comment by Hoverbear** [comment]
Closed with https://github.com/DeterminateSystems/nix-installer/pull/296
