### ISSUE TITLE
Cannot install nor rollback in Docker Alpine container

### ISSUE THREAD

**Issue by zarelit** [DeterminateSystems/nix-installer#282]
To reproduce:
`docker run --rm -it alpine`
```
# apk add curl
# curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix | sh -s -- install
```

The installer correctly proposes a plan with init: "None" but proceeding leads to this output

```
Proceed? ([Y]es/[n]o/[e]xplain): Y
 INFO Step: Create directory `/nix`
 INFO Step: Provision Nix
ERROR 
   0: Install failure
   1: Error executing action
   2: Failed to execute command
   3: No such file or directory (os error 2)

Location:
   /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/convert/mod.rs:726

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
```

downloadin the installer and running it with RUST_BACKTRACE=full leads to no backtrace at all

**Comment by cole-h** [comment]
Thanks for the report!

The issue is that, to add / remove users and groups, we naively used the `useradd` binary, but alpine doesn't have that available (by default?). I've opened https://github.com/DeterminateSystems/nix-installer/issues/284 to track a feature that would fix this (by adding supporting both `useradd` and `adduser`).

**Comment by cole-h** [comment]
I've opened https://github.com/DeterminateSystems/nix-installer/pull/319 to hopefully fix this, please give it a shot! You should be able to do so with the following:

```shell
curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix/pr/319 | sh -s -- install
```

**Comment by zarelit** [comment]
@cole-h `install` works like a charm, thank you! 

I also like the improvements on the error output!

There's a issue now while uninstalling, probably for the same reason, here is the error trace:

```

**Comment by cole-h** [comment]
Ah, brainfart. I knew that would be a problem and didn't handle it for whatever reason lol. I'll get that fixed up ASAP. Thanks for your help!

**Comment by cole-h** [comment]
OK, I've merged https://github.com/DeterminateSystems/nix-installer/pull/319 now that I actually tested both installation and uninstallation this time. If there are any further issues, please let me know and I'll try to get to them ASAP!

```
curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix/rev/caebcd33e6fec12364b96e60da773604306b2d2c | sh -s -- install
```
or

```
curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix/pr/319 | sh -s -- install
```

should work.

**Comment by zarelit** [comment]
@cole-h thank you so much for the fix!
