### ISSUE TITLE
Support `adduser`

### ISSUE THREAD

**Issue by cole-h** [DeterminateSystems/nix-installer#284]
As seen in https://github.com/DeterminateSystems/nix-installer/issues/282, we should support `useradd` _or_ `adduser` and detect this as soon as possible (and error if neither are found).

Sidenote: we might want to abstract this to all places where we run commands: try to find out if the binary exists / is executable, and error otherwise...?

TODO:
* see if we can use nss/pam directly?

**Comment by Hoverbear** [comment]
A crate like `which` (https://crates.io/crates/which) can be used to determine if a command exists.

I'm not sure if we need to check this for each command. We already return an error if we try to execute a command and it doesn't exist. In the general case, that's reasonable.

In this specific case, I think it would be sufficient to have the `CreateUser` action to have some step in the plan phase that detects which command it should use and stores that to later use in execute.
