### ISSUE TITLE
MacOS: Cannot unmount already unmounted disk

### ISSUE THREAD

**Issue by kashifsoofi** [DeterminateSystems/nix-installer#285]
OS: macOS Big Sur 11.7.2

I have previously installed Nix that was not in a working state, so I cleaned up as suggested by the installer. After running I got following

```
curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix | sh -s -- install
info: downloading installer https://install.determinate.systems/nix/tag/v0.4.0/nix-installer-x86_64-darwin
`nix-installer` needs to run as `root`, attempting to escalate now via `sudo`...
Nix install plan (v0.4.0)

Planner: macos

Planner settings:

* volume_label: "Nix Store"
* nix_build_user_count: 32
* case_sensitive: false
* modify_profile: true
* channels: ["nixpkgs=https://nixos.org/channels/nixpkgs-unstable"]
* diagnostic_endpoint: "https://install.determinate.systems/nix/diagnostic"
* nix_package_url: "https://releases.nixos.org/nix/nix-2.13.2/nix-2.13.2-x86_64-darwin.tar.xz"
* volume_encrypt: null
* root_disk: "disk1"
* extra_conf: []
* nix_build_group_name: "nixbld"
* nix_build_group_id: 30000
* nix_build_user_prefix: "_nixbld"
* nix_build_user_id_base: 300
* force: false

The following actions will be taken:

* Create an APFS volume `Nix Store` for Nix on `disk1`
* Fetch `https://releases.nixos.org/nix/nix-2.13.2/nix-2.13.2-x86_64-darwin.tar.xz` to `/nix/temp-install-dir`
* Create build users (UID 300-332) and group (GID 30000)
* Create a directory tree in `/nix`
* Move the downloaded Nix into `/nix`
* Setup the default Nix profile
* Place the Nix configuration in `/etc/nix/nix.conf`
* Place channel configuration at `/Users/kashif/.nix-channels`
* Configure the shell profiles
* Configure Nix daemon related settings with launchctl


Proceed? ([Y]es/[n]o/[e]xplain): Y
 INFO Step: Create an APFS volume `Nix Store` for Nix on `disk1`
ERROR Error saving receipt: RecordingReceipt("/nix/receipt.json", Os { code: 30, kind: ReadOnlyFilesystem, message: "Read-only file system" })
ERROR
   0: Install failure
   1: Error executing action
   2: Failed to execute command
   3: Command `"launchctl" "bootstrap" "system" "/Library/LaunchDaemons/org.nixos.darwin-store.plist"` failed status 37, stderr:
      /Library/LaunchDaemons/org.nixos.darwin-store.plist: service already bootstrapped
      Bootstrap failed: 37: Operation already in progress

   3:

Location:
   /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/convert/mod.rs:726

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
Installation failure, offering to revert...
Nix uninstall plan

Planner: macos

Planner settings:

* volume_label: "Nix Store"
* nix_package_url: "https://releases.nixos.org/nix/nix-2.13.2/nix-2.13.2-x86_64-darwin.tar.xz"
* extra_conf: []
* nix_build_group_id: 30000
* nix_build_user_prefix: "_nixbld"
* nix_build_user_id_base: 300
* case_sensitive: false
* channels: ["nixpkgs=https://nixos.org/channels/nixpkgs-unstable"]
* force: false
* diagnostic_endpoint: "https://install.determinate.systems/nix/diagnostic"
* nix_build_user_count: 32
* nix_build_group_name: "nixbld"
* root_disk: "disk1"
* modify_profile: true
* volume_encrypt: null

The following actions will be taken (`--explain` for more context):

* Remove the APFS volume `Nix Store` on `disk1`


Proceed? ([Y]es/[n]o/[e]xplain): Y
 INFO Revert: Configure Nix daemon related settings with launchctl
 INFO Revert: Configure Nix
 INFO Revert: Provision Nix
 INFO Revert: Create an APFS volume `Nix Store` for Nix on `disk1`
ERROR Error saving receipt: RecordingReceipt("/nix/receipt.json", Os { code: 30, kind: ReadOnlyFilesystem, message: "Read-only file system" })
Error:
   0: Error executing action
   1: Failed to execute command
   2: Command `"/usr/sbin/diskutil" "unmount" "force" "Nix Store"` failed status 1, stderr:
      disk1s7 was already unmounted

   2:

Location:
   /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/convert/mod.rs:726

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
```

**Comment by natecox** [comment]
FWIW, I had to go into the disk utilities app and delete the APFS volume there.

I'm still having issues with permissions after this, but the installer did finish successfully after deleting that volume (and several other cleanup steps I got one at a time by rerunning the installer).

**Comment by kashifsoofi** [comment]
I checked before running the installer (after cleaning up) that there is no APFS volume. And I was able to delete the volume after installer failed to install nix and as a result uninstaller failed to delete APFS volumne. I have not tried running it again though.

**Comment by Hoverbear** [comment]
Oh no! Dangit, I thought I fixed this.

It looks like you had a `org.nixos.darwin-store.plist` daemon in launchctl already... But we weren't able to detect it.

I believe this bug will be fixed by #246 which should get merged soon. I don't expect it will make it into 0.5.0, but curing is the main topic of 0.6.0.

Regarding permissions: That is a known issue and our 0.5.0 on Monday-ish should fix it. Sorry about that!

**Comment by natecox** [comment]
No apology necessary, thanks for being so responsive. This project is a major milestone in making nix accessible to people outside of a small niche.

**Comment by kashifsoofi** [comment]
> Oh no! Dangit, I thought I fixed this.
> 
> It looks like you had a `org.nixos.darwin-store.plist` daemon in launchctl already... But we weren't able to detect it.
> 
> I believe this bug will be fixed by #246 which should get merged soon. I don't expect it will make it into 0.5.0, but curing is the main topic of 0.6.0.
> 
> Regarding permissions: That is a known issue and our 0.5.0 on Monday-ish should fix it. Sorry about that!

No apology necessary, I am pretty sure I deleted that file before installing though shouldn't that fix that? I will try the installer after these changes are merged.

**Comment by Hoverbear** [comment]
@kashifsoofi I am not 100% clear how/where Mac handles it's init system data, it's possible some was left over.

**Comment by kashifsoofi** [comment]
> @kashifsoofi I am not 100% clear how/where Mac handles it's init system data, it's possible some was left over.

That makes 2 of us :)

**Comment by Hoverbear** [comment]
Here's a version that should cure partially done APFS related things:

```
curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix/pr/246 | sh -s -- install
```

**Comment by kashifsoofi** [comment]
> Here's a version that should cure partially done APFS related things:
> 
> ```
> curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix/pr/246 | sh -s -- install
> ```

Thanks that worked, nix is installed version 2.13.3

**Comment by Hoverbear** [comment]
This is now merged to `main` (but not released)!
