### ISSUE TITLE
Document Versioning and pinning

### ISSUE THREAD

**Issue by mausch** [DeterminateSystems/nix-installer#288]
Hi and thanks for this new installer!

The current README doesn't seem to mention what version of Nix gets installed or how to control that.

Also how do I pin the version of the installer itself?
I assume that instead of the documented:
```
curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix | sh -s -- install
```
I'd run this?
```
curl --proto '=https' --tlsv1.2 -sSf -L https://github.com/DeterminateSystems/nix-installer/releases/download/v0.4.0/nix-installer.sh | sh -s -- install
```

This is worth documenting I think, especially since Nix users care a lot about pinning everything as you know :slightly_smiling_face: 

Maybe related: https://github.com/DeterminateSystems/nix-installer/issues/69

**Comment by Hoverbear** [comment]
For the installer, you can pick any tag via `curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix/tag/v0.4.0 | sh -s -- install`, or use github releases (do note these appear to be rate limited)

We should document this, you're right!
