### ISSUE TITLE
MacOS: can you test an install of Nix in one user account, leaving the others untouched?

### ISSUE THREAD

**Issue by vielmetti** [DeterminateSystems/nix-installer#301]
Environment: my MacBook Air (M1) which is my daily use laptop.

The challenge: try out nix-installer and Nix on this hardware, but don't go all-in yet.

Does it make any sense to create a new user account on MacOS, and
try Nix there, leaving my original user account still using brew / Homebrew?

The idea is that user "foo" would log in and have a home
directory of ~foo and a PATH that had Homebrew binaries
on it, but that user "bar" would log in and have a home 
directory of ~bar and a PATH that had Nix binaries. (And
then slowly or quickly, as you get comfortable with the
new environment, you move things over).

I have plenty of disk space so dups of more or less everything
in user land is OK for now.

**Comment by Hoverbear** [comment]
Nix on MacOS requires things like a system daemon (in launchctl) and some special volume setup yet, so installing Nix is a system-wide action. If you desire, you can configure the allowed users in the nix.conf: https://nixos.org/manual/nix/stable/command-ref/conf-file.html#conf-allowed-users
