### ISSUE TITLE
A fish user on archlinux had a bad time, plus info about vendor-conf.d

### ISSUE THREAD

**Issue by grahamc** [DeterminateSystems/nix-installer#302]
I read this thread https://mastodon.social/@vascorsd/109955987515359582

and this part in particular:

> Symlinked /etc/profile.s/nix-daemon.fish to /usr/share/fish/vendor-conf.d and seems to have properly loaded. NIX_PATH and NIX_SSL* are now defined.

which lead me to finding:

```
if not set -q FISH_UNIT_TESTS_RUNNING
    set __fish_vendor_completionsdirs $__fish_user_data_dir/vendor_completions.d $xdg_data_dirs/vendor_completions.d
    set __fish_vendor_functionsdirs $__fish_user_data_dir/vendor_functions.d $xdg_data_dirs/vendor_functions.d
    set __fish_vendor_confdirs $__fish_user_data_dir/vendor_conf.d $xdg_data_dirs/vendor_conf.d
```

https://github.com/fish-shell/fish-shell/blob/307c58dd072283ea2f91c0bb636a469d6fb1d6ab/share/config.fish#L57-L60

...which makes me think we should add `/usr/share/fish` to our list of potential locations, and use vendor_conf.d in (some?) scenarios.
https://github.com/DeterminateSystems/nix-installer/blob/903258942cac252c4f36fe8bea99b6de93865f2c/src/action/common/configure_shell_profile.rs#L11-L23

**Comment by Hoverbear** [comment]
Yup that makes sense: https://fishshell.com/docs/3.3/index.html#configuration-files

```
Directories for third-party software vendors to ship their own configuration snippets for their software. Fish searches the directories in the XDG_DATA_DIRS environment variable for a fish/vendor_conf.d directory; if that variable is not defined, the default is /usr/share/fish/vendor_conf.d and /usr/local/share/fish/vendor_conf.d, unless your distribution customized this.
```
