### ISSUE TITLE
Installing in a container running in GKE

### ISSUE THREAD

**Issue by Jonpez2** [DeterminateSystems/nix-installer#314]
Hello!  I have a fairly vanilla container based on debian, running in GKE, into which I would like to install nix.  However I get the following error (even running under sudo).  Is there any way you know of to work around this?

(Thank you so much for making this tool and pushing for accessible nix.  It's going to be incredibly helpful.)

```
~/nix-installer$ sudo ./nix-installer-x86_64-linux install --diagnostic-endpoint=file:///home/coder/nix-installer/diagnostic.txt
Nix install plan (v0.5.0)

Planner: linux

Planner settings:

* nix_package_url: "https://releases.nixos.org/nix/nix-2.13.3/nix-2.13.3-x86_64-linux.tar.xz"
* nix_build_user_count: 32
* start_daemon: false
* force: false
* nix_build_group_id: 30000
* diagnostic_endpoint: "file:///home/coder/nix-installer/diagnostic.txt"
* modify_profile: true
* extra_conf: []
* nix_build_group_name: "nixbld"
* nix_build_user_id_base: 30000
* nix_build_user_prefix: "nixbld"
* channels: ["nixpkgs=https://nixos.org/channels/nixpkgs-unstable"]
* init: "None"

The following actions will be taken:

* Create directory `/nix`
* Fetch `https://releases.nixos.org/nix/nix-2.13.3/nix-2.13.3-x86_64-linux.tar.xz` to `/nix/temp-install-dir`
* Create build users (UID 30000-30032) and group (GID 30000)
* Create a directory tree in `/nix`
* Move the downloaded Nix into `/nix`
* Setup the default Nix profile
* Place the Nix configuration in `/etc/nix/nix.conf`
* Place channel configuration at `/root/.nix-channels`
* Configure the shell profiles


Proceed? ([Y]es/[n]o/[e]xplain): 
 INFO Step: Create directory `/nix`
 INFO Step: Provision Nix
 INFO Step: Configure Nix
ERROR 
   0: Install failure
   1: Error executing action `configure_nix`
   2: Child action `setup_default_profile`
   3: Failed to execute command with status 1 `"/nix/store/mc43d38fibi94pp5crfwacl5gbslccd0-nix-2.13.3/bin/nix-env" "-i" "/nix/store/mc43d38fibi94pp5crfwacl5gbslccd0-nix-2.13.3"`, stdout: 
      stderr: installing 'nix-2.13.3'
      error: unable to make '/' private: Permission denied
      (use '--show-trace' to show detailed location information)

   3: 

Location:
   /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/convert/mod.rs:726

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.

Consider reporting this error using this URL: https://github.com/DeterminateSystems/nix-installer/issues/new?title=%3Cautogenerated-issue%3E&body=%23%23+Error%0A%60%60%60%0AError%3A+%0A+++0%3A+Install+failure%0A+++1%3A+Error+executing+action+%60configure_nix%60%0A+++2%3A+Child+action+%60setup_default_profile%60%0A+++3%3A+Failed+to+execute+command+with+status+1+%60%22%2Fnix%2Fstore%2Fmc43d38fibi94pp5crfwacl5gbslccd0-nix-2.13.3%2Fbin%2Fnix-env%22+%22-i%22+%22%2Fnix%2Fstore%2Fmc43d38fibi94pp5crfwacl5gbslccd0-nix-2.13.3%22%60%2C+stdout%3A+%0A++++++stderr%3A+installing+%27nix-2.13.3%27%0A++++++error%3A+unable+to+make+%27%2F%27+private%3A+Permission+denied%0A++++++%28use+%27--show-trace%27+to+show+detailed+location+information%29%0A%0A%0A%60%60%60
Installation failure, offering to revert...
Nix uninstall plan

Planner: linux

Planner settings:

* modify_profile: true
* extra_conf: []
* nix_build_user_id_base: 30000
* start_daemon: false
* nix_build_group_id: 30000
* nix_build_group_name: "nixbld"
* nix_build_user_prefix: "nixbld"
* diagnostic_endpoint: "file:///home/coder/nix-installer/diagnostic.txt"
* nix_build_user_count: 32
* init: "None"
* force: false
* channels: ["nixpkgs=https://nixos.org/channels/nixpkgs-unstable"]
* nix_package_url: "https://releases.nixos.org/nix/nix-2.13.3/nix-2.13.3-x86_64-linux.tar.xz"

The following actions will be taken (`--explain` for more context):

* Unconfigure the shell profiles
* Remove channel configuration at `/root/.nix-channels`
* Remove the Nix configuration in `/etc/nix/nix.conf`
* Unset the default Nix profile
* Remove the directory tree in `/nix`
* Remove Nix users and group
* Remove the directory `/nix`


Proceed? ([Y]es/[n]o/[e]xplain): 
 INFO Revert: Leave the Nix daemon unconfigured
 INFO Revert: Configure Nix
 INFO Revert: Provision Nix
 INFO Revert: Create directory `/nix`
Partial Nix install was uninstalled successfully!

~/nix-installer$ cat diagnostic.txt 
{
  "version": "0.5.0",
  "planner": "linux",
  "configured_settings": [
    "diagnostic_endpoint"
  ],
  "os_name": "Debian GNU/Linux",
  "os_version": "11 (bullseye)",
  "triple": "x86_64-unknown-linux-musl",
  "is_ci": false,
  "action": "Uninstall",
  "status": "Success",
  "failure_chain": null
}
```

**Comment by Jonpez2** [comment]
Interestingly, perhaps, I just went off to try [nix-portable](https://github.com/DavHau/nix-portable), which previously had not worked for me, but now appears to work fine.  Is that what I should be doing?

Thanks!

**Comment by Jonpez2** [comment]
Hmm, I may have spoken too soon, as I'm now getting sqlite errors with nix-portable.  Sorry for the noise.

I'd love to know whether there is a good approach here and what it is please!

Thanks!

**Comment by Hoverbear** [comment]
Hi @Jonpez2 ! I think you're facing the same issue some podman containers face? Could you try adding ` --extra-conf "sandbox = false"`? Here are some examples: https://github.com/DeterminateSystems/nix-installer#in-a-container

**Comment by Hoverbear** [comment]
Ah ya you need to use the daemonless version. `--init none`. :(

We've spoke a bit about the non-root single user scenario and while it's something I'd like to support it's not really the best experience for users. It breaks multi-user systems, lacks a lot of sandboxing support, and provides a less complete experience to users. We implemented the root-only support to see if folks would find it a good middle-ground, where you could still get features like sandboxing and multi-user support, but no daemon was required.

Unfortunately a truly-good rootless Nix isn't well supported, since virtually all cached packages rely on `/nix` existing, something a normal user can't necessarily do.

We're still researching how to provide this rootless experience best to users -- It'd be especially nice to provide an option that didn't require root to install, too!

**Comment by Jonpez2** [comment]
That makes a lot of sense. I’ll work with this and watch out for further
developments! Thanks again for your work and your help!

**Comment by Jonpez2** [comment]
FWIW, I thought about this a bit more, and I think it's probably worth pushing on the non-root single-user container install.  I expect a bunch of people will be looking for this configuration as they move to various flavours of k8s-hosted remote backends for their dev env.  This is in fact my usecase.
As far as I understand, the consensus seems to be that running such backends as root, or with significant sudo-into-root actions, results in a greater attack surface than simply running as a normal user.

**Comment by Hoverbear** [comment]
How are you running services typically required for development, like PostgreSQL? Are you using some other init system, or systemd? If it's possible to start services then using Nix in the normal daemon based mode may be better.

**Comment by Jonpez2** [comment]
We haven’t had a need for such things… there’s just sshd which we start in
an entrypoibt script.

Perhaps I should go and research container init systems!

**Comment by Jonpez2** [comment]
So, I've done some research at least on systemd, and the results don't look awesome.  It appears to require, for example, SYS_ADMIN, which presents a rather large attack surface.  This doesn't seem likely to fly with hosted systems, I think?

I'm a bit over my skis here so please forgive any ignorant assertions!

**Comment by Jonpez2** [comment]
Sorry to keep throwing ideas onto this but... would a more "k8s-native" approach be to have a sidecar container that hosts the builders?  Then it writes to a shared /nix, which the developer's container mounts readonly?  Is that plausible?

**Comment by Hoverbear** [comment]
Okay so an init daemon isn't possible! Then yes, you're kind of in a spot. It seems like you're using multiple users (root and some other user) in a container without an init system.

The single user option from the official scripts is an option, but be aware that this is a less robust option for using Nix. You lose out on some sandboxing features, but since you're already in a dev container that may not matter to you!

I'll chat with some folks and see if we can find a better solution for `nix-installer`.

**Comment by Jonpez2** [comment]
Thank you again for your time and understanding

**Comment by Hoverbear** [comment]
We do support installing in GKE containers, just the support requires root-only mode. Lacking `--init systemd` support, it's the best this installer can do without significant changes to our architecture. There already exists https://github.com/DeterminateSystems/nix-installer/issues/214 for the more general case of a Nix install that does not require root or init daemon things.
