### ISSUE TITLE
Nix build users should contain their index in the comment

### ISSUE THREAD

**Issue by cole-h** [DeterminateSystems/nix-installer#323]
> (Also, the official scripts include the user's number... We might want to do the same.)

_Originally posted by @cole-h in https://github.com/DeterminateSystems/nix-installer/pull/319#discussion_r1131436879_
            

Right now, we don't say e.g. `Nix build user 29` but `Nix build user` -- for anything that uses that comment, it's not all that informative, so we should follow upstream's lead and include the digits in that comment.

**Comment by Hoverbear** [comment]
https://github.com/DeterminateSystems/nix-installer/pull/330
