### ISSUE TITLE
darwin: disk was already unmounted

### ISSUE THREAD

**Issue by cdmistman** [DeterminateSystems/nix-installer#326]
Came across this error, this is the 2nd time I've used this script (on separate systems). Didn't come across it the first time, both systems had a previous running version of Nix.

## Error
```
 INFO Revert: Configure Nix daemon related settings with launchctl
 INFO Revert: Configure Nix
 INFO Revert: Provision Nix
 INFO Revert: Create an APFS volume `Nix Store` for Nix on `disk3`
ERROR Error saving receipt: RecordingReceipt("/nix/receipt.json", Os { code: 30, kind: ReadOnlyFilesystem, message: "Read-only file system" })
Error:
   0: Error executing action `create_apfs_volume`
   1: Child action `unmount_apfs_volume`
   2: Failed to execute command with status 1 `"/usr/sbin/diskutil" "unmount" "force" "Nix Store"`, stdout:
      stderr: disk3s7 was already unmounted
```

**Comment by Hoverbear** [comment]
Thanks for this report Colton! I expect it's because we're not properly checking if we actually need to unmount it. I'll take a look.

**Comment by Hoverbear** [comment]
So this should be fixed next version. You can see in v0.5.0:

https://github.com/DeterminateSystems/nix-installer/blob/9d939e788581eeba3361e607ac8fbc3adfe70637/src/action/macos/unmount_apfs_volume.rs#L55-L68

https://github.com/DeterminateSystems/nix-installer/blob/b96e6b25136210204ad7351c23dc36a6418e30c6/src/action/macos/unmount_apfs_volume.rs#L57-L89

So you shouldn't bump into this after we cut a new release in the next couple days!

**Comment by cdmistman** [comment]
thanks Ana!
