### ISSUE TITLE
Nix paths appended to `$PATH`

### ISSUE THREAD

**Issue by briankung** [DeterminateSystems/nix-installer#327]
Hi there 👋 I'm new to Nix and using macOS (`aarch64-darwin`). I started with [Zero to Nix](https://zero-to-nix.com/) and went through [Tidying up your $HOME with Nix](https://juliu.is/tidying-your-home-with-nix/) which is a `home-manager` tutorial. Unfortunately when I use `home-manager` to install Ruby, the path still resolves to the system Ruby. After some investigation, it looks like Ruby is installed, but the nix paths are appended to the end of `$PATH`, so `ruby` resolves to `/usr/bin/ruby` rather than the nix Ruby:

```sh
❯ type -a ruby
ruby is /usr/bin/ruby
ruby is /Users/brian/.nix-profile/bin/ruby

❯ echo $PATH
/* a bunch of default paths *:/Users/brian/.nix-profile/bin:/nix/var/nix/profiles/default/bin
```

I can't figure out how my PATH was modified by the installer - I assume it's the installer. Is there a way to configure this so that it prepends the nix paths instead of appends them?

EDIT - I fixed this for my own use case by prepending the nix paths (`/Users/brian/.nix-profile/bin:/nix/var/nix/profiles/default/bin`) to my `$PATH`.

**Comment by abathur** [comment]
I'm guessing zshenv is used here to keep Nix's hooks from getting evicted by macOS updates, but using it does have the side-effect of leaving Nix at the end of the path due to how `path_helper` works, and the fact that /etc/zshenv will get sourced before `/etc/zprofile` runs `path_helper`.

Background:
- nixos/nix#3616
- nixos/nix#3456
- nixos/nix#3608
- nixos/nix#4169
- nixos/nix#5179

**Comment by Hoverbear** [comment]
I worry that prefixing nix's `ruby` on the path over the system `ruby` on Mac may cause unforseen consequences! MacOS does utterly strange things (like invoke perl inside it's libc).

Consider, for example, the purpose of `rbenv` and `rvm`. These tools provide different versions of Ruby in a scope manner for your different workspaces. Nix also offers this functionality, you could install some version of Ruby far in the future (or past) compared to the one MacOS offers. You may do this, for example, as part of installing a dev toolchain... But changing your global ruby is rarely what you may intend to do.

What I *presume* (and I may be wrong!!!) is that you want to use some specific (likely, newer) Ruby version in your favorite project. One way I like to do this is making a `flake.nix`:

```nix
{
  outputs = { self, nixpkgs }: {
    devShells."aarch64-darwin".default = let pkgs = import nixpkgs { system = "aarch64-darwin"; }; in pkgs.mkShell {
      buildInputs = with pkgs; [
        ruby_2_7
      ];
    };
  };
}
```

Then doing `nix develop` in that folder. That should give you the right Ruby for your project! You can automate that `nix develop` command with `direnv` if you want.

If you do truly want to use Nix's ruby over your system Ruby, you may consider specifically adding that one toolchain to your path in the `zshrc` (Something like `nix eval --raw nixpkgs#ruby_2_7` can give you the path to the package in the store).

As such, I am not entirely sure prepending the paths is the best idea? We should consider taking action on this, but be careful we don't cause more problems than we solve doing it.

**Comment by briankung** [comment]
Hi! All very good points. In my particular case, I _do_ want to completely override the system ruby because I use it for one off shell scripts that should be largely unaffected by Ruby compatibility issues _and_ because I want the same ruby environment across several machines.

> If you do truly want to use Nix's ruby over your system Ruby, you may consider specifically adding that one toolchain to your path in the `zshrc` (Something like `nix eval --raw nixpkgs#ruby_2_7` can give you the path to the package in the store).

This seems like a good idea instead! I'm satisfied with that - if you want I'd be happy to close this issue as well. Thank you!

**Comment by Hoverbear** [comment]
In that case, you may be interested in adding a nix shebang to that script so you can keep the ruby version in alignment! More on that here: https://nixos.wiki/wiki/Nix-shell_shebang

Hope your exploration goes well!

**Comment by abathur** [comment]
I don't agree that this is resolved (but we can continue in a new issue without Brian getting the notifications if that makes sense). IMO the answer to how Brian does or doesn't access ruby is orthogonal to whether the detsys installer should be adding Nix executable locations to the head or tail of the PATH.

Using Nix's upstream shell init hooks (which prefix the PATH) and letting a macOS environment quirk shift Nix executable locations to the end of the PATH _only for zsh_ users is going to be a source of regular confusion.

If this is going to be one of the detsys installers opinions, it seems like it should be using its own shell hooks to implement this consistently across shells and installation targets?

**Comment by Hoverbear** [comment]
I didn't realize this was a discrepancy with normal behavior. :sweat_smile:

You're right, in Bash etc we do prefix the path, so we obviously should here in ZSH.

I'll work on getting a patch into this next release.

**Comment by Hoverbear** [comment]
![image](https://user-images.githubusercontent.com/130903/225077118-e85e4ff8-b2fd-4679-9e8f-38bb480c0e5e.png)

Seems our current strategy may be a bit... aggressive.

**Comment by Hoverbear** [comment]
Digging into this more, it looks like the install scripts modify zshrc: https://github.com/NixOS/nix/blob/a387f46967ae9eb97eaeb17ca26fb583283815ce/scripts/install-multi-user.sh#L36

While the insgle user scripts do zshenv and zshrc: https://github.com/NixOS/nix/blob/a387f46967ae9eb97eaeb17ca26fb583283815ce/scripts/install-nix-from-closure.sh#L235-L246

**Comment by Hoverbear** [comment]
So I tried a patched branch that only altered `zshrc` and it seems to work without altering zshenv:

```
ephemeraladmin@mac-epic-turducken ~ % nix store ping --store ssh://localhost
Store URL: ssh://localhost
```

**Comment by Hoverbear** [comment]
Ah ha! It *must* be from a remote:

```
harmonic on  zshenv-and-zshrc [$?] is 📦 v0.5.1-unreleased via 🦀 v1.67.1 via ❄️  impure (nix-install-shell-env) 
❯ nix store ping --store ssh://ephemeraladmin@mac-epic-turducken
Store URL: ssh://ephemeraladmin@mac-epic-turducken
Warning: Permanently added 'mac-epic-turducken' (RSA) to the list of known hosts.
zsh:1: command not found: nix-store
error: cannot connect to 'ephemeraladmin@mac-epic-turducken'
```

**Comment by Hoverbear** [comment]
#352 includes a fix and should be out soon!

**Comment by briankung-bpn** [comment]
That’s awesome, thanks! Given that I have already installed Nix using the Determinate Systems installer, how should I update my installation?

**Comment by briankung** [comment]
Woops, accidentally responded from my work account. 

> That’s awesome, thanks! Given that I have already installed Nix using the Determinate Systems installer, how should I update my installation?

**Comment by Hoverbear** [comment]
If you've already fixed it you should be good. :) It's not our intention to get in the way after you're installed.

**Comment by zhiyuanzhai** [comment]
Hello! I don't think this has been fixed well as binary paths with Nix are still attached to the end of `$PATH`:
```
$ echo $PATH
/Users/zhiyuanzhai/anaconda3/condabin:/opt/homebrew/opt/python@3.11/libexec/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/Library/TeX/texbin:/Users/zhiyuanzhai/.nix-profile/bin:/run/current-system/sw/bin:/nix/var/nix/profiles/default/bin
```
