### ISSUE TITLE
Fresh install fails with permissions issue on /etc/bashrc

### ISSUE THREAD

**Issue by zmitchell** [DeterminateSystems/nix-installer#358]
## Steps
1. After a reboot I download the installer via the command line:
```
$ curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix | sh -s -- install
```

2. The install immediately fails with the error below

## Error
```
Error: 
   0: Planner error
   1: Error executing action
   2: Child action `configure_shell_profile`
   3: `/etc/bashrc` exists with a different mode (755) than planned (444), consider updating it with `chmod 444 /etc/bashrc`
```

## Discussion
The permissions found on my `/etc/bashrc` are actually more permissive than the expected permissions, correct? Is there a reason that should generate an error?

**Comment by TheLonelyGhost** [comment]
Yours are actually more permissive. 755 is `rwxr-xr-x` whereas the installer is suggesting `r--r--r--`.

Separate from the installer question, I don't see any circumstance where you would want a bashrc file (or other `source`'d shell script) to be executable.

**Comment by Hoverbear** [comment]
While testing we found our Macs used `444` for those files, so codified it. Perhaps we can just remove the permission check entirely...

**Comment by TheLonelyGhost** [comment]
I'm not sure I'd remove the permission check entirely since `777` would pose a big security risk. Bad actor could write some shell code that would execute when any user opens an interactive terminal session (assuming shell == bash), purely by appending it to `/etc/bashrc`.

Testing that it doesn't have world-write permissions would be the bare (bear? *snicker*) minimum, I'd say.

**Comment by Hoverbear** [comment]
If `/etc/bashrc` exists already and is 777 out of the users own choices, it's not our place to tell them to fix it, I think! Certainly we should create it with the right mode, if we need to, though.
