### ISSUE TITLE
`/usr/share/fish/` not writable on Fedora Silverblue

### ISSUE THREAD

**Issue by dnkmmr69420** [DeterminateSystems/nix-installer#360]
## Error
```
Error: 
   0: Install failure
   1: Error executing action `configure_nix`
   2: Child action `configure_shell_profile`
   3: Child action `create_or_insert_into_file`
   4: Open path `/usr/share/fish/vendor_conf.d/nix-installer-tmp.4025512441`
   5: Read-only file system (os error 30)
```

**Comment by Hoverbear** [comment]
Hi! Thanks for this report. I suppose we need to do some more testing on Silverblue.

**Comment by Hoverbear** [comment]
Interestingly, the Steam Deck had a similar issue #367 .

**Comment by dnkmmr69420** [comment]
WIll this bug be fixed?

**Comment by Hoverbear** [comment]
There are a number of issue installing on Silverblue, even if we fixed this particular issue I don't think install would work.

This last release we added SELinux support, which I believe is required for Silverblue.

#389 is a ticket that would introduce full Silverblue support, and I'm hoping we can do it soon.

**Comment by Hoverbear** [comment]
(Closing this in favor of the greater #389 ticket)
