### ISSUE TITLE
Both Installers & Uninstallers Fail

### ISSUE THREAD

**Issue by ChetanBhasin** [DeterminateSystems/nix-installer#368]
I've run into an interesting issue that upon restart My nix configuration seems to have disappeared from Mac and it can't bootstrap.

I tried both installer and uninstaller and neither seems to work. I can't figure it out so I'm attaching the entire log here.

## Error
```
Error: 
   0: Reading receipt
   1: No such file or directory (os error 2)
```

## Backtrace

<details>

```
Backtrace:
   0: __mh_execute_header
   1: __mh_execute_header
   2: __mh_execute_header
   3: __mh_execute_header
   4: __mh_execute_header
   5: __mh_execute_header
   6: __mh_execute_header
   7: __mh_execute_header
   8: __mh_execute_header
   9: __mh_execute_header
  10: __mh_execute_header
  11: __mh_execute_header
  12: __mh_execute_header

```
</details>

**Comment by Hoverbear** [comment]
If you revisit this to add more info please reopen it! Thanks!
