### ISSUE TITLE
Install failure on a brand new MBP 16 M1

### ISSUE THREAD

**Issue by derekcrovo** [DeterminateSystems/nix-installer#369]
## Error
```
Error: 
   0: Install failure
   1: Error executing action `create_apfs_volume`
   2: Child action `create_fstab_entry`
   3: Failed to execute command with status 1 `"/usr/sbin/diskutil" "info" "-plist" "Nix Store"`, stdout: <?xml version="1.0" encoding="UTF-8"?>
      <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
      <plist version="1.0">
      <dict>
      	<key>Error</key>
      	<true/>
      	<key>ErrorMessage</key>
      	<string>Could not find disk: Nix Store</string>
      	<key>ExitCode</key>
      	<integer>1</integer>
      </dict>
      </plist>

      stderr: 

```

**Comment by derekcrovo** [comment]
Oh look at that, I ran it again and it worked. The only difference was the first time it asked for my password for sudo and the second time it was already cached.

**Comment by Hoverbear** [comment]
@derekcrovo Can you help me understand a bit better? The first time you got asked your password at some point (other than at the start of the install process before the prompt?)

**Comment by Hoverbear** [comment]
Right now we do `diskutil apfs addVolume "APFS" "Nix Store" -nomount` then pretty much immediately do `diskutil info -plist "Nix Store"` to get the UUID it was created with. Perhaps it's possible Apple is returning success from the function before the volume has information present in the `disktuil info -plist "Nix Store"` command.
