### ISSUE TITLE
SSL connect error (35) while running command from quickstart

### ISSUE THREAD

**Issue by mauricioabreu** [DeterminateSystems/nix-installer#370]
# Context

I'm following the quickstart and it is the 3rd time I'm having the same issues.

Installation was ok, but every time I get to [this point](https://zero-to-nix.com/start/nix-develop) my mac starts to have some problems outside of the nix environment.

# Command and Errors

Command and error I had:

```
➜  ~ nix develop "github:DeterminateSystems/zero-to-nix#go"
```

```
warning: error: unable to download 'https://cache.nixos.org/3j2zanz8vixwdy0r92344ys9v6m83v28.narinfo': SSL connect error (35); retrying in 300 ms
warning: error: unable to download 'https://cache.nixos.org/3j2zanz8vixwdy0r92344ys9v6m83v28.narinfo': SSL connect error (35); retrying in 669 ms
warning: error: unable to download 'https://cache.nixos.org/3j2zanz8vixwdy0r92344ys9v6m83v28.narinfo': SSL connect error (35); retrying in 1383 ms
warning: error: unable to download 'https://cache.nixos.org/3j2zanz8vixwdy0r92344ys9v6m83v28.narinfo': SSL connect error (35); retrying in 2667 ms
error: unable to download 'https://cache.nixos.org/3j2zanz8vixwdy0r92344ys9v6m83v28.narinfo': SSL connect error (35)
```

Now the interesting part: if I try to curl a website, for example, Google, I get some errors:

```
➜  ~ curl https://www.google.com
curl: (35) Recv failure: Software caused connection abort
```

It looks like Nix is messing my mac OS (M1) in some way.

**Comment by Hoverbear** [comment]
Nix and the installer don't touch your Mac's curl or ca-certificates in any way. The fact that you are getting them suggests to me that your computer may be experiencing adverse networking conditions unrelated to Nix.

Are you only getting the errors after running `nix develop`?

Can you uninstall `/nix/nix-installer uninstall` then confirm curl is still broken?

**Comment by mauricioabreu** [comment]
I did the same sequence of _installing and uninstalling_ many many times, like five times. I even rebooted the system between one attempt and another.

Even with the official installer I had a similar problem. But with the DeterminateSystems installer the error starts after executing the `develop` subcommand.

I had a pretty functional installation before trying out this installar. Not sure what went wrong.

**Comment by Hoverbear** [comment]
So you're seeing the same error with the official install scripts as well? But not at the same time? Could you elaborate a bit?

Did you perhaps set `--ssl-cert-file` or `NIX_INSTALLER_SSL_CERT_FILE` during install?

Do you have the `HTTPS_PROXY` or `https_proxy` environments set in the shell where `curl` is failing?

Do you have the `NIX_SSL_CERT_FILE` environment set in the shell where `nix develop` is giving you issues?

Can you please tell me if you're on a corporate network with a possible MITM tls ca/proxy?

**Comment by Hoverbear** [comment]
Thank you for confirming. I'll try to reproduce.

**Comment by mauricioabreu** [comment]
@Hoverbear sorry for not giving any feedback here recently. Can I help you with something? Logs maybe?

**Comment by Hoverbear** [comment]
@mauricioabreu I asked you several questions in https://github.com/DeterminateSystems/nix-installer/issues/370#issuecomment-1485764913 which I'd still love an answer to.

**Comment by mauricioabreu** [comment]
@Hoverbear omg sorry I thought you were talking to the other person in the thread. My apologies.

> Did you perhaps set --ssl-cert-file or NIX_INSTALLER_SSL_CERT_FILE during install? 

**No, never.**

> Do you have the HTTPS_PROXY or https_proxy environments set in the shell where curl is failing?

**No**

> Do you have the NIX_SSL_CERT_FILE environment set in the shell where nix develop is giving you issues?

**No**

Can you please tell me if you're on a corporate network with a possible MITM tls ca/proxy?
**No.**

**Comment by mauricioabreu** [comment]
@Hoverbear if you want me to reinstall nix using the _nix-installer_ and collect some logs, drop a message and I'll be glad to help.

**Comment by Hoverbear** [comment]
That is extremely bizarre... I wonder if it still occurs. If you're not setting the SSL cert yourself we don't do anything different than the official installer...

At least the original issue you reported could be attributed to some SSL anamoly or bug at the time. 

If you have a working Nix install right now, it's ok to keep it and we'll keep this issue around in case we can reproduce it in the future. Thanks so much for circling back!

**Comment by mauricioabreu** [comment]
@Hoverbear The original installer fails in different ways. Maybe it is my macOS version (Ventura 13.2.1 I guess)
I will try to reinstall again this weekend and send some logs/commands/screenshots here or in the original installer

**Comment by Hoverbear** [comment]
Could you also try opening https://cache.nixos.org/3j2zanz8vixwdy0r92344ys9v6m83v28.narinfo in your browser?

**Comment by mauricioabreu** [comment]
Browser: 404
curl: 404

**Comment by mauricioabreu** [comment]
Yes, the same @Hoverbear 

```
➜  ~ which curl
/opt/homebrew/opt/curl/bin/curl
```

I installed `curl` with homebrew. I'm not using any kind of nix right now because of the errors described in this issue.

**Comment by mauricioabreu** [comment]
Closing it. At the time I opened this issue, I thought it had to do with this installer but it turns out it is another problem. Thank you for your help @Hoverbear
