### ISSUE TITLE
A Fedora Silverblue planner

### ISSUE THREAD

**Issue by Hoverbear** [DeterminateSystems/nix-installer#389]
Given things like #360 and https://github.com/DeterminateSystems/nix-installer/issues/124, we may need to investigate a dedicated planner for Silverblue, ala the Steam Deck planner.

This issue, for now, should serve to aggregate things related to Silverblue.

**Comment by dnkmmr69420** [comment]
it would be really cool to have an installer from determinate for nix on silverblue

**Comment by Hoverbear** [comment]
It looks like the incredibly talented @dnkmmr69420 puzzled out how to get this working!

https://github.com/dnkmmr69420/nix-installer-scripts/blob/main/installer-scripts/silverblue-nix-installer.sh

Perhaps we can use this for inspiration.

**Comment by dnkmmr69420** [comment]
> It looks like the incredibly talented @dnkmmr69420 puzzled out how to get this working!
> 
> https://github.com/dnkmmr69420/nix-installer-scripts/blob/main/installer-scripts/silverblue-nix-installer.sh
> 
> Perhaps we can use this for inspiration.

I agree with that. I hope there will be a silverblue installer soon.
