### ISSUE TITLE
Nix installer fails on Clear Linux

### ISSUE THREAD

**Issue by worldofgeese** [DeterminateSystems/nix-installer#391]
Clear is largely immutable much like SteamOS. I'm wondering if a SteamOS approach might work?

## Error
```
ERROR 
   0: Install failure
   1: Error executing action `configure_init_service`
   2: Symlinking from `/nix/var/nix/profiles/default/lib/tmpfiles.d/nix-daemon.conf` to `/etc/tmpfiles.d/nix-daemon.conf`
   3: No such file or directory (os error 2)
```

**Comment by Hoverbear** [comment]
Hmm the steamos planner uses some steamos specific thing, this is likely closer to #389 ?

**Comment by marikgoran** [comment]
I had to make the a couple of dirs in `/etc` for ClearLinux, as they are missing from default due to its immutable nature.

```
mkdir -p /etc/tempfiles.d/
mkdir -p /etc/profile.d/
```

After that running the installer with `RUST_BACKTRACE=full  ./nix-installer install` worked for me.

**Comment by Hoverbear** [comment]
This is now merged into main and will be part of the next release! Thanks for bringing it to our attention and even a suggestion how to fix it. :)
