### ISSUE TITLE
Cannot find disk during fresh installation

### ISSUE THREAD

**Issue by shoekstra** [DeterminateSystems/nix-installer#394]
Hi,

I cannot get past this error.

I had Nix installed before and uninstalled it following [these steps](https://iohk.zendesk.com/hc/en-us/articles/4415830650265-Uninstall-nix-on-MacOS). I ensured the volume had been cleaned up and rebooted (so no volume or `/nix` folder present). I guess there is something lingering that makes the installer think the volume has been created.

I've gone through the [similar'ish issues](https://github.com/DeterminateSystems/nix-installer/issues?q=is%3Aissue+Could+not+find+disk%3A+Nix+Store) but didn't see any fixes.

## Error
```
Error: 
   0: Planner error
   1: Error executing action
   2: Child action `setup_volume_daemon`
   3: Failed to execute command with status 1 `"/usr/sbin/diskutil" "info" "-plist" "Nix Store"`, stdout: <?xml version="1.0" encoding="UTF-8"?>
      <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
      <plist version="1.0">
      <dict>
      	<key>Error</key>
      	<true/>
      	<key>ErrorMessage</key>
      	<string>Could not find disk: Nix Store</string>
      	<key>ExitCode</key>
      	<integer>1</integer>
      </dict>
      </plist>

      stderr: 

```

## Metadata
|key|value|
|--|--|
|**version**|0.7.0|
|**os**|macos|
|**arch**|x86_64|

**Comment by Hoverbear** [comment]
I think this situation is something we should be able to cure, just need to figure out how.

**Comment by shoekstra** [comment]
Sorry for the delayed response. Yup, that did the trick!

I ran into another issue, but after running `/nix/nix-installer uninstall` and installing again, it went through issue free. Thanks for the pointer!

**Comment by Hoverbear** [comment]
Sorry just reopening this as I do have a fix to prevent this in the future now!
