### ISSUE TITLE
nix.daemon.socket not loaded during cure on Ubuntu Mate

### ISSUE THREAD

**Issue by jradxl** [DeterminateSystems/nix-installer#402]
## Error
```
Error: 
   0: Install failure
   1: Error executing action `configure_init_service`
   2: Failed to execute command with status 5 `"systemctl" "disable" "nix-daemon.socket" "--now"`, stdout: 
      stderr: Removed "/etc/systemd/system/sockets.target.wants/nix-daemon.socket".
      Removed "/etc/systemd/system/nix-daemon.socket".
      Failed to stop nix-daemon.socket: Unit nix-daemon.socket not loaded.


```

## Metadata
|key|value|
|--|--|
|**version**|0.7.0|
|**os**|linux|
|**arch**|x86_64|

**Comment by jradxl** [comment]
$ curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix | sh -s -- install
info: downloading installer https://install.determinate.systems/nix/tag/v0.7.0/nix-installer-x86_64-linux
`nix-installer` needs to run as `root`, attempting to escalate now via `sudo`...
[sudo] password for jradley: 
Nix install plan (v0.7.0)
Planner: linux (with default settings)

Planned actions:
* Create directory `/nix`
* Fetch `https://releases.nixos.org/nix/nix-2.13.3/nix-2.13.3-x86_64-linux.tar.xz` to `/nix/temp-install-dir`
* Create build users (UID 30000-30032) and group (GID 30000)
* Create a directory tree in `/nix`
* Move the downloaded Nix into `/nix`
* Setup the default Nix profile
* Place the Nix configuration in `/etc/nix/nix.conf`
* Configure the shell profiles
* Configure Nix daemon related settings with systemd
* Remove directory `/nix/temp-install-dir`


Proceed? ([Y]es/[n]o/[e]xplain): y
 INFO Step: Create directory `/nix`
 INFO Step: Provision Nix
 INFO Step: Configure Nix
 INFO Step: Configure Nix daemon related settings with systemd
ERROR 
   0: Install failure
   1: Error executing action `configure_init_service`
   2: Failed to execute command with status 5 `"systemctl" "disable" "nix-daemon.socket" "--now"`, stdout: 
      stderr: Removed "/etc/systemd/system/sockets.target.wants/nix-daemon.socket".
      Removed "/etc/systemd/system/nix-daemon.socket".
      Failed to stop nix-daemon.socket: Unit nix-daemon.socket not loaded.

   2: 

Location:
   /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/convert/mod.rs:726

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.

Consider reporting this error using this URL: https://github.com/DeterminateSystems/nix-installer/issues/new?title=%3Cautogenerated-issue%3E&body=%23%23+Error%0A%60%60%60%0AError%3A+%0A+++0%3A+Install+failure%0A+++1%3A+Error+executing+action+%60configure_init_service%60%0A+++2%3A+Failed+to+execute+command+with+status+5+%60%22systemctl%22+%22disable%22+%22nix-daemon.socket%22+%22--now%22%60%2C+stdout%3A+%0A++++++stderr%3A+Removed+%22%2Fetc%2Fsystemd%2Fsystem%2Fsockets.target.wants%2Fnix-daemon.socket%22.%0A++++++Removed+%22%2Fetc%2Fsystemd%2Fsystem%2Fnix-daemon.socket%22.%0A++++++Failed+to+stop+nix-daemon.socket%3A+Unit+nix-daemon.socket+not+loaded.%0A%0A%0A%60%60%60%0A%0A%23%23+Metadata%0A%7Ckey%7Cvalue%7C%0A%7C--%7C--%7C%0A%7C**version**%7C0.7.0%7C%0A%7C**os**%7Clinux%7C%0A%7C**arch**%7Cx86_64%7C%0A
Installation failure, offering to revert...
Nix uninstall plan (v0.7.0)

Planner: linux (with default settings)

Planned actions:
* Unconfigure Nix daemon related settings with systemd
* Unconfigure the shell profiles
* Remove the Nix configuration in `/etc/nix/nix.conf`
* Unset the default Nix profile
* Remove the directory tree in `/nix`
* Remove Nix users and group
* Remove the directory `/nix`


Proceed? ([Y]es/[n]o/[e]xplain): 

`
`

**Comment by jradxl** [comment]
I hope the above is useful.
I installed the Nix Original installer on Ubuntu Mate 23.04 lobster and was working fine (as a beginner can tell)
I thought then to try your Installer so I removed Nix as per the manual remove  from 
`https://nix-tutorial.gitlabpages.inria.fr/nix-tutorial/installation.html`
But alas, your installer fails, but I don't know why

**Comment by jradxl** [comment]
Success, it worked the second time I ran it
I think I didn't remove any of the systemd stuff as mentioned in
`https://www.tecmint.com/nix-package-manager-for-linux/
`
But it looks like I've got back to what I had

```
$ nix --version
nix (Nix) 2.13.3
```
so I am even more confused than when I started

**Comment by Hoverbear** [comment]
In the future, official uninstall instructions for the script is: https://nixos.org/manual/nix/stable/installation/installing-binary.html#uninstalling, the page you linked (https://nix-tutorial.gitlabpages.inria.fr/nix-tutorial/installation.html) happens to have rather incorrect instructions.

I suspect what happened here is you removed `/nix` which caused the service to start failing, however it was still enabled, so when we sent `disable --now` it could not stop it now and failed. I think we can split that into separate commands and be more intelligent.

Thanks for this report!

I'm glad you got it working, we'll try to have this solved for the next release so others don't face it.
