### ISSUE TITLE
Group `nixbld` existed but had a different gid (3000) than planned (30000) when re-installing on macOS aarch64

### ISSUE THREAD

**Issue by nickgerace** [DeterminateSystems/nix-installer#404]
## Context

I wanted to try out the new installer as well as get the side benefit of having a new `nix` without using `nix upgrade-nix`. Thus, I ran `/nix/nix-installer uninstall` (unsure which version, sadly) and then ran the installer script. However, I hit the error described in the next section.

## Error

```
❯ curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix | sh -s -- install

info: downloading installer https://install.determinate.systems/nix/tag/v0.7.0/nix-installer-aarch64-darwin
`nix-installer` needs to run as `root`, attempting to escalate now via `sudo`...
Password:
Error:
   0: Planner error
   1: Error executing action
   2: Child action `create_users_and_group`
   3: Group `nixbld` existed but had a different gid (3000) than planned (30000)

Location:
   src/cli/subcommand/install.rs:146

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
```

## Metadata
|key|value|
|--|--|
|**version**|0.7.0|
|**os**|macos|
|**arch**|aarch64|

Additional metadata: macOS version `13.0` (`22A380`)

**Comment by nickgerace** [comment]
I presume this is related to the following message displayed during uninstallation: ` WARN `nix-installer` currently cannot delete groups on Mac due to https://github.com/DeterminateSystems/nix-installer/issues/33. This is a no-op, installing with `nix-installer`
again will use the existing user.`

**Comment by nickgerace** [comment]
### Workaround

Alright, I have a workaround, but I _highly_ recommend performing it in two parts because the way I found the users used `grep` and `ripgrep`, which is... a bit scary.

> Yes, I could have used just `grep`, but meh. Old habits die hard.

Short version:

1. Get the names of all the users that you would like to delete.
2. Delete them.

### Step 1/2: Find Users

I used the following command...

```bash
dscl . list /Users | grep -v “^_” | rg nix
```

...to get the following list...

```
_nixbld0
_nixbld1
_nixbld10
_nixbld11
_nixbld12
_nixbld13
_nixbld14
_nixbld15
_nixbld16
_nixbld17
_nixbld18
_nixbld19
_nixbld2
_nixbld20
_nixbld21
_nixbld22
_nixbld23
_nixbld24
_nixbld25
_nixbld26
_nixbld27
_nixbld28
_nixbld29
_nixbld3
_nixbld30
_nixbld31
_nixbld4
_nixbld5
_nixbld6
_nixbld7
_nixbld8
_nixbld9
```

### Step 2/2: Delete Users

I iterated over the list, with each iteration using `OLD_NIX_USER` for each trimmed line of the list about, and performed the following command for each item:

```bash
sudo /usr/bin/dscl . -delete "/Users/$OLD_NIX_USER"
```

**Comment by Hoverbear** [comment]
Thanks for being an early adopter and I'm sorry about this! I'm guessing it was `0.4.0`. Your workaround looks correct!

We have since improved the error message (and in fact, delete the users in almost all cases) so this problem should be fixed.

I suppose we could add some migration ability from these older versions, however our adoption prior to then was pretty small so I'm not sure if the added complexity will be worth it...

**Comment by nickgerace** [comment]
That all sounds good! Whatever you all decide to do is best! :) Hope all is well @Hoverbear

**Comment by Hoverbear** [comment]
Doing great! Learning a lot about how Macs work! :rofl: I'm pretty excited to try #193 soon!

**Comment by Hoverbear** [comment]
CLosing this as I'm not sure what is left to do. Let me know if something changes!
