### ISSUE TITLE
wsl Uninstall error

### ISSUE THREAD

**Issue by kingwill101** [DeterminateSystems/nix-installer#406]
## Error
```
Error: 
   0: Error executing action `configure_init_service`
   1: Remove file `/etc/tmpfiles.d/nix-daemon.conf`
   2: No such file or directory (os error 2)
```

## Metadata
|key|value|
|--|--|
|

**Comment by Hoverbear** [comment]
I'm sorry I need some more information if I'm gonna be able to help!

This was with Systemd enabled in WSL yes? What was the host distro? Ubuntu?

Did you do anything interesting to systemd before uninstalling?

I've tried to reproduce with the available information and not had success. I also had a friend try on their WSL instance and that worked.
