### ISSUE TITLE
Poor messaging around version incompatability with already `nix-installer`'d Nix

### ISSUE THREAD

**Issue by wolfd** [DeterminateSystems/nix-installer#408]
I'm really happy about the existence of this tool! It's filling a big gap in the nix ecosystem, thank you for your hard work!

I'm curious about how I should be using this installer in an environment where I want to ensure that a computer is up-to-date with the expected versions of a number of system tools. For context, I have a setup script that downloads and installs nix and sets up some other system configuration. This script is located in a monorepo that uses nix, and developers run this setup script after updating their current branch.

Since I've been having trouble with the official nix installer, especially on macOS, I attempted to switch over to this one. I naively was using some upgrade logic that checked if `nix-installer` existed, checked its version, and tried installing it again if it differed in version.

Currently what happens is that the installer errors out because the plan file is from a different version:
```
curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix | sh -s -- install
info: downloading installer https://install.determinate.systems/nix/tag/v0.7.0/nix-installer-aarch64-darwin
`nix-installer` needs to run as `root`, attempting to escalate now via `sudo`...
Password:
Error:
   0: This version of `nix-installer` (0.7.0) is not compatible with this plan's version (0.5.0), check for a compatible version at `/nix/nix-installer` or download the matching release from https://github.com/DeterminateSystems/nix-installer/releases at line 2 column 20

Location:
   src/cli/subcommand/install.rs:78

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
```

I think it would be neat if `nix-installer` could make upgrades to installs made by older versions of itself to keep configuration up to date with its currently preferred settings (e.g. enabling flakes by default, etc) that might change in future versions. It might also make sure that it has a minimum version of nix installed that's compatible with the latest release as https://github.com/DeterminateSystems/nix-installer/issues/387 takes note of.

Alternatively, I was wondering what a good workflow might be for ensuring this. Using the uninstall script and reinstalling seems like overkill, but it would theoretically ensure a match in how nix was set up. For updating nix itself, I assume that it should go through normal [`nix-env` means as suggested in the wiki](https://nixos.org/manual/nix/stable/installation/upgrading.html) or by using the ["new" cli's `upgrade-nix` function](https://nixos.org/manual/nix/stable/command-ref/new-cli/nix3-upgrade-nix.html).

**Comment by Hoverbear** [comment]
> Currently what happens is that the installer errors out because the plan file is from a different version:

Yeah we should improve the messaging here... What's happening is the installer is detecting an existing `/nix/receipt.json` and telling you it can't try to resume that install since it's by an old version.

If you'd like to reinstall Nix because it's broken, please run `/nix/nix-installer uninstall` and then reinstall. If you'd like to upgrade Nix, please upgrade it using the articles you linked above!

**Comment by apstanisic** [comment]
I'm not sure if this should be separate issue, or is the same as #35, but it would be cool if there was an option for installer to check if nix is installed successfully, and only do something if nix is not installed or is partially installed.
That would enable simplified ansible task bellow. My current workaround is to run installer only if there is no `/nix` folder
```bash
  - name: Install nix
    shell: curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix | sh -s -- install --no-confirm
    become: true
```

**Comment by Hoverbear** [comment]
It'd be swell if that was separate issue. :) I think having a feature like that is worthwhile.
