### ISSUE TITLE
Cannot connect to socket: Connection refused on Fedora 37

### ISSUE THREAD

**Issue by ziutech** [DeterminateSystems/nix-installer#419]
When using the installer after `sudo setenforce Permissive` everything works fine, but then after reboot running `nix shell nixpkgs#name-of-flake` produces error:
> error: cannot connect to socket at '/nix/var/nix/daemon-socket/socket': Connection refused

**Comment by Hoverbear** [comment]
Could you please tell me the output of `journalctl -u nix-daemon.service`?

**Comment by ziutech** [comment]
> Could you please tell me the output of `journalctl -u nix-daemon.service`?

Sure:

> kwi 16 03:21:43 fedora systemd[1]: Started nix-daemon.service - Nix Daemon.
kwi 16 03:21:43 fedora nix-daemon[15409]: accepted connection from pid 15404, user ziutech
kwi 16 03:29:32 fedora systemd[1]: Stopping nix-daemon.service - Nix Daemon...
kwi 16 03:29:32 fedora systemd[1]: nix-daemon.service: Deactivated successfully.
kwi 16 03:29:32 fedora systemd[1]: Stopped nix-daemon.service - Nix Daemon.
kwi 16 03:29:32 fedora systemd[1]: nix-daemon.service: Consumed 4.736s CPU time.
-- Boot e1782794f6cd4c0093502a27f29bc45e --
kwi 16 04:01:06 fedora systemd[1]: Started nix-daemon.service - Nix Daemon.
kwi 16 04:01:06 fedora nix-daemon[7052]: accepted connection from pid 7049, user ziutech
kwi 16 04:02:44 fedora systemd[1]: Stopping nix-daemon.service - Nix Daemon...
kwi 16 04:02:44 fedora systemd[1]: nix-daemon.service: Deactivated successfully.
kwi 16 04:02:44 fedora systemd[1]: Stopped nix-daemon.service - Nix Daemon.
kwi 16 04:02:44 fedora systemd[1]: nix-daemon.service: Consumed 4.887s CPU time.

**Comment by Hoverbear** [comment]
We now support SELinux, perhaps this would work better for you.

**Comment by ziutech** [comment]
Thank you, now it works flawlessly :sparkles:
