### ISSUE TITLE
How to keep nix updated once installed?

### ISSUE THREAD

**Issue by hydrajump** [DeterminateSystems/nix-installer#421]
Let's say I've installed nix on macOS using `nix-installer` **v0.8.0**.
How do I keep nix updated? Do install again once a newer version of the installer is released?

**Comment by Hoverbear** [comment]
I'd use `nix upgrade-nix` for this! https://nixos.org/manual/nix/stable/command-ref/new-cli/nix3-upgrade-nix.html

**Comment by chewblacka** [comment]
> I'd use `nix upgrade-nix` for this! https://nixos.org/manual/nix/stable/command-ref/new-cli/nix3-upgrade-nix.html

Weirdly when I run `nix upgrade nix` I get:

`error: directory '/nix/var/nix/profiles/default/bin' does not appear to be part of a Nix profile`

and if  I run as root I get:

`error: directory '/root/.nix-profile/bin' does not appear to be part of a Nix profile`

**Comment by chewblacka** [comment]
> I'd use `nix upgrade-nix` for this! https://nixos.org/manual/nix/stable/command-ref/new-cli/nix3-upgrade-nix.html

In which case is this a bug?:

```
# nix upgrade-nix
replacing old 'nix-2.13.3'
installing 'nix-2.13.3'
# nix profile list
0 - - /nix/store/ba4f8msp39cfvfpw3m7fsalb4psw347z-nss-cacert-3.83
1 - - /nix/store/mc43d38fibi94pp5crfwacl5gbslccd0-nix-2.13.3
# nix profile install 'nixpkgs#sl'
# nix profile list
0 - - /nix/store/ba4f8msp39cfvfpw3m7fsalb4psw347z-nss-cacert-3.83
1 - - /nix/store/mc43d38fibi94pp5crfwacl5gbslccd0-nix-2.13.3
2 flake:nixpkgs#legacyPackages.x86_64-linux.sl github:NixOS/nixpkgs/2362848adf8def2866fabbffc50462e929d7fffb#legacyPackages.x86_64-linux.sl /nix/store/54g2bb7i2syhznxqhy7kis76jkficqrg-sl-5.05
nix upgrade-nix
error: directory '/root/.nix-profile/bin' does not appear to be part of a Nix profile
```
Basically installing anything from nixpkgs seems to result in this error.

**Comment by hydrajump** [comment]
Now that nix version 2.15.0 has been released I thought I'd try what you suggested @Hoverbear. Unfortunately, it doesn't work as expected.

```
% nix upgrade-nix
replacing old 'nix-2.13.3'
installing 'nix-2.13.3'
error: opening lock file '/nix/var/nix/profiles/default.lock': Permission denied
error: program '/nix/store/8w0v2mffa10chrf1h66cbvbpw86qmh85-nix-2.13.3/bin/nix-env' failed with exit code 1
```

I tried with `sudo` and got a different error:

```
% sudo nix upgrade-nix
Password:
warning: $HOME ('/Users/test') is not owned by you, falling back to the one defined in the 'passwd' file ('/var/root')
[0.0 MiB DL] warning: $HOME ('/Users/test') is not owned by you, falling back to the one defined in the 'passwd' file ('/var/root')
warning: $HOME ('/Users/test') is not owned by you, falling back to the one defined in the 'passwd' file ('/var/root')
replacing old 'nix-2.13.3'
installing 'nix-2.13.3'
```

I'm not sure why it installed the same version. Maybe updating nix on macOS is broken?

**Comment by Hoverbear** [comment]
Sadly the `nix-fallback-paths.nix` describved in https://nixos.org/manual/nix/stable/command-ref/new-cli/nix3-upgrade-nix.html#description is not yet updated: https://raw.githubusercontent.com/NixOS/nixpkgs/master/nixos/modules/installer/tools/nix-fallback-paths.nix

**Comment by Hoverbear** [comment]
@chewblacka I think you may have found some hiccup. I'll investigate.

**Comment by Hoverbear** [comment]
I was fiddling with this today and it seems to be working alright. We've made some changes on `main` since last release so that may be related. I'm closing this for now as I'm not able to nail down anything concrete to fix in this issue. Please reopen if we get something!
