### ISSUE TITLE
Equivalent of `nix-env -u`? (Or: How do I update all packages?)

### ISSUE THREAD

**Issue by hraban** [DeterminateSystems/nix-installer#424]
How do I update all packages installed through nix-env? I don't see any channels, so my usual approach of `nix-channel --update` doesn't work.

Thanks for the installer.

(system: apple silicon, mac ventura)

**Comment by grahamc** [comment]
Hey @hraban,

Since we set `extra-nix-path` to `nixpkgs=flake:nixpkgs`, your `nixpkgs` is always moving forward as upstream releases. You should be able to "just" run `nix-env -u` if that is what you were doing before. Have you tried that?
