### ISSUE TITLE
Specify nix version

### ISSUE THREAD

**Issue by dezren39** [DeterminateSystems/nix-installer#426]
hi i tried to find an answer but couldn't,

I have an app that needs, i want to say 2.15, but this installed 2.14 something when i used it. when I use the normal install i get 2.15. I'm guessing there is a small delay before this installer pulls a new version? Can I specify the nix version? I don't think the app i'm looking at really needs any features beyond .14 tbh, but I am not in a position to change their code right now.

**Comment by dezren39** [comment]
looking back, in my case maybe i could have ran `nix upgrade-nix` after your installer wraps up? at least since i'm looking for just 'something newer', but i'm also curious if the version can be specified in case i need to use that down the line. maybe the nix version is part of the installer and so this is actually not something i should expect? in that case I should just wait for mainline to catch up or temporarily fork if i need to change it?

**Comment by teto** [comment]
this is a concern I have to `sh ./nix-rust-installer.sh install --help`. Why can't the installer support arbitrary nix install ?
I've tried `sh ./nix-rust-installer.sh install --nix-package-url https://releases.nixos.org/nix/nix-2.15.0/nix-2.15.0-x86_64-linux.tar.xz` and looks like it worked.

**Comment by Hoverbear** [comment]
> Why can't the installer support arbitrary nix install ?

It can, we just can't promise compatability if you use say, a very new version of this installer with a very old version of Nix. We try to keep it up to date. We're trying to figure out how to best handle this in #387 which you linked.

**Comment by Hoverbear** [comment]
@dezren39 We didn't upgrade to 2.14 because 2.14 was broken. The upstream installer rolled back to serving 2.13 and 2.14 wasn't very widely distributed.

**Comment by dezren39** [comment]
Thank you# closing
