### ISSUE TITLE
stability of installer uri https://install.determinate.systems/nix/tag/v0.8.0/nix-installer-x86_64-linux

### ISSUE THREAD

**Issue by teto** [DeterminateSystems/nix-installer#429]
I've frenetically tried the installer with different flags and all. I am impressed by how fast it was compared to the official nix installer (it was so fast I thought it bugged and nooped but no `nix --version` worked !). The advised command was taking most of the time: 
`curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix | sh -s -- install`
so instead in my script I am tempted to download https://install.determinate.systems/nix/tag/v0.8.0/nix-installer-x86_64-linux directly. My concern is: is that uri supposed to be stable ? Can I use it in an enterprise setting ?

Cheers

**Comment by Hoverbear** [comment]
It's the plan to keep it stable! You can also snag it from https://github.com/DeterminateSystems/nix-installer/releases, or if you know you'll have a Rust toolchain you can `cargo install` it from crates.io which would be suitable for enterprise, as it can't be taken down (even if we wanted to!)

**Comment by teto** [comment]
cool ty
