### ISSUE TITLE
error uninstalling nix on WSL2-based distro

### ISSUE THREAD

**Issue by klauern** [DeterminateSystems/nix-installer#430]
## Error
```
Error: 
   0: Error reverting
   0: Action `configure_init_service` errored
      Failed to execute command with status 1 `"systemctl" "daemon-reload"`, stdout: 
      stderr: System has not been booted with systemd as init system (PID 1). Can't operate.
      Failed to connect to bus: Host is down
```

## Metadata
|key|value|
|--|--|
|**version**|0.8.0|
|**os**|linux|
|**arch**|x86_64|

I didn't see the instructions for installing [Nix in WSL2](https://github.com/DeterminateSystems/nix-installer#in-wsl2) until I had already run the top-most command, so it prompted me to uninstall and failed.  I think the uninstall was successful, as I was able to install it correctly.

**Comment by Hoverbear** [comment]
Thanks for reporting this! It looks like you have already solved the issue, so closing it.
