### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by bhanucpp** [DeterminateSystems/nix-installer#432]
root@DESKTOP-F99K0KT:~/elevate-devops/kubernetes/env-dev-staging# ./k9s.sh
error: getting attributes of path '/run/user/0/nix-build-remove-references-to.drv-0': Permission denied
(use '--show-trace' to show detailed location information)
error: getting attributes of path '/run/user/0/nix-build-remove-references-to.drv-0': Permission denied
(use '--show-trace' to show detailed location information)
W0427 14:09:43.097159    1361 loader.go:223] Config not found: /root/elevate-devops/kubernetes/env-dev-staging/.kubeconfig
The connection to the server localhost:8080 was refused - did you specify the right host or port?

**Comment by Hoverbear** [comment]
I believe you may have reported this to the wrong repository.
