### ISSUE TITLE
Sandboxing issue during boxwolfi build

### ISSUE THREAD

**Issue by tulilirockz** [DeterminateSystems/nix-installer#435]
## Error
```
Error: 
   0: Install failure
   1: Error executing action
   2: Action `configure_nix` errored
   3: Action `setup_default_profile` errored
   4: Failed to execute command with status 1 `HOME="/root" NIX_SSL_CERT_FILE="/nix/store/ba4f8msp39cfvfpw3m7fsalb4psw347z-nss-cacert-3.83/etc/ssl/certs/ca-bundle.crt" "/nix/store/mc43d38fibi94pp5crfwacl5gbslccd0-nix-2.13.3/bin/nix-env" "-i" "/nix/store/mc43d38fibi94pp5crfwacl5gbslccd0-nix-2.13.3"`, stdout: 
      stderr: installing 'nix-2.13.3'
      error: cannot set host name: Operation not permitted
      (use '--show-trace' to show detailed location information)


```

## Metadata
|key|value|
|--|--|
|**version**|0.8.0|
|**os**|linux|
|**arch**|x86_64|

**Comment by tulilirockz** [comment]
Happened when trying to build [this image](https://github.com/nunix/boxwolfi/tree/main), to be honest, I don't have any idea why?

**Comment by Hoverbear** [comment]
I believe this is coming from sandboxing, Nix tries to change your hostname to something generic. Please do `nix-installer install linux --extra-conf "sandbox = false"` and see if that helps?

**Comment by Hoverbear** [comment]
(Closing this since we have no response and the suggestion should work, please reopen if you come back to it!)
