### ISSUE TITLE
Install (with init) fails if cannot run `systemctl daemon-reload`

### ISSUE THREAD

**Issue by carnage-mode** [DeterminateSystems/nix-installer#436]
## Error
```
Error: 
   0: Install failure
   1: Error executing action
   2: Action `configure_init_service` errored
   3: Failed to execute command with status 1 `"systemctl" "daemon-reload"`, stdout: 
      stderr: Failed to reload daemon: Access denied


```

## Metadata
|key|value|
|--|--|
|**version**|0.8.0|
|**os**|linux|
|**arch**|x86_64|

**Comment by Hoverbear** [comment]
Hi! Does root not have have the ability to run `systemctl daemon-reload` on your machine?

**Comment by carnage-mode** [comment]
Yes

**Comment by Hoverbear** [comment]
Could you tell me which OS you're running and more about this situation?

**Comment by carnage-mode** [comment]
I'm running it on Fedora Silverblue. I'll try to install it again and see if it works this time.

**Comment by carnage-mode** [comment]
That's unfortunate. Could you document distros you don't support? This may help you avoid future bug reports.
