### ISSUE TITLE
Can't install nix issue

### ISSUE THREAD

**Issue by nikivdev** [DeterminateSystems/nix-installer#447]
## Error
```
Error: 
   0: Planner error
   1: Error executing action
   2: Action `encrypt_apfs_volume` errored
   3: The keychain lacks a password for the already existing "Nix Store" volume on disk `disk3`, consider removing the volume with `diskutil apfs deleteVolume "Nix Store"` (if you receive error -69888, you may need to run `launchctl bootout system/org.nixos.darwin-store` and `launchctl bootout system/org.nixos.nix-daemon` first)
```

## Metadata
|key|value|
|--|--|
|**version**|0.8.0|
|**os**|macos|
|**arch**|aarch64|

As image looks like this:

<img width="1500" alt="image" src="https://user-images.githubusercontent.com/6391776/236257093-e2b2c64b-d5ba-4d00-b620-9bb254416946.png">

**Comment by Hoverbear** [comment]
Hi!

Consider removing the volume with `diskutil apfs deleteVolume "Nix Store"`

(if you receive error -69888, you may need to run `launchctl bootout system/org.nixos.darwin-store` and `launchctl bootout system/org.nixos.nix-daemon` first)

Let me know if that doesn't work for you.
