### ISSUE TITLE
Install started failing randomly

### ISSUE THREAD

**Issue by gkze** [DeterminateSystems/nix-installer#450]
## Error
```
Error: 
   0: Install failure
   1: Error executing action
   2: Action `configure_init_service` errored
   3: Copying file `/nix/var/nix/profiles/default/Library/LaunchDaemons/org.nixos.nix-daemon.plist` to `/Library/LaunchDaemons/org.nixos.nix-daemon.plist`
   4: No such file or directory (os error 2)
```

## Metadata
|key|value|
|--|--|
|**version**|0.8.0|
|**os**|macos|
|**arch**|aarch64|

## Notes
Completely removed Nix from my system to the best of my knowledge (`~/.nix*`, `/etc/nix*`, deleted `/nix` volume) and tried again but with the same result.

**Comment by Hoverbear** [comment]
That's a bit odd. In the issue title you say "started failing randomly", was it working previously?

Hmm.... Does `/Library/LaunchDaemons/` exist?

If you already took the revert step, could you try again and before reverting again.... does `/nix/var/nix/profiles/default/Library/LaunchDaemons/` or `/nix/var/nix/profiles/default/Library/` exist?

**Comment by evanrichter** [comment]
@gkze if you want to be more thorough in your uninstall steps, this should be everything you need to do: https://github.com/NixOS/nix/blob/master/doc/manual/src/installation/uninstall.md#macos

**Comment by gkze** [comment]
Thank you for the quick turnaround folks! Turns out it was the leftover fstab entry.

I know it's kind of an unresolved topic in the community but curious to hear any thoughts on automating the uninstall process?

**Comment by Hoverbear** [comment]
With a `nix-installer` installed (or cured!) install, you can run `/nix/nix-installer uninstall` to get rid of Nix (including the stuff the official scripts might have set)

**Comment by gkze** [comment]
Got it, thank you! That Uninstall section in the manual was super helpful too. 👍🏻
