### ISSUE TITLE
Only install nix if not already installed

### ISSUE THREAD

**Issue by apstanisic** [DeterminateSystems/nix-installer#453]
It would be cool if there was an option for installer to check if nix is installed successfully, and only do something if nix is not installed or is partially installed.
That would enable simplified ansible task bellow. My current workaround is to run installer only if there is no `/nix` folder
```bash
  - name: Install nix
    shell: curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix | sh -s -- install --no-confirm
    become: true
```

**Comment by Hoverbear** [comment]
#454 should address your issue but due to things like #408 I suggest pinning your version:

```
curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix/tags/v0.8.0 | sh -s -- install --no-confirm
```

And upgrading manually.
