### ISSUE TITLE
Improve detection of WSL installs without Systemd

### ISSUE THREAD

**Issue by pingiun** [DeterminateSystems/nix-installer#462]
I used the installer on a fresh WSL installation of Ubuntu. The installer seems to run fine, however when I want to use a `nix run` command afterwards, I get the following error:

```
error: could not set permissions on '/nix/var/nix/profiles/per-user' to 755: Operation not permitted
```

I have not configured WSL to use systemd but the installer did say "INFO Step: Configure Nix daemon related settings with systemd". This may be related to an issue I filed earlier about not detecting systemd correctly?

**Comment by pingiun** [comment]
Just to be clear, I tried this:

```
sudo chmod 755 /nix/var/nix/profiles/per-user
```

Which didn't fix the issue, it still gives the same error

**Comment by pingiun** [comment]
I setup systemd in /etc/wsl.conf, rebooted, reinstalled nix and now the issue is gone

**Comment by Hoverbear** [comment]
I'm glad you got it! Perhaps we should do more validation of WSL environments in our planner...

**Comment by Hoverbear** [comment]
Related to https://github.com/DeterminateSystems/nix-installer/pull/336

**Comment by Hoverbear** [comment]
![image](https://github.com/DeterminateSystems/nix-installer/assets/130903/02c5eb9c-2010-4272-a1e8-78dc5ca24b6a)
Confirming this issue. I think the solution in https://github.com/DeterminateSystems/nix-installer/pull/336/files#r1153191998 is probably right.
