### ISSUE TITLE
Keychain already populated with key and cannot be removed

### ISSUE THREAD

**Issue by bhagya7893** [DeterminateSystems/nix-installer#463]
## Error
```
Error: 
   0: Planner error
   1: Error executing action
   2: Action `encrypt_apfs_volume` errored
   3: The keychain has an existing password for a non-existing "Nix Store" volume on disk `disk3`, consider removing the password with `security delete-generic-password  -a "Nix Store" -s "Nix Store" -l "disk3 encryption password" -D "Encrypted volume password"`
```

## Metadata
|key|value|
|--|--|
|**version**|0.8.0|
|**os**|macos|
|**arch**|aarch64|

**Comment by rch** [comment]
Additional context: the error still occurs on re-install after executing the recommended command.

**Comment by Hoverbear** [comment]
Did this machine have a pre-existing Nix install? Could you run 

```bash
security find-generic-password -a "Nix Store" -s "Nix Store"
```

For me?

We need to remove that key.

**Comment by bhagya7893** [comment]
keychain: "/Library/Keychains/System.keychain"
version: 256
class: "genp"
attributes:
    0x00000007 <blob>="disk3 encryption password"
    0x00000008 <blob>=<NULL>
    "acct"<blob>="Nix Store"
    "cdat"<timedate>=0x32303233303530343137333833365A00  "20230504173836Z\000"
    "crtr"<uint32>=<NULL>
    "cusi"<sint32>=<NULL>
    "desc"<blob>="Encrypted volume password"
    "gena"<blob>=<NULL>
    "icmt"<blob>="Added automatically by the Nix installer for use by /Library/LaunchDaemons/org.nixos.darwin-store.plist"
    "invi"<sint32>=<NULL>
    "mdat"<timedate>=0x32303233303530343137333833365A00  "20230504173836Z\000"
    "nega"<sint32>=<NULL>
    "prot"<blob>=<NULL>
    "scrp"<sint32>=<NULL>
    "svce"<blob>="Nix Store"
    "type"<uint32>=<NULL>

**Comment by Hoverbear** [comment]
Please run `security delete-generic-password  -a "Nix Store" -s "Nix Store"` then try again?

**Comment by rch** [comment]
I'll update -- Running with security delete-generic-password  -a "Nix Store" -s "Nix Store":

`security delete-generic-password -a "Nix Store" -s "Nix Store"`

```
keychain: "/Library/Keychains/System.keychain"
version: 256
class: "genp"
attributes:
...
  "acct"<blob>="Nix Store"
  "cdat"<timedate>=0x32303233303530343137333833365A00 "20230504173836Z\000"
  "crtr"<uint32>=<NULL>
  "cusi"<sint32>=<NULL>
  "desc"<blob>="Encrypted volume password"
  "gena"<blob>=<NULL>
  "icmt"<blob>="Added automatically by the Nix installer for use by /Library/LaunchDaemons/org.nixos.darwin-store.plist"
  "invi"<sint32>=<NULL>
  "mdat"<timedate>=0x32303233303530343137333833365A00 "20230504173836Z\000"
  "nega"<sint32>=<NULL>
  "prot"<blob>=<NULL>
  "scrp"<sint32>=<NULL>
  "svce"<blob>="Nix Store"
  "type"<uint32>=<NULL>
password has been deleted.
```

It says `password deleted` but when installing nix there's still get the same error.

**Comment by Hoverbear** [comment]
Does it still exist maybe? Apple's tooling often straight out lies or misbehaves...

```bash
security find-generic-password -a "Nix Store" -s "Nix Store"
```

**Comment by rch** [comment]
Yes, output of that command is in a comment above.

Maybe the uninstall should confirm that the key was removed, and if not, then inform the user that it will be necessary to remove it manually.

**Comment by Hoverbear** [comment]
So even after running `security delete-generic-password -a "Nix Store" -s "Nix Store"`, the output of `security find-generic-password -a "Nix Store" -s "Nix Store"` was the same as in https://github.com/DeterminateSystems/nix-installer/issues/463#issuecomment-1546189930 ?

This implies the key was not removed. Can the user not remove keys from the keychain?

**Comment by Hoverbear** [comment]
In another issue we found that if the keychain has muiltiple keys on it, it will act like this and make it feel like the user hasn't deleted the key. We need to change the error message.

**Comment by Hoverbear** [comment]
I think this is fixed now!
