### ISSUE TITLE
Add  $HOME/.nix-profile/bin to GHA path

### ISSUE THREAD

**Issue by Hoverbear** [DeterminateSystems/nix-installer#475]
Ref https://github.com/cachix/cachix-action/issues/146

**Comment by Hoverbear** [comment]
I'm curious why this code wasn't firing?

https://github.com/DeterminateSystems/nix-installer/blob/79a32a7c668af6936f272960dbab80b05019bd16/src/action/common/configure_shell_profile.rs#L151-L170

**Comment by Hoverbear** [comment]
Okay it may be that the user already had nix installed (??) and we weren't adding the profile to the path in https://github.com/DeterminateSystems/nix-installer-action/pull/22

**Comment by shyim** [comment]
That script will not work when the username is different (self-hosted runner). Maybe thats the problem?
