### ISSUE TITLE
Building without experimental features enabled

### ISSUE THREAD

**Issue by mkenigs** [DeterminateSystems/nix-installer#476]
I was poking around about how to build an installer without experimental features enabled, but I wanted to check in with @Hoverbear before trying to change anything.

Here was an approach I came up with:
- Add a `nix-community` or `no-experimental` feature
- Add `extra_typed_conf` or `experimental_features` to `CommonSettings`. Set it's value in `CommonSettings::default` depending on the value of the feature above
- Pass the added setting to `PlaceNixConfiguration::plan`

Let me know what you think!

**Comment by Hoverbear** [comment]
We spoke a bit today during the Installer WG! (Always a pleasure!)

As we discussed with @abathur, removing our use of Nix's experimental features would likely require very considerable code changes. It may be wise to carefully choose which of these features we disable and weigh their cost of maintenance.

For example, when we added auto UID allocation we were able to remove a considerable amount of code from the installer that represented the bulk of the complexity of the codebase. It would be extremely unfortunate to need to add that back, as we'd all like install have the least complexity possible... Especially around something with so many failure modes as user creation.

`extra_typed_conf` is likely unnecessary as `extra-conf` is typed and can take multiple instances (`--extra-conf "experimental-features = flakes" --extra-conf "auto-uid-allocation = true"` is valid). If it's not sufficient, let's make it sufficient instead!

We discussed a bit on the call about having separate planners for this purpose, but it's quite possible we could instead have different options for the default settings -- so long as the codebases don't drift much. (Eg https://github.com/NixOS/experimental-nix-installer could have a different `CommonSettings` than this repo, but nothing else particularly different, or even that this repo has a `nix-community` build flag that opts for a more conservative default settings)

I do think it is realistic to assume that over time we may have some drift between specifics of certain actions within https://github.com/NixOS/experimental-nix-installer and this repo, but if we keep the interfaces (eg `Action` and `Planner`) the same, it should be fairly easy to work together even if these differences come. :blush:

**Comment by mkenigs** [comment]
I think my vote would be to add a `nix-community` build flag and use it to adjust `CommonSettings` for this issue, because it would mean the least amount of drift. And adding multiple planners (linux-community and darwin-community) seems like it would be duplicative, since settings should be shared between them.

But I think any of the alternatives you mentioned would work, and since you're the maintainer, I think it's up to you! Let me know!

**Comment by Hoverbear** [comment]
I think at least in the current case... It depends mostly on if we can keep `auto-uid-allocation`!

If we can, then just having differing `CommonSettings` in https://github.com/NixOS/experimental-nix-installer may be sufficient. We could make some changes that allowed for most of the nix.conf we set to be configured by those `CommonSettings`.

But if we have to turn that off, then user creation code would need to be re-introduced, and that would mean the nix-org repo would need to have different planners which included that code.

**Comment by mkenigs** [comment]
Okay but either way you want the changes in https://github.com/NixOS/experimental-nix-installer ?

**Comment by Hoverbear** [comment]
I worry that about some future we will want to adopt something similar to `auto-uid-allocation` (Perhaps `auto-group-allocation`) and want to delete some code but be unable to because of this `nix-community` build time flag.

It really depends on what changes this `nix-community` flag wants to make. For example, we don't provision `$HOME/.nix-channel` and if the

**Comment by mkenigs** [comment]
Ok makes sense! Thanks! I'll make changes in https://github.com/NixOS/experimental-nix-installer

**Comment by Hoverbear** [comment]
Please let me know if you bump into anything we could change to make it easier to share code or work together in the future! I'd like to try to keep things aligned where we can. :)

**Comment by mkenigs** [comment]
Will do! I'll ping you on https://github.com/NixOS/experimental-nix-installer PRs
