### ISSUE TITLE
Investigate more flexible/robust way to handle GITHUB_PATH

### ISSUE THREAD

**Issue by Hoverbear** [DeterminateSystems/nix-installer#485]
We're pretty unhappy with https://github.com/DeterminateSystems/nix-installer/pull/482 being locked to the `runner` user and just overall how that is working. The GITHUB_PATH modifications should be able to work in the presence of a user not named `runner`.

In order to do this, we'd need to either:

* Bring `$USER` through escalation -- Though this kind of violates our library bounds too
* Introduce a new configuration option the GHA automatically sets
* Add a new subcommand to `nix-installer` that sets the Github path... Eg `nix-installer gha set-path $GITHUB_PATH`?
  + This command could skip elevation and operate as the user... A similar strategy might be employed for fixing macs after an update mucks their zshrc.

**Comment by cole-h** [comment]
Nit: if we're bringing anything (more) through escalation, it'd probably be better to bring `$HOME`, in case e.g. a self-hosted runner has a non-standard home dir like `/var/lib/runner` -- but also it would be nice to not need to smuggle more things through escalation by looking at one of the other options first...

**Comment by Hoverbear** [comment]
The more I think about this the more I think a `gha` subcommand makes the most sense...

**Comment by Hoverbear** [comment]
With https://github.com/DeterminateSystems/nix-installer-action/pull/34 these settings are the responsibility of the action, and also no longer specific to `runner`. I think this can be closed.
