### ISSUE TITLE
Improve messaging when `/nix/receipt.json` is already found.

### ISSUE THREAD

**Issue by rossng** [DeterminateSystems/nix-installer#488]
Just got this error while re-running the Nix installer after the macOS update to Ventura 13.4.

## Error
```
Error: 
   0: This version of `nix-installer` (0.8.0) is not compatible with this plan's version (0.7.0), check for a compatible version at `/nix/nix-installer` or download the matching release from https://github.com/DeterminateSystems/nix-installer/releases at line 2 column 20
```

## Metadata
|key|value|
|--|--|
|**version**|0.8.0|
|**os**|macos|
|**arch**|aarch64|

**Comment by rossng** [comment]
I was able to run `curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix/tag/v0.7.0 | sh -s -- install` (specifying the version myself) to run without a crash. I guess this isn't a bug per-se but there's probably a nicer UX possible around this scenario.

**Comment by Hoverbear** [comment]
It sounds like you had some existing plan at `/nix/receipt.json` which it was automatically picking up. It should have suggested you uninstall then reinstall if your nix wasn't working for some reason.

Thanks!

**Comment by rossng** [comment]
Yes, that's correct. 

What happened to me here is that macOS updates have an annoying tendency to remove the Nix config from your `~/.zshrc` file, for which I guess [this is a better fix](https://discourse.nixos.org/t/nix-commands-missing-after-macos-12-1-version-upgrade/16679) as opposed to reinstalling.

Perhaps this would be considered outside scope for `nix-installer`, but it would be awesome if there was a way to detect this issue and repair it automatically without either a) a full reinstall or b) the user manually figuring out how to fix the issue.

In any case, thanks for your work on this project - I've really appreciated it so far.

**Comment by Hoverbear** [comment]
We've been discussing something like a `/nix/nix-installer macos cure-shell` command or something which might do this but we haven't really fleshed anything out.
