### ISSUE TITLE
0.9.1 and nix-darwin

### ISSUE THREAD

**Issue by bestlem** [DeterminateSystems/nix-installer#507]
nix-darwin in its install gives the error
`error: Using the nix-daemon requires build users, aborting activation
Create the build users or disable the daemon:`

From your 0.9.0 Releas notes 

> 2.15 includes the new auto-allocate-uids feature! While we still need to create a system group, This removes a significant portion of the installer complexity, especially on Mac. It also makes things a bit faster:

I guess that means you removed the build users.

Is there a way to get nix-darwin working with your install. 0.8.0 worked.

**Comment by cole-h** [comment]
Funny enough, I just ran into this myself.

You can try out my branch: https://github.com/LnL7/nix-darwin/pull/681

**Comment by emilazy** [comment]
Oh, I was excited to have a Darwin installation option that doesn't need to make new accounts, as the users have caused issues on macOS in the past. Were there other problems or is it just this one thing? The check was patched to be disableable upstream and I think there's an argument for defaulting it off if it's the only motivation to skip `auto-allocate-uids` here.

**Comment by Hoverbear** [comment]
Sadly MacOS doesn't offer enough ability to make things like `whoami` not fail it seems. Related issue is https://github.com/DeterminateSystems/nix-installer/issues/521.
