### ISSUE TITLE
Update nix to a newer version

### ISSUE THREAD

**Issue by shyim** [DeterminateSystems/nix-installer#508]
Hey,

the nix version right now is 2.13.3, I would like to use 2.16.1, but the official docs are not working with this installer :)
https://nixos.org/manual/nix/stable/installation/upgrading.html

What is the recommended way to update nix?

**Comment by bodazhao** [comment]
Personally I use `sudo nix upgrade-nix`

See https://nixos.org/manual/nix/stable/command-ref/new-cli/nix3-upgrade-nix.html

**Comment by sbellem** [comment]
Just in case that helps the issue ... also struggling to upgrade `nix`:

Without `sudo`; getting a permission denied error:
```
$ nix upgrade-nix
replacing old 'nix-2.13.3'
installing 'nix-2.15.1'
building '/nix/store/07rwkrxfd5v9b07zv3ljl0lddadqdn0a-user-environment.drv'...
error: opening lock file '/nix/var/nix/profiles/default.lock': Permission denied
error: program '/nix/store/mc43d38fibi94pp5crfwacl5gbslccd0-nix-2.13.3/bin/nix-env' failed with exit code 1
```

With sudo; `nix` command cannot be found:
```
$ sudo nix upgrade-nix
sudo: nix: command not found
```

**Comment by shyim** [comment]
That seems to install 2.15.1 instead of 2.16.1

**Comment by Hoverbear** [comment]
That is the version currently chosen to be blessed by the Nix release process at this moment.

**Comment by cole-h** [comment]
FWIW, the Nix version that gets installed by `nix upgrade-nix` comes from here: https://github.com/NixOS/nixpkgs/blob/287f80473e226cb184e55a4fbe09c29d01752aae/nixos/modules/installer/tools/nix-fallback-paths.nix (which is indeed 2.15.1).

**Comment by sbellem** [comment]
> `sudo -i nix upgrade-nix` should work!

I get `nix command not found` some similar error. For the time being I installed nix the as per https://nixos.org/manual/nix/stable/installation/installing-binary.html, and added `experimental-features = nix-command flakes` in `~/.config/nix/nix.conf` to use flakes.

I like this tool, and will try it again at some point.

I am wondering if some files from my previous installation are causing the problem. For "standard" installations, I remove `nix`  this way:

```
sudo rm -rf /nix/ .nix-* .local/state/nix/ .cache/nix .config/nix .config/nixpkgs/ 
```

**Comment by Hoverbear** [comment]
0.10.0 now installs Nix 2.15!

**Comment by maacl** [comment]
I just ran the installer and tried to upgrade and got the below:

❯ sudo -i nix upgrade-nix
[sudo] password for mac:
zsh:1: command not found: nix

I am on Ubuntu under WSL.
