### ISSUE TITLE
Script hosted on https://install.determinate.systems/nix is outdated

### ISSUE THREAD

**Issue by COLAMAroro** [DeterminateSystems/nix-installer#510]
Like said in the title, the URL shown in the readme offers an out of date script.

Using this URL on a brand new RHEL 9 fails because of SELinux. It was fixed in #124 and using the script from the release page worked without issue.

**Comment by Hoverbear** [comment]
Hi! 0.9.1 is under limited rollout at the moment, as we're testing the `auto-uid-allocation` feature. (There are some now-known problems on Mac!) Sorry about the issue.

You can force it to use that branch with:

```bash
curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix/tag/v0.9.1 | sh -s -- install
```
