### ISSUE TITLE
Potential build issues with `auto-allocate-uids` enabled by default on macOS

### ISSUE THREAD

**Issue by nanzhong** [DeterminateSystems/nix-installer#521]
I recently ran into a build issue with `auto-allocate-uids` on macOS that took me a while to realize that this experimental feature was the source of the problem.

When building the `emacs` packages (and all variants of it in nixpkgs) the build would hang on one part of the build phase. [https://github.com/NixOS/nixpkgs/issues/238087#event-9558331478](https://github.com/NixOS/nixpkgs/issues/238087) has more details of the build issue.

What ultimately made we wonder if `auto-allocate-uids` was at fault was that when I used `nix develop` and manually run through the phases (unpack, autoreconf, configure, build), I did not seem to hit the problem.

Although I have been able to reproduce this on two different Macs (both of which were fresh installs), I wonder if this could be specific to my environment. I do not have any other Macs to test with, so if someone else could try to reproduce this that would be great. It should be reproducible by having `auto-allocate-uids` enabled and building emacs (`nix build github:nixos/nixpkgs#emacs --rebuild --print-build-logs`). 

So far I have only noticed this with the `emacs` package, and only because I use the emacs-overlay which does not have any cached builds for darwin (which is what led me to realize this was masked by the version in nixpkgs which does have cached builds).

If this is indeed the issue, would disabling `auto-allocate-uids` for macOS until this is resolved be something worth exploring?

**Comment by Hoverbear** [comment]
Hi! Yes we're working on disabling auto-allocate-uids on Mac since it is broken.
