### ISSUE TITLE
nix-installer v0.10.0 fails when installing Nix 2.15.0 in Alpine Linux container in Proxmox 8.0.3.

### ISSUE THREAD

**Issue by derekmahar** [DeterminateSystems/nix-installer#539]
`nix-installer` v0.10.0 fails when installing Nix 2.15.0 in Alpine Linux container.

```
curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix/tag/v0.10.0 |
  sh -s -- install linux --init none
```

## Error
```
Error: 
   0: Install failure
   1: Error executing action
   2: Action `configure_nix` errored
   3: Action `setup_default_profile` errored
   4: Failed to execute command with status 1 `HOME="/root" NIX_SSL_CERT_FILE="/nix/store/ba4f8msp39cfvfpw3m7fsalb4psw347z-nss-cacert-3.83/etc/ssl/certs/ca-bundle.crt" "/nix/store/556bgbl9z8jm7030g1b31d0cblf09036-nix-2.15.0/bin/nix-env" "-i" "/nix/store/556bgbl9z8jm7030g1b31d0cblf09036-nix-2.15.0"`, stdout: 
      stderr: installing 'nix-2.15.0'
      [31;1merror:[0m setting uid: [35;1mInvalid argument[0m
      error: cannot kill processes for uid '872415232': failed with exit code 1


```

## Metadata
|key|value|
|--|--|
|**version**|0.10.0|
|**os**|linux|
|**arch**|x86_64|

```
$ uname -a
Linux alpine-1 6.2.16-3-pve #1 SMP PREEMPT_DYNAMIC PVE 6.2.16-3 (2023-06-17T05:58Z) x86_64 Linux
```

**Comment by Hoverbear** [comment]
Hmm this may be related to `auto-allocate-uids`. I'll try to reproduce it. It may require some fix upstream.

**Comment by bketelsen** [comment]
same error for LXD containers

**Comment by derekmahar** [comment]
> same error for LXD containers

The Alpine Linux container in which I tried to run nix-installer is an LXD container.

**Comment by manan-gup** [comment]
Same for an ArchLinux container using Distrobox with "--init" flag.

**Comment by nexhub** [comment]
I've got the same error on a Proxmox 6.4 host with an Ubuntu 20.04 guest, installer 0.10.0.

**Comment by Hoverbear** [comment]
Does it work if you pass `--extra-conf "sandbox = false"` ? I wonder if it's sandboxing...

**Comment by derekmahar** [comment]
Does #638 resolve this issue?

**Comment by derekmahar** [comment]
> Does #638 resolve this issue?

nix-installer 0.14.0 successfully installed Nix 2.18.1 in my Alpine Linux container.

**Comment by manan-gup** [comment]
The installation works in containers now but if I try anything after that, like using the `nix run` command with a package, it gives me a "No space left on device" error. Both with and without an init system. Don't know what I'm doing wrong.

**Comment by derekmahar** [comment]
> The installation works in containers now but if I try anything after that, like using the `nix run` command with a package, it gives me a "No space left on device" error. Both with and without an init system. Don't know what I'm doing wrong.

That's strange.  Are you running Nix inside a container, like Alpine Linux, that [doesn't use systemd](https://github.com/DeterminateSystems/nix-installer#without-systemd-linux-only)?  In such containers, you must run Nix using `sudo nix`.

**Comment by manan-gup** [comment]
I tried in an Alpine and also an Arch container. I did use sudo when there was no init system but got the same error. The error without sudo is about permissions and not device storage.

**Comment by manan-gup** [comment]
I'm getting this error with nix-installer on my host OS as well. I also used the official nix bash installation script
and I'm getting similar storage related errors. There's more than 50 GB free on my system, so, I'm stumped here.

On running `nix run nixpkgs#hello` I get something like:
```
error:
       … while fetching the input 'github:NixOS/nixpkgs/nixpkgs-unstable'

       error: creating directory '/nix/store/tmp-3165-0/x/pkgs/tools/misc/sl': No space left on device
```
I guess I should ask about this at a more appropriate forum but any help is appreciated.

**Comment by derekmahar** [comment]
Is it possible that your root partition or specifically `/nix` is mapped to a different device or volume that is full?

**Comment by Hoverbear** [comment]
If you're facing this issue with the official bash scripts as well, could I invite you to open an issue on the Nix repo? :)

**Comment by manan-gup** [comment]
Yeah sure. I'll do it tomorrow. Night time here. 🙂
