### ISSUE TITLE
Cannot force an encrypted volume on macOS

### ISSUE THREAD

**Issue by alexpearce** [DeterminateSystems/nix-installer#543]
If I set `--encrypt true` the APFS volume isn't actually encrypted:

```
$ ./nix-installer install macos --encrypt true
<snip>
Configured settings:
* root_disk: null
* volume_encrypt: true

Planned actions:
* Create an APFS volume `Nix Store` for Nix on `disk3` and add it to `/etc/fstab` mounting on `/nix`
<snip>
```

I'd [expect](https://github.com/DeterminateSystems/nix-installer/blob/35864576243828e0383aaee86805865ea7271ca0/src/action/macos/create_nix_volume.rs#L130) the plan to read "Create an encrypted volume…" but it doesn't.

Reading the code it looks like setting the `--encrypt` flag at all disables encryption, regardless of its value:

https://github.com/DeterminateSystems/nix-installer/blob/35864576243828e0383aaee86805865ea7271ca0/src/planner/macos.rs#L111-L130

If I omit the flag I would expect the volume to be encrypted because FileVault is enabled:

```
$ /usr/bin/fdesetup isactive                  
true
```

But that gives the same result as above.

**Comment by Hoverbear** [comment]
Linke 128 there definitely has a bug! Thanks for finding it!
