### ISSUE TITLE
No messaging about `auto-allocate-uids` so seems like we aren't making users

### ISSUE THREAD

**Issue by chewblacka** [DeterminateSystems/nix-installer#544]
I don't know if it's just me but by default the 0.10.0 installer installs using the following build user settings:

    * Create build users (UID 30000-30000) and group (GID 30000)

The group is correctly created in `/etc/group`, but no build users are created in `/etc/passwd`
Is this a bug?

Specifying the settings manually e.g. with the line below works. It's just the default values that are off.

    nix-installer install --nix-build-user-count 10 --nix-build-group-id 30000 --nix-build-user-id-base 30000

**Comment by Hoverbear** [comment]
Hi! This is intended! Linux planners now use `auto-allocate-uids` and don't need build users, however Mac does! We should improve the planner output to inform you of such.

**Comment by chewblacka** [comment]
Oops! Many thanks for the explanation!
