### ISSUE TITLE
Uninstaller fails when `/nix` is a pre-existing ZFS dataset

### ISSUE THREAD

**Issue by fnichol** [DeterminateSystems/nix-installer#545]
Howdy folks! While attempting to debug an issue (involving re-installing my Nix environment), I ran across an issue when calling the uninstall subcommand (i.e. `/nix/nix-installer uninstall`). Prior to installing Nix in the first place I had created a dedicated ZFS dataset mounted at `/nix` so that I could track usage/snapshot/disconnect it from other Linux boot environments etc. I believe that because this directory is a mounted dataset the equivalent of `rmdir` via the Rust code returned an error. Not totally sure if this is reasonable for the uninstaller to track or check for, but in case it comes up again, here's what I got:

## Error
```
Error: 
   0: Error reverting
   0: Action `create_directory` errored
      Remove file `/nix`

```

## Metadata
|key|value|
|--|--|
|**version**|0.8.0|
|**os**|linux|
|**arch**|x86_64|

**Comment by Hoverbear** [comment]
Making your `/nix` a separate volume is a great idea and advisable! We should definitely support this use case. I think we can check if the `/nix` is a mount and skip this action.

**Comment by fnichol** [comment]
Yeah, that's what I was thinking as a reasonable check that didn't involve more details. Basically, if it's a mount point, it's not getting deleted!

**Comment by Hoverbear** [comment]
Ya! It doesn't need to be created either!

**Comment by Hoverbear** [comment]
About an hour after this comment you should be able to go

```bash
curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix/branch/main | sh -s -- install
```

To use the fixed version before next release!
