### ISSUE TITLE
Self test fails, but installed Nix still functional

### ISSUE THREAD

**Issue by Quanterm** [DeterminateSystems/nix-installer#548]
## Error
```
Error: 
   0: Install failure
   1: Self test
   2: Shell `bash` failed self-test with command `"bash" "-lc" "nix build --no-link --expr \'derivation { name = \"self-test-bash-1688240356745\"; system = \"x86_64-linux\"; builder = \"/bin/sh\"; args = [\"-c\" \"echo hello > \\$out\"]; }\'"`, stderr:
   2: Der Befehl 'nix' wurde nicht gefunden, kann aber installiert werden mit:
      apt install nix-bin

```

## Metadata
|key|value|
|--|--|
|**version**|0.10.0|
|**os**|Debian GNU/Linux|
|**arch**|x86_64|

## More info
I have installed the version from the Official nixos before as a non daemon and after that as a demon via Debian GNU/Linux Repo. Both versions are working fine. I have only this install issue from Zero to Nix. I also removed all nix stuffs including in the shell config etc. Have I maybe miss something there? 
Despite the error it is some how working
### Nixshell is working
The fish shell on the left side is from nix-shelll -p
![image](https://github.com/DeterminateSystems/nix-installer/assets/94648307/524397c2-3000-437b-8f64-61a9b6b49745)
### The Daemon looks alsto ok
![image](https://github.com/DeterminateSystems/nix-installer/assets/94648307/249761fe-3970-45a4-a7c0-a5fff88a9a25)

**Comment by Hoverbear** [comment]
It seems like your `bash` shell on that system may not work with Nix... Could you try running Nix from `bash`?

Could you take a look in `/etc/bashrc`, `/etc/profile.d/nix.sh`, and `/etc/bash.bashrc` and see if there is maybe old entries from your previous install?

**Comment by Quanterm** [comment]
I have check that before. I had removed also Group ids and any dotfiles which are relate to nix

**Comment by Hoverbear** [comment]
We changed the code on the upcoming version to only WARN if this occurs: https://github.com/DeterminateSystems/nix-installer/pull/559

**Comment by Hoverbear** [comment]
I believe your install is working and that this may have been a quirk in your system configuration. #559 should help mitigate this looking so severe in the future. I think this can be closed.
