### ISSUE TITLE
Generated `nix.conf` is not deterministic

### ISSUE THREAD

**Issue by emilazy** [DeterminateSystems/nix-installer#562]
When testing the installer in clean macOS VMs, @Enzime and I obtained `nix.conf` files with the exact same settings, but in different orders. I assume this is due to iterating through a randomized hash map in the unspecified internal order or similar.

I realize that the user can supply settings that can affect the resulting configuration, but it would be really helpful for us (nix-darwin) if the default `nix.conf` file had a consistent and predictable hash. Plus, isn't unnecessary unreproducibility just not very Nix? :)

(It'd be even better if the file did not contain the full `nix-installer` version but just an integer that only increments on changes that might materially affect the output `nix.conf` file, but I can understand why you would not want to do this.)

**Comment by emilazy** [comment]
I should note also that the order is not completely irrelevant:

> A configuration setting usually overrides any previous value. However, you can prefix the name of the setting by `extra-` to *append* to the previous value.
> — https://nixos.org/manual/nix/stable/command-ref/conf-file.html

but I don't know if this is relevant to `nix-installer`.

**Comment by Hoverbear** [comment]
This is unfortunately a consequence of our `nix.conf` merging behavior. It's most certainly a place we could improve. We should probably be preserving the ordering/format where possible.

**Comment by emilazy** [comment]
FWIW, only the order of the file on a clean install really matters for us, since it's just a matter of having a consistent hash. Anyone doing customization pre-install hopefully knows what they're doing already and can add the hash or manually move the file away. So just removing the nondeterminism from the added options would be adequate for us, even though it might be worth considering ordering in general due to the odd behaviour of the `extra-*` options.
