### ISSUE TITLE
Some extra_conf arguments are silently ignored

### ISSUE THREAD

**Issue by therealpxc** [DeterminateSystems/nix-installer#577]
I've noticed that extra_conf arguments are listed in plans generated, but then don't actually appear in /etc/nix/nix.conf after the install is finished. I've seen this with:

  * any `!include ...` line
  * overriding extra_conf lines that come by default in the installer, e.g., `extra-nix-path`
  
  here's a snippet from a plan generated with v0.10.0:
  
```
"planner": {
    "planner": "macos",
    "settings": {
      "modify_profile": true,
      "nix_build_group_name": "nixbld",
      "nix_build_group_id": 30000,
      "nix_build_user_prefix": "_nixbld",
      "nix_build_user_count": 32,
      "nix_build_user_id_base": 300,
      "nix_package_url": "https://releases.nixos.org/nix/nix-2.15.0/nix-2.15.0-aarch64-darwin.tar.xz",
      "proxy": null,
      "ssl_cert_file": null,
      "extra_conf": [
        "!include /etc/nix/access-tokens.nix.conf",
        "extra-nix-path = nixpkgs=flake:nixpkgs darwin=flake:nix-darwin darwin-config=/etc/nix-darwin/configuration.nix",
        "auto-optimise-store = false"
      ],
      "force": false,
      "diagnostic_endpoint": "https://install.determinate.systems/nix/diagnostic"
    },
    "encrypt": false,
    "case_sensitive": false,
    "volume_label": "Nix Store",
    "root_disk": null
  }
```

When I run `install` instead of `plan`, it also reports those same features prior to installation:

```
Configured settings:
* extra_conf: ["!include /etc/nix/access-tokens.nix.conf","extra-nix-path = nixpkgs=flake:nixpkgs darwin=flake:nix-darwin darwin-config=/etc/nix-darwin/configuration.nix","auto-optimise-store = false"]
* root_disk: null
* volume_encrypt: false
```

but when the install is completed, here is what `/etc/nix/nix.conf` looks like:

```
# Generated by https://github.com/DeterminateSystems/nix-installer, version 0.10.0.
extra-nix-path = nixpkgs=flake:nixpkgs
experimental-features = nix-command flakes auto-allocate-uids
auto-optimise-store = true
build-users-group = nixbld
bash-prompt-prefix = (nix:$name)\040
```

**Comment by Hoverbear** [comment]
This likely stems from a bug in https://github.com/DeterminateSystems/nix-config-parser, but this issue is just fine living here since we're the only user of that crate.

**Comment by Hoverbear** [comment]
#620 may resolve this

**Comment by therealpxc** [comment]
I'm traveling atm so it may be a few days before I find time, but I'm excited to test this again! Thanks for the update :)

**Comment by Hoverbear** [comment]
I think this is fixed but I've kicked it along just in case you find an issue!

**Comment by Hoverbear** [comment]
I believe this may be fixed so I am closing it.
