### ISSUE TITLE
plan subcommand seems to require sudo on macOS, but does not prompt for it

### ISSUE THREAD

**Issue by therealpxc** [DeterminateSystems/nix-installer#578]
## Error
```
Error: 
   0: Planner error
   1: Error executing action
   2: Action `create_nix_volume` errored
   3: Action `create_or_insert_into_file` errored
   4: Open path `/etc/synthetic.conf`
   5: Permission denied (os error 13)
```

## Metadata
|key|value|
|--|--|
|**version**|0.10.0|
|**os**|macos|
|**arch**|aarch64|

Unlike the install subcommand, the plan subcommand does not prompt for sudo. This seems right! But the installer chokes when I try to run a plan without sudo, and succeeds when I do use it (`sudo ./nix-installer plan ...`).

The plan/install commands I've used for testing this have been invoked with arguments like this

```
./nix-installer plan macos --extra-conf '!include /etc/nix/access-tokens.nix.conf' 'extra-nix-path = nixpkgs=flake:nixpkgs darwin=flake:nix-darwin darwin-config=/etc/nix-darwin/configuration.nix' 'auto-optimise-store = false'
```

PS: Sorry for the flood of issue reports! I just finally logged into GitHub on my work Mac, where I've run into various quirks testing our Nix installation instructions. Overall I'm happy to have the Determinate Nix installer! I'd like to help it improve. :)

**Comment by Hoverbear** [comment]
Thanks for catching this! Really appreciate the issues. They'll keep me busy!

**Comment by therealpxc** [comment]
As you know well, the most brittle, finicky, parts of the Nix world are its joints with the non-Nix world. They're also the hardest for Linux/Unix novices to debug and overcome, which is a problem because many potential users on non-NixOS are exactly that!

Given that no one really wants to own the existing bash-based installer, I really appreciate your work on this one. :D
