### ISSUE TITLE
Running install script fails

### ISSUE THREAD

**Issue by samuela** [DeterminateSystems/nix-installer#583]
## Error
```
Error: 
   0: Install failure
   1: Self test
   2: Shell `sh` failed self-test with command `"sh" "-lc" "nix build --no-link --expr \'derivation { name = \"self-test-sh-1689722197433\"; system = \"x86_64-linux\"; builder = \"/bin/sh\"; args = [\"-c\" \"echo hello > \\$out\"]; }\'"`, stderr:
   2: sh: 1: nix: not found
```

Full log:
```
info: downloading installer https://install.determinate.systems/nix/tag/v0.10.0/nix-installer-x86_64-linux
`nix-installer` needs to run as `root`, attempting to escalate now via `sudo`...
 INFO Step: Create directory `/nix`
 INFO Step: Provision Nix
 INFO Step: Create build users (UID 30000-30000) and group (GID 30000)
 INFO Step: Configure Nix
 INFO Step: Configure Nix daemon related settings with systemd
 INFO Step: Remove directory `/nix/temp-install-dir`
Error: 
   0: Install failure
   1: Self test
   2: Shell `sh` failed self-test with command `"sh" "-lc" "nix build --no-link --expr \'derivation { name = \"self-test-sh-1689722197433\"; system = \"x86_64-linux\"; builder = \"/bin/sh\"; args = [\"-c\" \"echo hello > \\$out\"]; }\'"`, stderr:
   2: sh: 1: nix: not found
   2: 

Location:
   /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/convert/mod.rs:727
```

The md5 hash of the installer is ed8542008f0dd54533fdff8dc32b5d3f at the time of writing. Based on redirect URLs it appears to be version v0.10.0.

## Metadata
|key|value|
|--|--|
|**version**|0.10.0|
|**os**|linux|
|**arch**|x86_64|

**Comment by Hoverbear** [comment]
Could you help me with what Distribution this is from?

**Comment by samuela** [comment]
sure, this is on Ubuntu 20.04.6

**Comment by Hoverbear** [comment]
The good news is your install should still work (provided you don't revert), however your `sh` shell profile may not be set up correctly. Your `bash` shell etc may pick up `nix` fine. (If not, `/nix/nix-installer uninstall` and please report back)

**Comment by samuela** [comment]
is there any way to avoid this error in the future? I end up re-installing nix frequently (and automatically) due to some wonkiness with the infra I have to use

**Comment by Hoverbear** [comment]
Could you try `curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix/pr/587 | sh -s -- install` when the CI on #587 finishes? That should reduce the behavior to a warning. Let me know if it works better for you? (I'd love to see the output from your system's automation, too!)

**Comment by samuela** [comment]
Ok, I'll try and report back next time I end up re-installing!
