### ISSUE TITLE
<autogenerated-issue>

### ISSUE THREAD

**Issue by zestsystem** [DeterminateSystems/nix-installer#592]
## Error
```
Error: 
   0: Install failure
   1: Self test
   2: Shell `fish` failed self-test with command `"fish" "-ic" "nix build --no-link --expr \'derivation { name = \"self-test-fish-1690271221310\"; system = \"aarch64-darwin\"; builder = \"/bin/sh\"; args = [\"-c\" \"echo hello > \\$out\"]; }\'"`, stderr:
   2: open terminal failed: can't use /dev/tty

```

## Metadata
|key|value|
|--|--|
|**version**|0.10.0|
|**os**|macos|
|**arch**|aarch64|

**Comment by Hoverbear** [comment]
Is this a non-interactive shell or something? Does your fish install work?

**Comment by zestsystem** [comment]
I ended up installing nix the default way.  Followed the directions from nix website from bash and then used this to make it work with fish 

https://github.com/lilyball/nix-env.fish

**Comment by Hoverbear** [comment]
Closing then
