### ISSUE TITLE
/etc/zshrc may be overwritten on macos

### ISSUE THREAD

**Issue by hybras** [DeterminateSystems/nix-installer#593]
This might be for upstream to resolve first. I'm mentioning this here as a note for myself/others. The nix daemon script is sourced in /etc/{bashrc,zshrc} on macos. However, these files may be overwritten on os upgrade. They are not for 3rd party usage. Unclear what the solution is.

The workaround is to source the daemon in user-specific shell config (~/.zshrc or ~/.zprofile). This can be achieved by copying over the snippet inserted by the installer. However, this doesn't seem appropriate for the installer to do given that multiuser installs are the recommended option now.

https://github.com/NixOS/nix/issues/3616
https://github.com/NixOS/nix/issues/4169
https://github.com/NixOS/nix/pull/5179
https://checkoway.net/musings/nix/#fixing-shell-integration

**Comment by Hoverbear** [comment]
Yeah this is unfortunately a known issue and there isn't really a clear way to fix it either here or in the installer. :(

**Comment by fd** [comment]
You can use [this](https://github.com/mrhenry/nix-darwin-fixer) workaround I built. It can be used to manually fix the zshrc file or you can have it install a LaunchDaemon that will fix the file on boot.

**Comment by Hoverbear** [comment]
https://github.com/DeterminateSystems/nix-installer/pull/672 fixes this
