### ISSUE TITLE
Ensure that /bin/sh is indeed bash, or change the /bin/sh scripts to live without bashisms

### ISSUE THREAD

**Issue by metaminimalist** [DeterminateSystems/nix-installer#594]
Yesterday I was installing with nix-installer on older ubuntu and debian machines (ubuntu 18 and debian 11, but it does not really matter).

**Both times the installer failed** (and reverted flawlessly). So I re-ran it with` --verbose --logger full` and the reason given was
```
2023-07-27T13:14:14.280879Z ERROR nix_installer::cli::subcommand::install:
   0: Install failure
   1: Self test
   2: Shell `sh` failed self-test with command `"sh" "-lc" "nix build --no-link --expr \'derivation { name = \"self-test-sh-1690463654228\"; system = \"x86_64-linux\"; builder = \"/bin/sh\"; args = [\"-c\" \"echo hello > \\$out\"]; }\'"`, stderr:
   2: sh: 3: /etc/profile.d/logic.sh: function: not found
      sh: 4: local: not in a function

```
which comes clearly from using bash dialect in /bin/sh scripts.

And indeed /bin/sh was dash (Debian Almquist shell)
```
❯ ls -l /bin/sh
lrwxrwxrwx 1 root root       4 27. Jul 16:38 /bin/sh -> dash

```
which can be changed with 

```
❯ \sudo dpkg-reconfigure dash
[sudo] Passwort für me:
»Umleitung von /bin/sh zu /bin/sh.distrib durch dash« wird entfernt
»Umleitung von /bin/sh zu /bin/sh.distrib durch bash« wird hinzugefügt
»Umleitung von /usr/share/man/man1/sh.1.gz zu /usr/share/man/man1/sh.distrib.1.gz durch dash« wird entfernt
»Umleitung von /usr/share/man/man1/sh.1.gz zu /usr/share/man/man1/sh.distrib.1.gz durch bash« wird hinzugefügt

```
( side effects explained in https://wiki.ubuntu.com/DashAsBinSh ) into 

```
❯ ls -l /bin/sh
lrwxrwxrwx 1 root root       4 27. Jul 16:38 /bin/sh -> bash

```
and so henceforth **the installer works as intended**!

```
Nix was installed successfully!
To get started using Nix, open a new shell or run `. /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh`


❯                                                                                                                                        ~ took 41s
Script done on 2023-07-27 21:22:38+02:00 [COMMAND_EXIT_CODE="0"]
```

Less experienced testers may have gotten derailed by this, so please make sure that /bin/sh is indeed bash, or change the /bin/sh scripts to live without bashisms

**Comment by Hoverbear** [comment]
Thanks for raising this! The next version of the installer lowers this from an error to a warning so the situation will be a bit better! Still, labelling this as a bug.

**Comment by dnkmmr69420** [comment]
also use `#!/usr/bin/env bash` not `#!/bin/bash`

**Comment by Hoverbear** [comment]
The installer does not use `#!/bin/bash` anywhere, and the relevant scripts also don't use a hashbang, please open a new issue if you have something unrelated, thanks!

**Comment by Hoverbear** [comment]
I was thinking about this issue more and I think that skipping the self-test is not what we want, for shells that are links to other shells, we may want to avoid editing the shell profile all together.

I'd not want to place a user in a situation where we leave them with a broken `sh` and simply skip the self-test on `sh`.

**Comment by metaminimalist** [comment]
Greetings from the same debian 11 machine which raised the error :)

```/etc/profile.d/logic.sh``` is a bash script:
``` 
#!/bin/bash

function extend_path_for_swipl {
   local SWIPL="/usr/local/logic/swipl"
   local BIN="${SWIPL}/bin"
   if [[ -d "${BIN}" ]]; then
      export PATH="${BIN}:${PATH}"
      export SWIPL_HOME="$SWIPL"
   fi
}

extend_path_for_swipl
unset extend_path_for_swipl
```
so I guess defining a "function" in it is legal.
It is not a debian thing, but stems from an installation of SWI prolog, it can be found here: https://www.swi-prolog.org/Download.html

No error would have occurred if not something had started /bin/sh -> /bin/dash.

This machine is like all my boxes somewhat modified to run /bin/zsh as the login shell for all accounts but root and postgres which run /bin/zsh-static. Most of the /bin/zsh accounts have a local zsh profile with command line completion for the task of the account.

So I can be pretty sure that I/my accounts/my machine did not start /bin/sh (which at the time pointed to /bin/dash).

The start of /bin/sh (which pointed to /bin/dash) may have happened from here
https://github.com/DeterminateSystems/nix-installer/blob/34d0b7e4f0283288c965c9052c90b9c93bed6b09/nix-installer.sh#L1
or maybe by the elevation to root ``` `nix-installer` needs to run as `root`, attempting to escalate now via `sudo`... ```
Other candidates would be running things with sudo like ```curl $URL | sudo sh```, by cron - IIRC all these stubbornly use ```/bin/sh``` regardless of the users login shell set in ```/etc/passwd```.

I did not find any such things in the code, but then I am not firm enough in rust to guess what is in the sudo cstring.

**Comment by Hoverbear** [comment]
It's my assumption that `/etc/profile.d/logic.sh` existed (and thus `sh` was broken) before the `nix` install ever occured, so it being broken during self test makes sense since it was already broken.

Is this correct?

**Comment by metaminimalist** [comment]
This ist definitely correct, I installed SWI Prolog in last winter after xmas, and nix in July.

**Comment by metaminimalist** [comment]
So I spent a little bit of my sunday on that debian11 machine which triggered this issue:
- uninstalled nix
- uninstalled SWI Prolog
- made sure that there are no remnants in /etc and user profiles
- reverted to dash as ```/bin/sh```
- kept ```/bin/zsh``` and ```/bin/zsh-static``` as login shells
- did a system upgrade to the latest packages for debian 11
- rebooted

After that the installer worked as intended :)

Conclusion:
- it works with ```/bin/sh -> dash``` on unmodified systems
- it works with ```/bin/sh -> bash``` even on modified systems
- it does not work with ```/bin/sh -> dash``` on modified systems and leaves a non-functioning nix install

("modified" means that this machine has eight foreign repositories configured, and heavily personalized shell profiles. The SWI prolog installation was only a software package, and any of the installation could have written to /etc/profile.d/)

Maybe you should threat this like the test for Apple's ksh93 which I found in the installer.

I consider this thing "worksforme" now, but the mileage or stamina of others will vary.

**Comment by Hoverbear** [comment]
If the user has a broken `sh` before the install, it seems like the self test reporting that `sh` is broken is expected, so I am not sure this is a bug or is in need of fixing. SWI prolog shipping a broken `profile.d` for dash is neither the installers problem nor responsibility.

I really appreciate your report and help debugging the issue! It's good Nix is working for you now.
