### ISSUE TITLE
Action `encrypt_apfs_volume` errored

### ISSUE THREAD

**Issue by rstauch** [DeterminateSystems/nix-installer#595]
Hi,

I am trying to run the installer (after having succesfully run it some time ago to install nix in the first place) but the following error occurs:

## Error
```
Error: 
   0: Planner error
   1: Error executing action
   2: Action `encrypt_apfs_volume` errored
   3: The keychain lacks a password for the already existing "Nix Store" volume on disk `disk3`, consider removing the volume with `diskutil apfs deleteVolume "Nix Store"` (if you receive error -69888, you may need to run `launchctl bootout system/org.nixos.darwin-store` and `launchctl bootout system/org.nixos.nix-daemon` first)
```

## Metadata
|key|value|
|--|--|
|**version**|0.10.0|
|**os**|macos|
|**arch**|aarch64|

Is the installer not intended to be able to upgrade an existing installation ?

**Comment by Hoverbear** [comment]
Generally to upgrade Nix you should use `nix upgrade-nix` or uninstall (`/nix/nix-installer uninstall`) and reinstall.
