### ISSUE TITLE
Install failed on macos <autogenerated-issue>

### ISSUE THREAD

**Issue by wongle** [DeterminateSystems/nix-installer#600]
Tried to install a couple of times.  There didn't appear to be any existing user `_nixbld1` before attempting to install.

## Error
```
Error: 
   0: Install failure
   1: Error executing action
   2: Action `create_users_and_group` errored
   3: Action `create_user` errored
   4: Failed to execute command with status 55 `"/usr/bin/dscl" "." "-create" "/Users/_nixbld1" "UniqueID" "301"`, stdout: 
      stderr: <main> attribute status: eDSRecordAlreadyExists
      <dscl_cmd> DS Error: -14135 (eDSRecordAlreadyExists)


```

## Metadata
|key|value|
|--|--|
|**version**|0.10.0|
|**os**|macos|
|**arch**|aarch64|

**Comment by Hoverbear** [comment]
Hmmm I think the problem is a user with uid 301 already exists? `dscl . -list /Users UniqueID`

**Comment by wongle** [comment]
Ah, you're right. There does appear to be a user with uid 301 already existing ...

I ran the installer again with `./nix-installer install macos --nix-build-user-id-base 400` and looks like it works.  Thanks!

**Comment by Hoverbear** [comment]
I'm so glad!
