### ISSUE TITLE
Uninstall error on arm64 OSX

### ISSUE THREAD

**Issue by e-minguez** [DeterminateSystems/nix-installer#601]
## Error
```
Error: 
   0: Error reverting
   0: Action `create_apfs_volume` errored
      Failed to execute command with status 1 `"/usr/sbin/diskutil" "apfs" "deleteVolume" "Nix Store"`, stdout: Started APFS operation
      Deleting APFS Volume from its APFS Container
      Unmounting disk3s7
      The volume "Nix Store" on disk3s7 couldn't be unmounted because it is in use by process 0 (kernel)

      stderr: Error: -69888: Couldn't unmount disk



```

## Metadata
|key|value|
|--|--|
|**version**|0.8.0|
|**os**|macos|
|**arch**|aarch64|

**Comment by Hoverbear** [comment]
Hi! I think in this version (0.8.0) we didn't yet set time machine exclusions, so if your machine was backing up `/nix` at the time, this might have errored. Do you think you could try again, or reboot and try again?

**Comment by e-minguez** [comment]
After rebooting and trying again and reinstalling, it worked.

**Comment by Hoverbear** [comment]
That's really good to hear!
