### ISSUE TITLE
Upgrade to 2.17

### ISSUE THREAD

**Issue by gotcha** [DeterminateSystems/nix-installer#606]
Hi,

I am on MacOS. With Nix installed with your nix-installer. Thanks !

What is the recommended way to upgrade to Nix 2.17 ?

```
$ nix upgrade-nix
```
Or sthing else ?

**Comment by Hoverbear** [comment]
You can run this if you'd like! `sudo nix upgrade-nix --nix-store-paths-url https://releases.nixos.org/nix/nix-2.17.0/fallback-paths.nix
`

**Comment by gotcha** [comment]
Would the uninstall feature of nix-installer be impacted ?
