### ISSUE TITLE
 auto-allocate-uids confuses the installer

### ISSUE THREAD

**Issue by teto** [DeterminateSystems/nix-installer#621]
I have a colleague that tried to install nix with this installer but for some reason the install could not continue because of the following error
 ```
Error:
    0: Install failure
   1: Error executing action
   2: Action configure_nix errored
   3: Action setup_default_profile errored
   4: Failed to execute command with status 1 HOME="/root" NIX_SSL_CERT_FILE="/nix/store/ba4f8msp39cfvfpw3m7fsalb4psw347z-nss-cacert-3.83/etc/ssl/certs/ca-bundle.crt" "/nix/store/556bgbl9z8jm7030g1b31d0cblf09036-nix-2.15.0/bin/nix-env" "-i" "/nix/store/556bgbl9z8jm7030g1b31d0cblf09036-nix-2.15.0", 
      stdout:       
      stderr: installing 'nix-2.15.0'      error: experimental Nix feature 'auto-allocate-uids' is disabled; use '--extra-experimental-features auto-allocate-uids' to override
   4: Location:   /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/convert/mod.rs:726
Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.Run with RUST_BACKTRACE=full to include source snippets.
```
I suspect a previous install had enabled auto-allocate-uids in /etc/nix/nix.conf but I am not sure why this should influence the nix-installer.

We ended up using the official nix installer with a version pre 2.12 (which introduced auto-allocate-uids  ) that didn't care about the auto-allocate-uids setting

NB: Once nix is installed and you launch the nix-installer, it prints "Nothing is installed" which I find confusing as a message.

**Comment by Hoverbear** [comment]
I believe this may be a bug with our config parser. We do set `auto-allocate-uids` on Linux by default, I wonder if some bug was causing it to not be included in the new config...

**Comment by cole-h** [comment]
Maybe related to https://github.com/NixOS/nix/issues/8911.

**Comment by Hoverbear** [comment]
#620 would fix this

**Comment by Hoverbear** [comment]
We don't use this anymore.
