### ISSUE TITLE
<autogenerated-issue> install failed

### ISSUE THREAD

**Issue by mikeBoterf** [DeterminateSystems/nix-installer#630]
## Error
```
Error: 
   0: Planner error
   1: Error executing action
   2: Action `provision_nix` errored
   3: Action `create_nix_tree` errored
   4: Action `create_directory` errored
   5: `/nix/var` exists with a different uid (1000) than planned (0), consider updating it with `chown 0 /nix/var`
```

## Metadata
|key|value|
|--|--|
|**version**|0.11.0|
|**os**|linux|
|**arch**|x86_64|

**Comment by mikeBoterf** [comment]
executed `rm -rf nix`
now see this:
Error:
   0: Planner error
   1: Error executing action
   2: Action `create_group` errored
   3: Group `nixbld` existed but had a different gid (958) than planned (30000)

**Comment by mikeBoterf** [comment]
something is wrong with the user account on this system. I'll just move to nix rather than fix this. :1st_place_medal:

**Comment by Hoverbear** [comment]
This is a very puzzling issue, I'm glad to know it seems it wasn't an installer issue and instead a system issue.

I hope you manage to get it sorted!
