### ISSUE TITLE
<autogenerated-issue>

### ISSUE THREAD

**Issue by eribertto** [DeterminateSystems/nix-installer#633]
## Error
I'm trying to follow the tutorial Zero to Nix Guide 1 but immediately got stopped by the error below.
My machine is EndeavourOS and the command i did was
export RUST_BACKTRACE=full && curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix | sudo sh -s -- install

```
Error: 
   0: Reading plan
   1: No such file or directory (os error 2)

Location:
   src/cli/subcommand/install.rs:148
```

## Metadata
|key|value|
|--|--|
|**version**|0.11.0|
|**os**|linux|
|**arch**|x86_64|

**Comment by Hoverbear** [comment]
This is a bit puzzling, according to the line of code the error is reporting, the installer believes you're setting a plan file manually. I'm not sure why.

For example, if I ran:

```
❯ curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix | sudo NIX_INSTALLER_PLAN=asdasd sh -s -- install
info: downloading installer https://install.determinate.systems/nix/tag/v0.11.0/nix-installer-x86_64-linux
Error: 
   0: Reading plan
   1: No such file or directory (os error 2)

Location:
   src/cli/subcommand/install.rs:148
```

Or:

```
❯ curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix | sudo sh -s -- install asdasd
info: downloading installer https://install.determinate.systems/nix/tag/v0.11.0/nix-installer-x86_64-linux
Error: 
   0: Reading plan
   1: No such file or directory (os error 2)

Location:
   src/cli/subcommand/install.rs:148
```

I would get the same error.

Is it possible you included some text after the `install` arg, or that `NIX_INSTALLER_PLAN` is set?

**Comment by Hoverbear** [comment]
Closing due to no response.
