### ISSUE TITLE
Broken/Missing Channel on SteamDeck

### ISSUE THREAD

**Issue by H-K-47** [DeterminateSystems/nix-installer#654]
Expectation: after running the provided installer, i can install package - this isnt possible.

Example:

nix-env -iA nixpkgs.xrdp

returns nixpkgs not found 

Verify:
nix-channel --list

This returns nothing

Fix:

nix-channel --add https://nixos.org/channels/nixpkgs-unstable
nix-channel --update

**Comment by cole-h** [comment]
Hi! With flakes, we eschew the previous style of installing packages with `nix-env` in favor of `nix profile install`.

What you would use for your example is:

```
nix profile install nixpkgs#xrdp
```

**Comment by H-K-47** [comment]
Mh, ok - for a total newbie of nix this is hard to understand because when i search for references online how to work with nix on non NIX OS that is the descriptions i get.

**Comment by Hoverbear** [comment]
Indeed it is confusing! We aren't going to override the command.
