### ISSUE TITLE
Unable to run nix-installer over an existing (older) install

### ISSUE THREAD

**Issue by mirosval** [DeterminateSystems/nix-installer#667]
## Error
```
Error: 
   0: Unable to parse existing receipt `/nix/receipt.json`, it may be from an incompatible version of `nix-installer`. Try running `/nix/nix-installer uninstall`, then installing again.
   1: missing field `existing_entry` at line 44 column 11
```

The affected entry in the `/nix/receipt.json` looks like this:
```json
        "create_fstab_entry": {
          "action": {
            "apfs_volume_label": "Nix Store"
          },
          "state": "Completed"
        },
```

## Metadata
|key|value|
|--|--|
|**version**|0.11.0|
|**receipt version**|0.5.0|
|**os**|macos|
|**arch**|aarch64|

**Comment by Hoverbear** [comment]
You'll need to run `/nix/nix-installer uninstall` and reinstall if you want to re-run.

**Comment by derekmahar** [comment]
> You'll need to run `/nix/nix-installer uninstall` and reinstall if you want to re-run.

@Hoverbear, can `/nix/nix-installer uninstall` remove `nix-installer` without deleting an existing Nix store and the packages that it contains?
