### ISSUE TITLE
installing in a container with systemd does not work as described

### ISSUE THREAD

**Issue by xendarboh** [DeterminateSystems/nix-installer#670]
The `Dockerfile` from the README fails to build for [in a container](https://github.com/DeterminateSystems/nix-installer#in-a-container) _with a systemd init_.

## Error
```
Error: 
   0: Planner error
   1: Error executing action
   2: Action `configure_init_service` errored
   3: Could not detect systemd; you may be able to get up and running without systemd with `nix-installer install linux --init none`.
      See https://github.com/DeterminateSystems/nix-installer#without-systemd-linux-only for documentation on usage and drawbacks.
```

## Metadata
|key|value|
|--|--|
|**version**|0.13.1|
|**os**|linux|
|**arch**|x86_64|

**Comment by Hoverbear** [comment]
I was able to run it, could you share your dockerfile with me?

**Comment by matifali** [comment]
```Dockerfile
# Dockerfile
FROM ubuntu:latest
RUN apt update -y
RUN apt install curl systemd -y
RUN curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix | sh -s -- install linux \
  --extra-conf "sandbox = false" \
  --no-start-daemon \
  --no-confirm
ENV PATH="${PATH}:/nix/var/nix/profiles/default/bin"
RUN nix run nixpkgs#hello
CMD [ "/bin/systemd" ]
```

hi @Hoverbear does not build.

**Comment by skewballfox** [comment]
hey running into a similar issue on fedora 39. 
I believe the issue is how you are checking for systemd [here](https://github.com/DeterminateSystems/nix-installer/blob/58303b559872b2f8d476d23f1c0496374204b548/src/action/common/configure_init_service.rs#L84)

I edited the Dockerfile to include an echo "$(ls /run/systemd)" before the curl command. This is the output: 

```
STEP 4/8: RUN echo "$(ls /run/systemd)"
ask-password
container
machines
netif
resolve
seats
sessions
shutdown
users
--> f6724eefea6e
STEP 5/8: RUN curl...
```
I poked around with hacking work arounds a little after that(creating the directory, running `systemctl status` to see if it would initialize things) but haven't found a way to get it to launch properly yet (while avoiding resorting to root). If I manage to find a solution, I'll  let you know

**Comment by skewballfox** [comment]
So I looked further unto this and I'm not sure there is a way to get this to build with podman without changes to how the installer initializes.

Buildah, the default build back end for podman doesn't run the init system, so the directory you are checking for doesn't exist and systemctl commands will fail. You could create the directory, and do all the steps save for actually enabling the service, and then either leave that to the actual running of the container, or potentially make use of redhats ubc-init container, the docs said something about systemctl available at build time, but I couldn't seem to make use of it

**Comment by Hoverbear** [comment]
@skewballfox I think you're right! Once CI is done, this should be a fixed version:

```bash
curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix/pr/853| sh -s -- install
```

**Comment by skewballfox** [comment]
hey yeah I got to the container to launch with that. here's the dockerfile I used
```
# Dockerfile
FROM registry.access.redhat.com/ubi8/ubi-init
RUN dnf install -y curl
RUN curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix/pr/853| sh -s -- install linux \
  --extra-conf "sandbox = false" --no-start-daemon --no-confirm
ENV PATH="${PATH}:/nix/var/nix/profiles/default/bin"
RUN nix run nixpkgs#hello
CMD [ "/sbin/init" ]
```
