### ISSUE TITLE
Document how to swap from a normal Nix install to this version

### ISSUE THREAD

**Issue by Victor239** [DeterminateSystems/nix-installer#677]
I like many used the official route for installing Nix. I was therefore surprised there was nothing in the README about how to swap over to this installer without uninstalling all my packages.

**Comment by grahamc** [comment]
Interesting! What’s your goal from switching over after installing? I’d love to hear about it.

**Comment by Victor239** [comment]
I've heard flakes mentioned in various Nix communities but I've never set it up, so I like that it's included with this installer. I like that I can upgrade to a [specific version](https://github.com/DeterminateSystems/nix-installer#upgrading-nix) if needed. And it just generally sounds like a cleaner, simpler installer.

**Comment by Hoverbear** [comment]
You can edit your `/etc/nix/nix.conf` and add `experimental-features = nix-command flakes"` to enable flakes.

You can run `nix upgrade-nix` from any Nix install with the `nix-command` feature.

If you wish to uninstall your old Nix and install Nix again you can follow the instructions on https://nixos.org/manual/nix/stable/installation/uninstall. This installer can *sometimes* run "over" an existing install from the install scripts, but this process is obviously full of corner cases that could lead to weirdness. If you feel particularly brave, just run this installer with Nix already installed, sometimes it works! If it doesn't, the uninstall process is the same. 😅
