### ISSUE TITLE
Unable to read the receipt (v0.8.0)

### ISSUE THREAD

**Issue by PackMeister** [DeterminateSystems/nix-installer#678]
## Error
```
Error: 
   0: Reading receipt
   1: No such file or directory (os error 2)
```

## Metadata
|key|value|
|--|--|
|**version**|0.8.0|
|**os**|macos|
|**arch**|x86_64|

**Comment by Hoverbear** [comment]
Lacking some more information, my best suggestion is to try using a newer version of the installer. 0.8.0 is quite old.
