### ISSUE TITLE
<autogenerated-issue>

### ISSUE THREAD

**Issue by han-tyumi** [DeterminateSystems/nix-installer#683]
## Error
```
Error: 
   0: Planner error
   1: Error executing action
   2: Action `configure_nix` errored
   3: Action `create_directory` errored
   4: Failed to execute command `"mount" "-d"`
   5: No such file or directory (os error 2)
```

## Metadata
|key|value|
|--|--|
|**version**|0.14.0|
|**os**|macos|
|**arch**|aarch64|

**Comment by Hoverbear** [comment]
It seems your machine doesn't have the `mount` command?

**Comment by han-tyumi** [comment]
Yeah..
My `$PATH` had somehow been reduced to `/usr/bin:/bin`.
So after adding `/usr/sbin:/sbin` to it, it worked without issue.

It's worth noting that the nix installer [here](https://nixos.org/download.html#nix-install-macos) worked even with these commands not being present in my `PATH`.
So maybe something worth looking into 🤷‍♂️
