### ISSUE TITLE
<autogenerated-issue>

### ISSUE THREAD

**Issue by eeoam** [DeterminateSystems/nix-installer#688]
I tried to install Nix on ubuntu using one the binary releases (version 0.14.0) as follows: `./nix-installer-x86_64-linux install
` but I got this

## Error
```
Error: 
   0: Install failure
   1: Error executing action
   2: Action `create_group` errored
   3: Failed to execute command with status 4 `"groupadd" "-g" "30000" "--system" "nixbld"`, stdout: 
      stderr: groupadd: GID '30000' already exists


```

## Metadata
|key|value|
|--|--|
|**version**|0.14.0|
|**os**|linux|
|**arch**|x86_64|

**Comment by Hoverbear** [comment]
It seems a service is already using UID `3000`. You'll need to use the `--nix-build-user-id-base` argument to choose some other number (eg 3100)

**Comment by eeoam** [comment]
The error message says nothing about UID `3000`. Did you mean GID `30000`? 

In any event, I tried running with the command `./nix-installer-x86_64-linux install --nix-build-user-id-base 31000
` but get exactly the same

## Error
``` 
   0: Install failure
   1: Error executing action
   2: Action `create_group` errored
   3: Failed to execute command with status 4 `"groupadd" "-g" "30000" "--system" "nixbld"`, stdout: 
      stderr: groupadd: GID '30000' already exists
```

**Comment by cole-h** [comment]
Probably meant GID indeed. Try with `--nix-build-group-id 31000`.

**Comment by eeoam** [comment]
@cole-h : That worked! Thanks!
