### ISSUE TITLE
Installing home-manager in an `--init none` installation

### ISSUE THREAD

**Issue by derekmahar** [DeterminateSystems/nix-installer#693]
After using nix-installer to install Nix in an Alpine Linux container that [does not use systemd](https://github.com/DeterminateSystems/nix-installer#without-systemd-linux-only), what is the recommended method of installing home-manager?

In my attempt below to install home-manager, which I must run as root, so that home-manager does not create its default configuration in `/root/.config/home-manager`, I explicitly specified the home-manager configuration directory as `~/.config/home-manager`.  Note that after the installation is complete, root owns `~/.config/home-manager` instead of user `derek`.  Furthermore, so that `sudo home-manager switch` does not look for the default configuration in `/root/.config/home-manager` , I again exhibiting specified the home-manager configuration directory with the `--flake` option in command `sudo home-manager switch --flake ~/.config/home-manager`.  Is there another way to do this that would allow me to use the default home-manager configuration, but not in the root home directory?

```
alpine-1:~$ sudo nix run home-manager/master -- init --switch ~/.config/home-manager                                                                  
[sudo] password for derek:
Creating /home/derek/.config/home-manager/home.nix...
Creating /home/derek/.config/home-manager/flake.nix...

Creating initial Home Manager generation...

warning: creating lock file '/home/derek/.config/home-manager/flake.lock'
trace: warning: optionsDocBook is deprecated since 23.11 and will be removed in 24.05
trace: warning: optionsDocBook is deprecated since 23.11 and will be removed in 24.05
trace: warning: optionsDocBook is deprecated since 23.11 and will be removed in 24.05
Starting Home Manager activation
Activating checkFilesChanged
Activating checkLinkTargets
Activating writeBoundary
Activating installPackages
installing 'home-manager-path'
building '/nix/store/26a7xjr3frdyhhn2vl41ygxk13p1l8i9-user-environment.drv'...
Activating linkGeneration
Creating profile generation 1
Creating home file links in /root
Activating onFilesChange

There are 121 unread and relevant news items.
Read them by running the command "home-manager news".

All done! The home-manager tool should now be installed and you can edit

    /home/derek/.config/home-manager/home.nix

to configure Home Manager. Run 'man home-configuration.nix' to
see all available options.
alpine-1:~$ ls -la ~/.config/home-manager
total 20
drwxr-sr-x    2 root     derek         4096 Oct 28 17:38 .
drwx--S---    5 derek    derek         4096 Oct 28 17:38 ..
-rw-r--r--    1 root     derek         1120 Oct 28 17:38 flake.lock
-rw-r--r--    1 root     derek          795 Oct 28 17:38 flake.nix
-rw-r--r--    1 root     derek         2490 Oct 28 17:38 home.nix
alpine-1:~$ sudo home-manager switch --flake ~/.config/home-manager
Starting Home Manager activation
Activating checkFilesChanged
Activating checkLinkTargets
Activating writeBoundary
Activating installPackages
replacing old 'home-manager-path'
installing 'home-manager-path'
Activating linkGeneration
Cleaning up orphan links from /root
No change so reusing latest profile generation 1
Creating home file links in /root
Activating onFilesChange

There are 121 unread and relevant news items.
Read them by running the command "home-manager news".
```

**Comment by Hoverbear** [comment]
I believe this is currently an unsupported configuration.

I believe the only way to install Nix without init and use it as non-root to use home-manager in such a way would be the official single-user scripts, or doing some `chmod`ing and `chown`ing of things.

**Comment by derekmahar** [comment]
Thank you for your answer.  I'll install the official single-user script instead.

**Comment by derekmahar** [comment]
Using the following guides, I installed multi-user Nix with flakes support and Home Manager on Alpine Linux:

- [Install NIX Package Manager on Alpine Linux](https://www.macktronics.com/nixpkg-alpine.html) ([Gist](https://gist.github.com/danmack/b76ef257e0fd9dda906b4c860f94a591#nix-package-manager-install-on-alpine-linux))
- [Home Manager Manual - 3. Nix Flakes - 3.2 Standalone Setup](https://nix-community.github.io/home-manager/index.html#sec-flakes-standalone)
