### ISSUE TITLE
Install Nix into an specific location

### ISSUE THREAD

**Issue by mmartinortiz** [DeterminateSystems/nix-installer#695]
Hi

I want to install `nix` into an Ubuntu system with a very small root partition. There are other partition in the machine with bigger space where `nix` can be installed without problem. I tried with a symlink from `/nix` to `/srv/nix` (location with enough space for `nix`) but symlinks are not allowed.

The `nix install --help` does not indicate how to specify a different install location. Is there a way to install nix in a location different to `/nix`?

Thanks

**Comment by Hoverbear** [comment]
Unfortunately the `nix` store must be located on `/nix` and symlinks are not allowed. :(

I believe one strategy here is to do a bind mount! https://www.baeldung.com/linux/bind-mounts#bind-mounts

**Comment by mmartinortiz** [comment]
> Unfortunately the `nix` store must be located on `/nix` and symlinks are not allowed. :(
> 
> I believe one strategy here is to do a bind mount! https://www.baeldung.com/linux/bind-mounts#bind-mounts

This did the trick, indeed. Thanks!
