### ISSUE TITLE
direnv support

### ISSUE THREAD

**Issue by kolloch** [DeterminateSystems/nix-installer#703]
I'd love a CLI flag to include direnv installation since nix+direnv is such a lovely combination.

I understand if you consider this out-of-scope.

I do this "by hand" in this repository: https://gitlab.com/nexxiot-labs/nix-bootstrap

**Comment by Hoverbear** [comment]
It would be convienent! I think in the interest of keeping the project from becoming difficult to maintain we should take the same position as we do with similar tools like `home-manager` and `nix-darwin`: It outside of scope. :(

Really happy to see the installer in `nix-bootstrap`. :) Please let us know if you encounter any issues.

**Comment by kolloch** [comment]
Thank you for answering and I do understand
