### ISSUE TITLE
On macOS, how are the `launchd` daemons maintained?

### ISSUE THREAD

**Issue by dhess** [DeterminateSystems/nix-installer#726]
On macOS, this installer installs a few `launchd` daemons (e.g., `/Library/LaunchDaemons/systems.determinate.nix-installer.nix-hook.plist`). On a stateful system like a developer's laptop, presumably these daemons will occasionally need to be updated to accommodate changes in macOS, Nix, `nix-darwin`, etc.

What's the process for this? Unless I'm missing something, it doesn't appear to be addressed in the docs.

**Comment by dhess** [comment]
@Hoverbear Hi, yes, I can see that the service files are copied. Sorry that I wasn't more clear: I suppose what I'm asking is, if an update is required to one of these service files, would the user be expected to run a new version of the installer again, just to fix them up?

I ask because while `nix-darwin` also installs `launchd` service files, its service files are of course maintained and updated by `nix-darwin` upon a `darwin-rebuild switch`, but the Nix installer is a one-shot (or should be, IMO). Since `nix-darwin` doesn't know about or otherwise assume ownership of any service files installed by the installer, it's not clear how the user would update the installer's services when necessary.

(I'm thinking here in particular of the `systems.determinate.nix-installer.nix-hook`, as it seems inevitable to me that it'll require a different approach than what it currently takes if it's going to properly interoperate with `nix-darwin`.)

**Comment by Hoverbear** [comment]
Yes the installer is oneshot. I believe you are right about the issues interacting with `nix-darwin`. (See https://github.com/DeterminateSystems/nix-installer/issues/721)
