### ISSUE TITLE
MacOS single user install

### ISSUE THREAD

**Issue by nustiueudinastea** [DeterminateSystems/nix-installer#732]
Hey folks, thank you so much for this nice piece of software! 

Is it possible to have a MacOS installation that has the following characteristics?
- keeps all files in the user's home directory
- doesn't require sudo
- doesn't require a running daemon

From what I could gather the official Nix installer has deprecated the MacOS single user installation, so I was hoping yours still supports it.

**Comment by Hoverbear** [comment]
Unfortunately we do not support single user installs on any platform, so we can't help here!
