### ISSUE TITLE
Can't install on Mac OS 13.6.1

### ISSUE THREAD

**Issue by ajfabbri** [DeterminateSystems/nix-installer#733]
Installer fails on install and well as uninstall

## Error
```
Error: 
   0: Planner error
   1: Error executing action
   2: Action `create_nix_volume` errored
   3: Action `create_volume_service` errored
   4: `/Library/LaunchDaemons/org.nixos.darwin-store.plist` contents differs, planned `LaunchctlMountPlist { run_at_load: true, label: "org.nixos.darwin-store", program_arguments: ["/usr/sbin/diskutil", "mount", "-mountPoint", "/nix", "31D988B8-C6AC-49AF-9473-69AB5448D7A5"] }`, discovered `LaunchctlMountPlist { run_at_load: true, label: "org.nixos.darwin-store", program_arguments: ["/bin/sh", "-c", "/usr/bin/security find-generic-password -s '31D988B8-C6AC-49AF-9473-69AB5448D7A5' -w | /usr/sbin/diskutil apfs unlockVolume '31D988B8-C6AC-49AF-9473-69AB5448D7A5' -mountpoint '/nix' -stdinpassphrase"] }`
```

## Metadata
|key|value|
|--|--|
|**version**|0.14.0|
|**os**|macos|
|**arch**|aarch64|

## Uninstall Error
```
sudo ~/Downloads/nix-installer uninstall
info: downloading installer (https://install.determinate.systems/nix/tag/v0.14.0/nix-installer-aarch64-darwin)
Error:
   0: Reading receipt
   1: No such file or directory (os error 2)

Location:
   src/cli/subcommand/uninstall.rs:113
```

**Comment by Hoverbear** [comment]
For the install error: It appears you already had a version of Nix installed and it was warning you it could not install since the actions it planned would conflict with your existing install.

It did not actually attempt to install.

For the uninstall error: It was not able to detect a receipt from the install (since it did not try it) so it could not uninstall.

**Comment by ajfabbri** [comment]
Update: I tried this again and it worked. Last issue was probably a stale shell environment or was fixed as a side effect of updating / rebooting. Closing this.

**Comment by Hoverbear** [comment]
I'm glad it worked!
