### ISSUE TITLE
MacOS: Unable to mount Nix Store partion (wrong password) after reboot

### ISSUE THREAD

**Issue by squiddy** [DeterminateSystems/nix-installer#753]
This already happened before. After a reboot (not the first one, but after some time), MacOS prompts me to enter the password for the Nix Store partition. My assumption right now is that the password has changed, because I made a copy of it (`security find-generic-password -s "Nix Store" -w`) into my home directory, and I can't use that anymore to unlock the partition. I did look into keychains to see if perhaps there are more entries for the Nix Store, but there is only this one.

I'm rather new to the apple ecosystem, so I appreciate any help that can get me closer to find out what happens.

Note: This is a machine provided by work and has some Sophos Endpoint Protection running, I'm reaching out to my Ops colleagues to double-check if that could interfer (as in, randomly change passwords).

**OS/Arch** MacOS 14.0, aarch64
**nix-installer version** 0.15.1

**Comment by squiddy** [comment]
Talked with my colleagues, might be the Sophos Disc Encryption service making trouble. I just saw in the code that encryption can be disabled in the installer, so that would be my next try. I'm assuming Sophos would still encrypt it, but then also take care of unencrypting it.

**Comment by Hoverbear** [comment]
We've not tested with Sophos, so it would make sense that it would be the culript for an issue like this...

**Comment by squiddy** [comment]
I don't recall exactly the steps I took, but I remember I had some issues convincing the installer not to encrypt the partition. I think because it checks if filevault is active and bases its decision on that.

Resorted to creating a plan, which didn't have that problem, and installing that.

Working fine so far, so closing the issue.

**Comment by cognivore** [comment]
Can someone outline the solution for installation from a PKG installer? What does one have to do to replace a broken installation?

**Comment by insanityfarm** [comment]
Consider this a minor bug report: I'm using the macOS planner specifically to leave the Nix Store unencrypted as @stephan-koenig described. Before doing the install, the installer prints this pre-flight Nix install plan:

```
Nix install plan (v3.5.2)
Planner: macos

Configured settings:
* determinate_nix: true
* root_disk: null
* volume_encrypt: false

Planned actions:
* Install Determinate Nixd
* Create an encrypted APFS volume `Nix Store` for Nix on `disk3` and add it to `/etc/fstab` mounting on `/nix`
* Extract the bundled Nix (originally from /nix/store/2a6qx3xsipw473bhnw4y20cpskqdmgpp-nix-binary-tarball-3.5.2/nix-3.5.2-aarch64-darwin.tar.xz) to `/nix/temp-install-dir`
* Create a directory tree in `/nix`
* Synchronize /nix/var ownership
* Move the downloaded Nix into `/nix`
* Synchronize /nix/store ownership
* Create build users (UID 351-382) and group (GID 350)
* Configure Time Machine exclusions
* Setup the default Nix profile
* Place the Nix configuration in `/etc/nix/nix.conf`
* Configure the shell profiles
* Configuring zsh to support using Nix in non-interactive shells
* Create a `launchctl` plist to put Nix into your PATH
* Configure the Determinate Nix daemon
* Remove directory `/nix/temp-install-dir`
```

The "bug" is just that step 2 says "Create an **encrypted** APFS volume" which is misleading because `volume_encrypt` is false. In this case the plan should say "unencrypted".
