### ISSUE TITLE
Bug: macOS `nix-installer uninstall` command not found, executable is missing correct chmod settings + 

### ISSUE THREAD

**Issue by sambacha** [DeterminateSystems/nix-installer#765]
## `nix-installer` does not have correct permissions 

```bash
sudo: /nix/nix-installer: command not found
```
<img width="546" alt="Screenshot 2023-12-03 at 8 26 15 PM" src="https://github.com/DeterminateSystems/nix-installer/assets/32783916/686211ac-3771-462f-a146-f25edbe6c25c">

## After correctly setting `chmod +x`
<img width="896" alt="Screenshot 2023-12-03 at 8 28 00 PM" src="https://github.com/DeterminateSystems/nix-installer/assets/32783916/29efedf3-b209-4354-af1e-0e67cbc68bc9">

**Comment by Hoverbear** [comment]
Thanks for this report! This seems to be a new issue.

**Comment by Hoverbear** [comment]
This appears to have been fixed since 0.8.0:

https://github.com/DeterminateSystems/nix-installer/blob/0419422de00515245f91759e6004fe2a15112e94/src/cli/subcommand/install.rs#L343

 Hopefully next time you try it will work. :)

**Comment by sambacha** [comment]
> This appears to have been fixed since 0.8.0:
> 
> https://github.com/DeterminateSystems/nix-installer/blob/0419422de00515245f91759e6004fe2a15112e94/src/cli/subcommand/install.rs#L343
> 
> Hopefully next time you try with a newer version it will work. :)


I actually was trying to update the installer, hence my posting of this issue and this one: https://github.com/DeterminateSystems/nix-installer/issues/764

Would you be open to a feature request for a 'soft reset' of configuration nix to the default setup?

**Comment by Hoverbear** [comment]
If you wish to reset your nix setup, the best option is to uninstall and reinstall.

If things like your shell profile are broken, you can sometimes get by with `/nix/nix-installer repair`.

If your `nix.conf` has somehow become problematic, you can review https://github.com/DeterminateSystems/nix-installer#installation-differences to set it exactly as we do. Perhaps we could add this to `/nix/nix-installer repair` somehow...

If your user `~/.config/nix` related things are problematic, this installer doesn't touch user configs, so it can't help with this.
