### ISSUE TITLE
Feature: offer sane defaults for `nix.conf` like adding cachix.org as a trusted substituter, etc.

### ISSUE THREAD

**Issue by sambacha** [DeterminateSystems/nix-installer#770]
On a fresh installation using the `nix-installer` I am confronted with the same issues as if I had used the normal nix installer. As a user, I would very much appreciate this set to sensible defaults that way I can get working and not adjusting boilerplate defaults.

```
$ nix flake update
warning: Git tree '/Users/janitor/mevETH2' is dirty
warning: ignoring untrusted substituter 'https://nix-community.cachix.org', you are not a trusted user.
Run `man nix.conf` for more information on the `substituters` configuration option.
error:
       … while updating the lock file of flake 'git+file:///Users/janitor/mevETH2'

       … while updating the flake input 'devshell'

       … while fetching the input 'github:numtide/devshell'

       error: unable to download 'https://api.github.com/repos/numtide/devshell/commits/HEAD': HTTP error 403

       response body:

       {"message":"API rate limit exceeded for 76.95.243.232. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)","documentation_url":"https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"}
```

https://nixos.org/manual/nix/stable/command-ref/conf-file.html#conf-trusted-substituters

**Comment by Hoverbear** [comment]
Appreciate the suggestion!

You are free to add that specific cachix cache as a trusted user using the `--extra-conf` at install time, or by editing your `/etc/nix.conf`.

It is not currently a goal of this project to "bless" specific community projects or the binary caches they suggest. What you consider sensible may not match the threat model of someone else.
