### ISSUE TITLE
Not working on Fedora Silverblue (rpm-ostree based)

### ISSUE THREAD

**Issue by bitestring** [DeterminateSystems/nix-installer#783]
After a reboot of Fedora Silverblue, Nix fails to work. This is constantly reproducible for months.

```
error: cannot connect to socket at '/nix/var/nix/daemon-socket/socket': Connection refused
```

Also systemd reports

```
Failed to start ensure-symlinked-units-resolve.service - Ensure Nix related units which are symlinked resolve.
```

**Comment by Hoverbear** [comment]
Thanks for the report!

**Comment by osalbahr** [comment]
Do you remember if you’ve used the determinate installer before or after the following PR?

- https://github.com/DeterminateSystems/nix-installer/pull/586

**Comment by bitestring** [comment]
It's definitely after the mentioned PR. I tried sometime back in November or December. Last time I tried it survived couple of reboots.But I fully moved to NixOS now. So I am not sure if it still works in Fedora. I can spin a VM and try.

**Comment by cole-h** [comment]
Thanks for confirming, I'll close this then.

If anybody stumbles here but is having the same / a similar problem, please feel free to open a new issue!
