### ISSUE TITLE
illegal configuration line 'extra-substituters'

### ISSUE THREAD

**Issue by SomeoneSerge** [DeterminateSystems/nix-installer#792]
## Error
```
Error: 
   0: Planner error
   1: Error executing action
   2: Action `configure_nix` errored
   3: Action `place_nix_configuration` errored
   4: illegal configuration line 'extra-substituters: https://XXXX.cachix.org' in '<unknown>'
```

(from https://github.com/SomeoneSerge/pkgs/actions/runs/7326992609/job/19953297268#step:25:23)

## Metadata
|key|value|
|--|--|
|**version**|0.15.1|
|**os**|linux|
|**arch**|x86_64|

**Comment by cole-h** [comment]
`extra-conf` needs to be in the same format as you would put in a nix.conf yourself. The format is `<setting name> = <setting value(s)>`, not `<name>: <value>`.

**Comment by SomeoneSerge** [comment]
Late nights and blurry vision xD Thanks and sorry for the noise!
