### ISSUE TITLE
`nix-installer repair` overwrites nix-darwin symlinks

### ISSUE THREAD

**Issue by lilyball** [DeterminateSystems/nix-installer#805]
nix-darwin manages `/etc/bashrc` on my system, making it a symlink to `/etc/static/bashrc` (which itself is a symlink into the store). `nix-installer repair` replaces this symlink with a regular file that has text injected at the start. This means the "repair" is actually breaking my system.

This likely affects other files that repair touches, I'm not sure offhand what they are (I don't have nix-darwin configure zsh because I don't use zsh, but that's probably affected by this).

It would be great if nix-installer could check to see if the files it wants to repair are actually symlinks into `/etc/static` and skip them in that case. In the event of a system update replacing these files, there's still a potential race condition here between `nix-installer repair` and the `org.nixos.activate-system` LaunchDaemon and I'm not sure what the appropriate remedy there is. It could potentially just check for `/etc/static` and see if the file in `/etc` it wants to fix exists within `/etc/static`, and if so then skip the file entirely with the assumption that nix-darwin is going to fix the system itself. This would leave the edge case of a user who installs nix-darwin and then uninstalls it, removing the `org.nixos.activate-system` LaunchDaemon but leaving `/etc/static` intact, I don't know if that's a plausible scenario but perhaps nix-installer could go so far as to check for the `org.nixos.activate-system` LaunchDaemon.

In the meantime my workaround is going to be to simply disable the `systems.determinate.nix-installer.nix-hook` LaunchDaemon, but I'm sure this issue is affecting other people too and I'd prefer to let nix-installer continue to repair anything that's not being managed by nix-darwin.

**Comment by cole-h** [comment]
I believe this is (somewhat?) related to https://github.com/DeterminateSystems/nix-installer/issues/721.

In https://github.com/DeterminateSystems/nix-installer/pull/767/, we added a check so that we don't clobber symlinks. That should be seeing a release sometime next week, I believe.

**Comment by cole-h** [comment]
(This should be fixed as of https://github.com/DeterminateSystems/nix-installer/releases/tag/v0.16.0)
