### ISSUE TITLE
How to manage nixpkgs version?

### ISSUE THREAD

**Issue by samuela** [DeterminateSystems/nix-installer#822]
I was surprised upon installing to discover that `nix-channel` doesn't work the same as in an "official" install:
```
$ nix-channel --list
$
```
(Tangential: Why is the `nix-channel` binary still included in the install if it is not a recommended/supported path to managing nixpkgs with the Determinate installer?)

Poking around the docs and issues, AFAIU this is because 
```
extra-nix-path = nixpkgs=flake:nixpkgs
```
is set in `/etc/nix/nix.conf`. I tried setting 
```
extra-nix-path = nixpkgs=flake:nixpkgs:2311
```
and other combinations like `23.11`, and so on. But to no avail:
```
$ nix-shell -p python3
error:
       … <borked>

       … while calling the 'import' builtin

         at «string»:1:18:

            1| {...}@args: with import <nixpkgs> args; (pkgs.runCommandCC or pkgs.runCommand) "shell" { buildInputs = [ (python3) (python3Packages.torchWithCuda) ]; } ""
             |                  ^

       … while realising the context of a path

       (stack trace truncated; use '--show-trace' to show the full trace)

       error: input 'nixpkgs:23.11' is unsupported
```

How does one set the nixpkgs version when using the Determinate installer?

**Comment by samuela** [comment]
Related: how do I determine which commit of nixpkgs I'm using by default?

**Comment by Hoverbear** [comment]
Indeed, this installer does not set up `nix-channel`. It is included because it would be harder not to include it (We'd need to provide a different Nix derviation).

Can you try this?

In your `nix.conf`:

```
extra-nix-path = nixpkgs=flake:nixpkgs/23.11
```

Then restart your Nix daemon (eg `sudo systemctl restart nix-daemon`).

```
$ nix-shell -p python3
these 57 paths will be fetched (110.27 MiB download, 457.63 MiB unpacked):
  /nix/store/mmy4fc1arb2ig642chgprgms27vk9hgn-acl-2.3.1
  /nix/store/vbb1l2krfp75m5w3y2h52l0pbq6fydz8-attr-2.5.1
  /nix/store/q1c2flcykgr4wwg5a6h450hxbk4ch589-bash-5.2-p15
  /nix/store/x88ivkf7rmrhd5x3cvyv5vh3zqqdnhsk-bash-interactive-5.2-p15
```

**Comment by samuela** [comment]
yup, that works for me! thanks @Hoverbear !
