### ISSUE TITLE
New M2 MacBook Pro, Determinate Graphical Installer, Nix Daemon not installed

### ISSUE THREAD

**Issue by byrongibson** [DeterminateSystems/nix-installer#823]
I just purchased an Apple refurbished M2 MacBook Pro with Sonoma 14.2.1.  Used the Determinate graphical installer to install Nix on it.  However, it seems the Nix Daemon wasn't installed.  Any idea what I might have done wrong?

Installer runs without error.  Creating the first flake.nix with `nix flake init -t nix-darwin` also works without error.  But `nix run nix-darwin -- switch --flake .` gives these errors:

```
byrongibson@MacBook-Pro-2 config % nix run nix-darwin -- switch --flake .
error: cannot connect to socket at '/nix/var/nix/daemon-socket/socket': Connection refused
byrongibson@MacBook-Pro-2 config % nix run nix-darwin -- switch --flake .MacBook-Pro-2
error: cannot connect to socket at '/nix/var/nix/daemon-socket/socket': Connection refused
byrongibson@MacBook-Pro-2 config % nix run nix-darwin -- switch --flake .#MacBook-Pro-2
error: cannot connect to socket at '/nix/var/nix/daemon-socket/socket': Connection refused
```
Seems the daemon doesn't exist:

```
byrongibson@MacBook-Pro-2 config % launchctl print system/org.nixos.nix-daemon
Bad request.
Could not find service "org.nixos.nix-daemon" in domain for system
```

`byrongibson` is the system's main Admin user.  The only changes I made to the default flake are:

````
      ....
      # The platform the configuration will be used on.
      #nixpkgs.hostPlatform = "x86_64-darwin";
      nixpkgs.hostPlatform = "aarch64-darwin";
    };
  in
  {
    # Build darwin flake using:
    # $ darwin-rebuild build --flake .#simple
    #darwinConfigurations."simple" = nix-darwin.lib.darwinSystem {
    darwinConfigurations."MacBook-Pro-2" = nix-darwin.lib.darwinSystem {
      modules = [ configuration ];
    };

    # Expose the package set, including overlays, for convenience.
    #darwinPackages = self.darwinConfigurations."simple".pkgs;
    darwinPackages = self.darwinConfigurations."MacBook-Pro-2".pkgs;
  };
````

**Comment by Hoverbear** [comment]
Based on https://github.com/DeterminateSystems/nix-installer/issues/824 evidence suggests that for some reason your nix store volume failed, or possibly even the launchd service we created did not work right.

I'm curious if the APFS volume got created, or if it was an issue with the service... Is there any chance you checked `Disk Utility` and saw a Nix Store before you uninstalled?

**Comment by byrongibson** [comment]
Thanks, I didn't check Disk Utility unfortunately, however [uninstalling](https://discord.com/channels/1116012109709463613/1116664639896424572/1198499966902079609) with `/nix/nix-installer uninstall` and reinstalling [fixed that problem](https://discourse.nixos.org/t/new-apple-silicon-macbook-nix-installation-questions/38592/).

However, there's a new problem which is that `nix run nix-darwin -- switch --flake .` appears to not work on a Standard non-Admin user account.  Is that the case, that Nix Darwin only works on Admin accounts?

```
bgibson@MacBook-Pro-2 config % nix run nix-darwin -- switch --flake .
building the system configuration...
warning: Ignoring setting 'auto-allocate-uids' because experimental feature 'auto-allocate-uids' is not enabled
warning: Ignoring setting 'impure-env' because experimental feature 'configurable-impure-env' is not enabled
Password:
bgibson is not in the sudoers file.
This incident has been reported to the administrator.
```

**Comment by zupo** [comment]
I use a Standard non-Admin user account too. Whenever I need sudo (for example, running the nix-darwin switch), I then use https://github.com/SAP/macOS-enterprise-privileges/ to temporarily get sudo.

**Comment by byrongibson** [comment]
Some updates, having problems whether I run it as a standard user or under sudo:

1.  `nix upgrade-nix` downgraded from nix-2.19.2 to nix-2.18.1
2.  error: `/Users/bgibson is not owned by you` when running `nix upgrade-nix` under sudo.  I'm running the command under the bgibson account, however the first and original account on this mac is /Users/byrongibson which may be the sudo user.  The 'upgrade' still completed despite this error, though it was actually a downgrade. 
3.  no commands work now, all give the error to enable nix-command with the extra features flag.

```
bgibson@MacBook-Pro-2 ~ % bgibson@MacBook-Pro-2 ~ % nix upgrade-nix
replacing old 'nix-2.19.2'
installing 'nix-2.18.1'
error: opening lock file '/nix/var/nix/profiles/default.lock': Permission denied
error: program '/nix/store/53r8ay20mygy2sifn7j2p8wjqlx2kxik-nix-2.19.2/bin/nix-env' failed with exit code 1

bgibson@MacBook-Pro-2 ~ % sudo nix upgrade-nix
Password:
warning: $HOME ('/Users/bgibson') is not owned by you, falling back to the one defined in the 'passwd' file ('/var/root')
[0.0 MiB DL] verifying that '/nix/store/0pbq6wzr2f1jgpn5212knyxpwmkjgjah-nix-2.18.1' works...warning: $HOME ('/Users/bgibson') is not owned by you, falling back to the one defined in the 'passwd' file ('/var/root')
warning: $HOME ('/Users/bgibson') is not owned by you, falling back to the one defined in the 'passwd' file ('/var/root')
replacing old 'nix-2.19.2'
installing 'nix-2.18.1'

bgibson@MacBook-Pro-2 ~ % nix --version
nix (Nix) 2.18.1

bgibson@MacBook-Pro-2 ~ % nix search pip3
error: experimental Nix feature 'nix-command' is disabled; use '--extra-experimental-features nix-command' to override
bgibson@MacBook-Pro-2 ~ % nix search pip3 --extra-experimental-features nix-command
error: experimental Nix feature 'flakes' is disabled; use '--extra-experimental-features flakes' to override
```

Any suggestions what to do here?

**Comment by Hoverbear** [comment]
> nix upgrade-nix downgraded from nix-2.19.2 to nix-2.18.1

Yes `nix upgrade-nix` consults a remote URL (eg https://github.com/DeterminateSystems/nix-upgrade/blob/main/versions.nix) and uses the version mentioned there. You can review that path in `nix.conf`

> error: /Users/bgibson is not owned by you when running nix upgrade-nix under sudo. I'm running the command under the bgibson account, however the first and original account on this mac is /Users/byrongibson which may be the sudo user. The 'upgrade' still completed despite this error, though it was actually a downgrade.

This is a warning, and it did work (yay!). I'm sorry, this project can't control Nix's behavior.

> no commands work now, all give the error to enable nix-command with the extra features flag.

Yes, you need to update your `/etc/nix/nix.conf` with the required features `extra-experimental-features = nix-command flakes`.

I don't know how your `nix.conf` changed.

**Comment by byrongibson** [comment]
> I don't know how your `nix.conf` changed.

Thanks, oddly it's not even there.  I have `/etc/nix`, but it's completely empty.  Does the Determinate installer automatically create nix.conf, and I somehow deleted it?  Or is nix.conf something I have to manually create after the installer finishes, and I just forgot?  Pretty sure I didn't intentionally delete it.  Here are my nix-related paths:

```
bgibson@MacBook-Pro-2 ~ % ls -al nix/darwin/config/
total 24
drwxr-xr-x@ 5 bgibson  staff   160 Jan 24 00:27 .
drwxr-xr-x@ 3 bgibson  staff    96 Jan 20 15:55 ..
-rw-r--r--@ 1 bgibson  staff  1623 Jan 22 14:47 flake.default.nix
-rw-r--r--@ 1 bgibson  staff  1094 Jan 22 14:50 flake.lock
-rw-r--r--@ 1 bgibson  staff  1879 Jan 24 00:27 flake.nix
```

```
bgibson@MacBook-Pro-2 ~ % ls -al /etc/nix/
total 0
drwxr-xr-x   2 root  wheel    64 Jan 23 02:15 .
drwxr-xr-x  87 root  wheel  2784 Jan 23 07:40 ..
```

```
bgibson@MacBook-Pro-2 ~ % ls -al /nix/
total 13504
drwxr-xr-x     9 root  wheel       288 Jan 23 07:40 .
drwxr-xr-x    20 root  wheel       640 Jan 11 23:19 ..
d-wx--x--t     4 root  wheel       128 Jan 20 22:56 .Trashes
-rw-r--r--     1 root  wheel         0 Jan 23 07:40 .nix-installer-hook.err.log
-rw-r--r--     1 root  wheel         0 Jan 23 07:40 .nix-installer-hook.out.log
-rwxr-xr-x     1 root  wheel   6879520 Jan  8 13:17 nix-installer
-rw-r--r--     1 root  wheel     32642 Jan 20 22:57 receipt.json
drwxrwxr-t@ 3257 root  nixbld   104224 Feb  1 22:39 store
drwxr-xr-x@    4 root  wheel       128 Jan 20 22:56 var
```

**Comment by Hoverbear** [comment]
The installer will provision a `/etc/nix/nix.conf` for you in normal cases.

**Comment by byrongibson** [comment]
> The installer will provision a `/etc/nix/nix.conf` for you in normal cases.

Ok thanks, then I'm thinking maybe I should uninstall and reinstall it.  Seems borked somehow.

**Comment by byrongibson** [comment]
> FWIW, I use a Standard non-Admin user account too. Whenever I need sudo (for example, running the nix-darwin switch), I then use https://github.com/SAP/macOS-enterprise-privileges/ to temporarily get sudo.

Btw did you install Privileges first and then Nix?  or Nix first?

**Comment by zupo** [comment]
I believe I tried both, and it works for both.

**Comment by byrongibson** [comment]
> I believe I tried both, and it works for both.

Oh, and did you install Nix with admin or standard privileges?

**Comment by zupo** [comment]
With admin.
