### ISSUE TITLE
Nix uninstall error (uninstalling graphical installer on M2 MBP)

### ISSUE THREAD

**Issue by byrongibson** [DeterminateSystems/nix-installer#824]
I got the following error when running `/nix/nix-installer uninstall` on an M2 MBP with Sonoma 14.2.1.  The laptop is new, with not much installed.  Running under admin user.  FileVault enabled.  I uninstalled b/c the graphical installer failed to install the daemon, as detailed [here](https://github.com/DeterminateSystems/nix-installer/issues/823).  Am attempting a reinstall.

## Error
```
Error: 
   0: Error reverting
   0: Action `bootstrap_launchctl_service` errored
      Failed to execute command with status 5 `"launchctl" "bootout" "system" "/Library/LaunchDaemons/org.nixos.darwin-store.plist"`, stdout: 
      stderr: Boot-out failed: 5: Input/output error
```

## Metadata
|key|value|
|--|--|
|**version**|0.16.0|
|**os**|macos|
|**arch**|aarch64|

**Comment by Hoverbear** [comment]
This is generally a sign that there is something wrong with your Nix Store APFS volume that should have been created, or the service that is supposed to mount it.

I wonder if Sonoma has somehow changed things...
