### ISSUE TITLE
unattended .iso installer

### ISSUE THREAD

**Issue by bam80** [DeterminateSystems/nix-installer#839]
Hi,
Is there way to embed this installer to unattended installation .iso image?

**Comment by Hoverbear** [comment]
Hi! Yes it can, you can call it like any other program and there is a `--no-confirm`.

**Comment by bam80** [comment]
I see, but I interested in the details - how would I build such an image, exactly?

Sorry I'm new to Nix and need the detailed instructions.

**Comment by Hoverbear** [comment]
I do not know enough details about your situation to offer you much input other than "Have whatever install script or automation you're using do call the installer with `--no-confirm` as one of the steps."

If you have a more detailed question perhaps I can offer a more detailed answer.

**Comment by bam80** [comment]
Thanks.
I need to generate an unattended .iso image to flash to SD card to install Nix to new NVMe of my Chromebox.
UEFI firmware there boots from the SD card as a last resort so ideally no keyboard intervention should be needed.

After the unattended installation procedure I expect wireless SSH access to the installed OS, then I could tune the system further.

**Comment by Hoverbear** [comment]
Judging by your lack of description of the target OS, I assume you are intending to install NixOS?

This installer is for Nix, which NixOS comes with by default.

**Comment by bam80** [comment]
> I assume you are intending to install NixOS?

That's right

**Comment by bam80** [comment]
@Hoverbear there is no target OS on my Chromebox as I inserted new clean NVMe there, so only way to install something is from SD/USB stick which I need to prepare first.

**Comment by Hoverbear** [comment]
As I noted above this project installs Nix, not NixOS, so this project won't help you install an operating system such as NixOS.

If you get a Linux distribution installed, you can probably install Nix using this project through the instructions in the `README.md`.

I wish you the best of luck in the endeavor!

**Comment by bam80** [comment]
Oh, sorry, I didn't realize the difference.
Maybe some warning about it worth to be present somewhere.
Thanks.
