### ISSUE TITLE
How to pick up fixes in nix-installer?

### ISSUE THREAD

**Issue by jschear** [DeterminateSystems/nix-installer#840]
I'd like to pick up #672 (thank you; excited to no longer have to modify `/etc/zshrc` myself after a macOS upgrade!).

Is there a way to upgrade `nix-installer` and apply any new changes in the installer? (Or is the best course of action to uninstall `nix` with the version of the installer I used to install it, then reinstall it with the latest `nix-installer` release?)

**Comment by Hoverbear** [comment]
That's probably the right idea!
