### ISSUE TITLE
nix upgrade-nix

### ISSUE THREAD

**Issue by bestlem** [DeterminateSystems/nix-installer#848]
Your documentation says that this will upgrade nix to the version in [this linl](https://raw.githubusercontent.com/NixOS/nixpkgs/master/nixos/modules/installer/tools/nix-fallback-paths.nix)
which shows 2.18.1

Two issues here

1. This is less than the version that nix-installer installed which is 2.19.1
2. How do you upgrade to the latest which is 2.20.

**Comment by bestlem** [comment]
See PR https://github.com/DeterminateSystems/nix-installer/pull/811 for a fix to the documentation - although wouldn't it be better to have the correct versions in there?

**Comment by develop7** [comment]
> How do you upgrade to the latest which is 2.20.

@bestlem see https://github.com/DeterminateSystems/nix-installer/issues/744#issuecomment-1991934085

**Comment by cole-h** [comment]
Resolved by https://github.com/DeterminateSystems/nix-installer/pull/854 (which included #811)

https://github.com/DeterminateSystems/nix-installer?tab=readme-ov-file#upgrading-nix links to https://github.com/DeterminateSystems/nix-upgrade/blob/main/versions.nix which is where we're maintaining a more-frequently-updated list of official, recent Nix "fallback" store paths.

**Comment by tcoopman** [comment]
this link: https://github.com/DeterminateSystems/nix-upgrade/blob/main/versions.nix doesn't exist?

**Comment by grahamc** [comment]
Hey @tcoopman, the canonical source for the file is https://install.determinate.systems/nix-upgrade/stable/universal. We used to commit it to the repository, but it is now a build product.

You can put this in your nix.conf to get it:

```
upgrade-nix-store-path-url = https://install.determinate.systems/nix-upgrade/stable/universal
```

We also have a flake that exposes our current Nix release and configuration as NixOS, nix-darwin, and home-manager modules: https://flakehub.com/flake/DeterminateSystems/nix

**Comment by abathur** [comment]
@grahamc Connecting the dots, since I ended up here via someone's comment on Discourse--the link below from the README points at the path Thomas asked about:

https://github.com/DeterminateSystems/nix-installer/blob/1fb0dc511617fcc08701083a1fda571d8e076db3/README.md?plain=1#L98-L100
