### ISSUE TITLE
On macOS, need to enter Nix Store disk password on every startup

### ISSUE THREAD

**Issue by forketyfork** [DeterminateSystems/nix-installer#857]
After running nix-installer on macOS, I now get the following message on every startup. Setting the "Remember..." checkbox doesn't seem to have any effect.
nix-installer 0.16.1, macOS Sonoma 14.3.1, aarch64, APFS encrypted

<img width="542" alt="Screenshot 2023-11-04 at 08 54 25" src="https://github.com/DeterminateSystems/nix-installer/assets/1592872/323fcb19-6502-4441-89fc-4439045d34fa">

**Comment by Hoverbear** [comment]
It seems the password did not get correctly saved to your Mac keychain. Could you try uninstalling (`/nix/nix-installer uninstall`) and checking your keychain for any "Nix Store" passwords? It may be some old password is conflicting or something.

**Comment by forketyfork** [comment]
Thanks for the response, no luck so far. 

I've uninstalled `nix-darwin` and `nix` itself as you proposed, then checked out the keychain. I had two `Nix Store` entries in the `login` keychain containing my own password, and one `Nix Store encryption password` entry in the `System` keychain storing some long random string. I've removed all three.

Then I've installed `nix` and `nix-darwin` again (hitting #810 along the way). Now I see this window again. I've set the "Remember..." checkbox, but it didn't help, as before. I've checked out the keychain again. I now have `Nix Store` in `login` with my password and `disk3 encryption password` in `System` with a long random string.

**Comment by stephan-koenig** [comment]
@forketyfork Assuming that FileVault is activated on your Mac and `Nix Store` is on your primary drive, as far as I understand, there is no need to encrypt the new volume since FileVault takes care of that. It seems like the default planner uses the option to encrypt the volume, but the macOS planner does not (I filed issue #891). So, just install using the macOS planner:

```
curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix | sh -s -- install macos
```

**Comment by forketyfork** [comment]
@stephan-koenig thank you, this helped!

**Comment by sambacha** [comment]
# Associated Nix System Keychain credentials


> [!IMPORTANT]
>  The password it is requesting is stored in your System Keychain. 

### Keychain Access Application, searching for 'nix'

<img width="1234" alt="nix_macos_keychain_access_ref" src="https://github.com/DeterminateSystems/nix-installer/assets/32783916/06a130eb-6d7f-4592-9f77-53b0165a714d">



<br>


### Checking for stored encrypted keychain passwords for nix store

You can check your keychain[^1] for any "Nix Store" passwords. You can open Keychain Access via `x-help-action://openApp?bundleId=com.apple.keychainaccess`[^2]

The reason why your password does not work is that there is a secure password generated at install that is used and stored in the keychain! Here is an example of the password that could be used (generated using `openssl rand -hex 32`) 

> [!WARNING]    
> DO NOT Manually change the password, either delete it or do not touch it!

~~~conf
8c493f2bde73c75fee03dd72d02cd2b9597076259152b75907718236f5066e6a
~~~

This is created at install, and is added automatically by the Nix installer for use by `/Library/LaunchDaemons/org.nixos.darwin-store.plist` 


#### Footnotes

[^1]: keychain access docs: https://support.apple.com/guide/keychain-access/welcome/11.0/mac/14.4 
[^2]: support doc on keychain access: https://support.apple.com/guide/keychain-access/delete-a-keychain-kyca2423/11.0/mac/14.4
