### ISSUE TITLE
error: experimental Nix feature 'auto-allocate-uids' is disabled; use '--extra-experimental-features auto-allocate-uids' to override

### ISSUE THREAD

**Issue by jongschneider** [DeterminateSystems/nix-installer#860]
I’ve been using nix with nix-darwin to manage my Mac system for the past month.

**My setup is as follows:**
macOS Sonoma version 14.3.1
Nix downloaded using [The Determinate Nix Installer](https://zero-to-nix.com/concepts/nix-installer)
Nix Installer Version: `nix-installer 0.14.0`
architecture: `aarch64-darwin`
Nix-Darwin downloaded using [Flake installation](https://zero-to-nix.com/concepts/nix-installer).

---
Last night I was browsing github and looking at various darwin nix configurations and came across [this repo](https://github.com/Cu3PO42/gleaming-glacier/blob/5abb8c0a3fb72cafbc7ca113e5f135142d0b51c8/features/darwin/base.nix#L20C7-L20C25) that sets

    extraOptions = ''
      extra-nix-path = nixpkgs=flake:nixpkgs
      auto-allocate-uids = true             <--- the big problem!!!
      build-users-group = nixbld
      experimental-features = nix-command flakes auto-allocate-uids
    '';
Ever since I added this extraOption and rebuilt my system using `darwin-rebuild switch --flake ~/PATH/TO/MY-NIX-DARWIN-CONFIG/` I can no longer do anything using the nix cli.

```
❯ darwin-rebuild switch --flake ~/PATH/TO/MY-NIX-DARWIN-CONFIG/
building the system configuration...
error: experimental Nix feature 'auto-allocate-uids' is disabled; use '--extra-experimental-features auto-allocate-uids' to override
❯ nix develop
error: experimental Nix feature 'auto-allocate-uids' is disabled; use '--extra-experimental-features auto-allocate-uids' to override
```

I found [this github PR](https://github.com/NixOS/nix/pull/3600) related to the experimental feature auto-uid-allocation which states:

> No, this will never work on macOS since it requires cgroups.

My current state is that the programs I’ve previously installed work. But I cannot update my computer using nix in any way - no new programs, no flake updates, no darwin configuration changes, etc. So my laptop is not bricked. It just is in stasis and I need to use conventional package management for my applications. And dev environments no longer work (rip nix develop).

So now I’m wondering what are my options?
**Here are some things I’ve tried that have not worked:**
* I removed auto-allocate-uids = true from my config.
* I tried passing --extra-experimental-features auto-allocate-uids flag with my nix commands.
* I tried uninstalling nix using `/nix/nix-installer uninstall` to start from scratch and reinstall I get:
```
❯ /nix/nix-installer uninstall
`nix-installer` needs to run as `root`, attempting to escalate now via `sudo`...
`nix-darwin` installation detected, it must be removed before uninstalling Nix. Please refer to https://github.com/LnL7/nix-darwin#uninstalling for instructions how to uninstall `nix-darwin`.
```
* Even after having uninstalled nix-darwin using the nix-darwin uninstall script, I get the error above. I guess nix isn't recognizing that `/run/current-system` was deleted... That's basically all the nix-darwin uninstall script does.
* I looked through the uninstall rust code to determine the source of this error message and it looks like it's coming from [here](https://github.com/DeterminateSystems/nix-installer/blob/09ddc9be6b26d7bc5622b040b4dae5064170e1d6/src/planner/macos.rs#L274-L295) but I don't write rust and so my ability to debug the issue locally was pretty much a non-starter.
* I tried manually updating my nix.conf file in the nix store where the current symlink of /etc/static/nix/nix.conf points to. After it didn't solve the problem, I put it back to how it was before...

Is there any way to get past this? Any help would be greatly appreciated. I really love nix and am devastated that I broke it.

**Comment by jongschneider** [comment]
@cole-h 
Thanks for your quick reply.

I got similar advice over [here](https://discourse.nixos.org/t/nix-on-macos-now-fails-because-i-set-auto-allocate-uids-true-like-an-idiot/40210) and did the following to fix the issue:

---

For anyone in the future who borks their system in a similar fashion, the fix was:

1. use `ls -alh /etc/static/nix/nix.conf` and follow the symlinks to find the source location of `nix.conf` in the nix store.
2. update this file in the store by removing `auto-allocate-uids = true` if it's there (it's read only by default so you will have to adjust the privileges save your changes).
3. restart the nix daemon
```
sudo launchctl stop org.nixos.nix-daemon
sudo launchctl start org.nixos.nix-daemon
```

The big trick I was missing was manually restarting the nix daemon. It's all working now. Thanks a lot!

**Comment by cole-h** [comment]
Ah, yep, I always forget about restarting the daemon too :laughing: Glad you got it fixed!

**Comment by jeeftor** [comment]
Could you use this option: https://daiderd.com/nix-darwin/manual/index.html#opt-environment.etc._name_.copy
