### ISSUE TITLE
<autogenerated-issue> Tried to uninstall. /nix and ~/.nix-profile not deleted.

### ISSUE THREAD

**Issue by agingorange** [DeterminateSystems/nix-installer#867]
## Error
```
Error: 
   0: Error reverting
   0: Action `create_apfs_volume` errored
      Failed to execute command with status 1 `"/usr/sbin/diskutil" "apfs" "deleteVolume" "Nix Store"`, stdout: Started APFS operation
      Deleting APFS Volume from its APFS Container
      Unmounting disk3s8
      The volume "Nix Store" on disk3s8 couldn't be unmounted because it is in use by process 0 (kernel)

      stderr: Error: -69888: Couldn't unmount disk



```

## Metadata
|key|value|
|--|--|
|**version**|0.16.1|
|**os**|macos|
|**arch**|aarch64|

---
I've since restarted, and was asked to enter a password to unlock `nix`. I entered my login password, but apparently that's not correct. So /nix probably still exists, but it's not mounted.

I couldn't find the extra users in System Settings so I'm hoping they're gone. I could remove the Nix Store with Disk Utility. 

Have I done what the installer was set to do?

**Comment by sambacha** [comment]
# Manually removing associated Nix System Keychain credentials


> [!IMPORTANT]
>  The password it is requesting is stored in your System Keychain. 

### Keychain Access Application, searching for 'nix'

<img width="1234" alt="nix_macos_keychain_access_ref" src="https://github.com/DeterminateSystems/nix-installer/assets/32783916/06a130eb-6d7f-4592-9f77-53b0165a714d">



<br>


### Manually removing the encrypted keychain passwords for your nix store

Try uninstalling (`/nix/nix-installer uninstall`) and checking your keychain[^1] for any "Nix Store" passwords. You can open Keychain Access via `x-help-action://openApp?bundleId=com.apple.keychainaccess`[^2]

The reason why your password does not work is that there is a secure password generated at install that is used and stored in the keychain! Here is an example of the password that could be used (generated using `openssl rand -hex 32`) 

> [!WARNING]    
> DO NOT Manually change the password, either delete it or do not touch it!

~~~conf
8c493f2bde73c75fee03dd72d02cd2b9597076259152b75907718236f5066e6a
~~~

This is created at install, and is added automatically by the Nix installer for use by `/Library/LaunchDaemons/org.nixos.darwin-store.plist` 


#### Footnotes

[^1]: keychain access docs: https://support.apple.com/guide/keychain-access/welcome/11.0/mac/14.4 
[^2]: support doc on keychain access: https://support.apple.com/guide/keychain-access/delete-a-keychain-kyca2423/11.0/mac/14.4

**Comment by agingorange** [comment]
Thanks for the response. I just saw the partition "magically" disappeared. It's been too long for me and can't remember if I did anything special after I asked this.
