### ISSUE TITLE
Installer not working under wezterm

### ISSUE THREAD

**Issue by amlanjlahkar** [DeterminateSystems/nix-installer#868]
## Error
```
Error: 
   0: Couldn't get terminal
```

## Metadata
|key|value|
|--|--|
|**version**|0.17.0|
|**os**|macos|
|**arch**|aarch64|

I've no prior experience with nix.
I wanted to give it a go for the first time but instead got this right after giving root privilege. The issue however doesn't occur when executed from within the default macOS terminal.

**Comment by cole-h** [comment]
It sounds like you don't have wezterm's terminfo loaded. That message is coming from here: https://github.com/DeterminateSystems/nix-installer/blob/06eaf882e644a63671cff33770f01481b08877d9/src/cli/interaction.rs#L23-L24

Could you try out https://github.com/DeterminateSystems/nix-installer/pull/869 and see if that works for you? If you wait for https://github.com/DeterminateSystems/nix-installer/actions/runs/8072414132/job/22054104053?pr=869 to succeed (which might take a while), you should be able to try it out with:

```sh
curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix/pr/869 | sh -s -- install
```

**Comment by amlanjlahkar** [comment]
I do have wezterm terminfo loaded but don't know why it's not being detected. I was tmux previously but it didn't work even outside of tmux.
Using the fallback patch fixes the problem

**Comment by axelsimon** [comment]
Ah ha, this happened to me using Alacritty.
Sadly, copying over the terminfo for Alacritty and importing that didn't solve it, but setting `export TERM=xterm-color` did.
