### ISSUE TITLE
Append the actual nix-installer version information in nix.conf

### ISSUE THREAD

**Issue by sambacha** [DeterminateSystems/nix-installer#898]
While this is somewhat useful, why not just embed the actual version information within the `nix.conf` file instead of just referring back to the CLI, which may change independent of the underlying nix install?

```conf
# Generated by https://github.com/DeterminateSystems/nix-installer.
# See `/nix/nix-installer --version` for the version details.

build-users-group = nixbld
experimental-features = nix-command flakes repl-flake
bash-prompt-prefix = (nix:$name)\040
max-jobs = auto
extra-nix-path = nixpkgs=flake:nixpkgs
```

```conf
# Generated by https://github.com/DeterminateSystems/nix-installer
# nix-installer 0.15.1

**Comment by cole-h** [comment]
We used to do this, but that made it difficult to install `nix-darwin` after using our installer, since the content was not deterministic (due to the version changing); see https://github.com/DeterminateSystems/nix-installer/pull/710 and its linked issues.

Is there a reason `/nix/nix-installer --version` isn't sufficient?

**Comment by sambacha** [comment]
> We used to do this, but that made it difficult to install `nix-darwin` after using our installer, since the content was not deterministic (due to the version changing); see #710 and its linked issues.
> 
> Is there a reason `/nix/nix-installer --version` isn't sufficient?

the `/nix/nix-installer` binary was removed during a failed upgrade. I had to clean up the leftover files to get the installer to install correctly again. So it would normally be fine, unless you had an unsucessful removal and were trying to see what the version was.
