### ISSUE TITLE
Fails to install in OrbStack 

### ISSUE THREAD

**Issue by SuperKenVery** [DeterminateSystems/nix-installer#955]
## Error
```
Error: 
   0: Install failure
   1: Error executing action
   2: Action `configure_nix` errored
   3: Action `setup_default_profile` errored
   4: Failed to execute command with status 1 `HOME="/root" NIX_SSL_CERT_FILE="/nix/store/47h1qcdfp2gp7qlzpa41zgmg6drvmrkz-nss-cacert-3.95/etc/ssl/certs/ca-bundle.crt" "/nix/store/00dc6iygj63mjcmixki1vwg7m1jbdi9p-nix-2.21.2/bin/nix-env" "-i" "/nix/store/00dc6iygj63mjcmixki1vwg7m1jbdi9p-nix-2.21.2"`, stdout: 
      stderr: installing 'nix-2.21.2'
      error:
             … while setting up the build environment

             error: unable to load seccomp BPF program: Invalid argument


```

## Metadata
|key|value|
|--|--|
|**version**|0.19.0|
|**os**|linux|
|**arch**|x86_64|

In OrbStack on macOS. OrbStack is a virtual machine for macOS but uses container to create multiple VMs. The installer is effectively run in a lxc container (I believe).

**Comment by cole-h** [comment]
Does this section in the README help: https://github.com/DeterminateSystems/nix-installer?tab=readme-ov-file#in-a-container? (It does explicitly call out Docker/Podman, but it may also apply for LXC.)

If not, you might also want to look at this comment: https://github.com/DeterminateSystems/nix-installer/issues/324#issuecomment-1491888268

**Comment by SuperKenVery** [comment]
Thanks. 

The README didn't help; this helped:
```
--extra-conf='filter-syscalls = false'
```

I wish it were better documented, or even better, the installer detects ebpf support and adds this config automatically 👍
