### ISSUE TITLE
nix installer on alpine linux(userland)

### ISSUE THREAD

**Issue by pwnwriter** [DeterminateSystems/nix-installer#958]
I'm having following issue while installing nix with `determinate nix installer` . I do have sudo installed but seems like the flag it seems isn't available. 

<img width="551" alt="Screenshot 2024-05-08 at 4 42 29 PM" src="https://github.com/DeterminateSystems/nix-installer/assets/90331517/3645e906-f2ae-42f0-8b45-a70ddb6cdcef">

**Comment by cole-h** [comment]
Which version of `sudo` are you running with (should be able to run `sudo --version` to find out)?

**Comment by cole-h** [comment]
Feel free to reopen if you can provide more information!
