### ISSUE TITLE
Error reading receipt: No such file or directory

### ISSUE THREAD

**Issue by vsingh-singlestore** [DeterminateSystems/nix-installer#979]
## Error
```
Error: 
   0: Reading receipt
   1: No such file or directory (os error 2)
```

## Metadata
|key|value|
|--|--|
|**version**|0.19.0|
|**os**|linux|
|**arch**|x86_64|

**Comment by cole-h** [comment]
This looks very similar to https://github.com/DeterminateSystems/nix-installer/issues/952. Did you try to uninstall using upstream's uninstallation instructions instead of `/nix/nix-installer uninstall`?

**Comment by cole-h** [comment]
Feel free to reopen if you can provide more information!
