### ISSUE TITLE
<autogenerated-issue>

### ISSUE THREAD

**Issue by ncontinanza** [DeterminateSystems/nix-installer#986]
## Error
```
Error: 
   0: Install failure
   1: Error executing action
   2: Action `create_nix_volume` errored
   3: Action `kickstart_launchctl_service` errored
   4: Failed to execute command with status 113 `"launchctl" "kickstart" "-k" "system/org.nixos.darwin-store"`, stdout: 
      stderr: Could not find service "org.nixos.darwin-store" in domain for system


```

## Metadata
|key|value|
|--|--|
|**version**|0.19.0|
|**os**|macos|
|**arch**|aarch64|

**Comment by cole-h** [comment]
This seems very similar to https://github.com/DeterminateSystems/nix-installer/issues/960 (and the related issues I call out in https://github.com/DeterminateSystems/nix-installer/issues/960#issuecomment-2104730686). Could you check that out and see if it helps?

I'm going to close this on the assumption that the referenced comment will help, but please feel free to comment or reopen if the issue still occurs and we'll try to help further.
