### ISSUE TITLE
Group `nixbld` existed but had a different gid (996) than planned (30000)

### ISSUE THREAD

**Issue by Forecastr-sci** [DeterminateSystems/nix-installer#999]
## Error
```
Error: 
   0: Planner error
   1: Error executing action
   2: Action `create_group` errored
   3: Group `nixbld` existed but had a different gid (996) than planned (30000)
```

## Metadata
|key|value|
|--|--|
|**version**|0.19.0|
|**os**|linux|
|**arch**|x86_64|

NOTE: This is from WSL Debian

**Comment by cole-h** [comment]
This sounds like you previous installed Nix somehow. If you used the official scripts, you may need to follow their uninstallation steps: https://nix.dev/manual/nix/stable/installation/uninstall.html#uninstalling-nix

If you're feeling adventurous, it may work if you specify the nixbld group gid to the already-existing one:

```console
$ curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix | sh -s -- install --nix-build-group-id 996
```

but I can't guarantee other things won't break.

**Comment by Forecastr-sci** [comment]
Thank you, I tried using official installation script and it also reported that group nixbld already exists. I had to delete all the users in that group and then delete the group itself using shell script found here: https://discourse.nixos.org/t/i-have-removed-all-nixbld-users-and-nixbld-group-by-excute/46062
`for i in $(seq 1 32); do
  sudo userdel nixbld$i
done
sudo groupdel nixbld`

I'm not sure why that could happen, but I installed Devbox before using your script and yes, there were several attempts to install nix with official script before this one
